/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChatInput: typeof import('./src/components/ai/AiChatInput.vue')['default']
    AiConfirmCard: typeof import('./src/components/ai/AiConfirmCard.vue')['default']
    AiFloatingBubble: typeof import('./src/components/ai/AiFloatingBubble.vue')['default']
    AiFormAssist: typeof import('./src/components/ai/AiFormAssist.vue')['default']
    AiMessageBubble: typeof import('./src/components/ai/AiMessageBubble.vue')['default']
    AiQuickAsk: typeof import('./src/components/ai/AiQuickAsk.vue')['default']
    AiSuggestionChips: typeof import('./src/components/ai/AiSuggestionChips.vue')['default']
    MobileLayout: typeof import('./src/components/MobileLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanIcon: typeof import('vant/es')['Icon']
  }
}
