FROM nginx:1.27-alpine
COPY dist /usr/share/nginx/html
COPY mobile-dist /usr/share/nginx/html/m
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ssl /etc/nginx/ssl
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
