// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounting_integration.sql

package store

import (
	"context"
	"encoding/json"
)

const countOutboxByStatus = `-- name: CountOutboxByStatus :many
SELECT status, COUNT(*) as count
FROM accounting_outbox
WHERE company_id = $1
GROUP BY status
`

type CountOutboxByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountOutboxByStatus(ctx context.Context, companyID int64) ([]CountOutboxByStatusRow, error) {
	rows, err := q.db.Query(ctx, countOutboxByStatus, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountOutboxByStatusRow{}
	for rows.Next() {
		var i CountOutboxByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createAccountingLink = `-- name: CreateAccountingLink :one
INSERT INTO accounting_links (
    company_id, provider, remote_company_id, api_endpoint,
    api_key_enc, webhook_secret, jurisdiction, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, company_id, provider, remote_company_id, api_endpoint, api_key_enc, webhook_secret, jurisdiction, status, last_synced_at, created_at, updated_at
`

type CreateAccountingLinkParams struct {
	CompanyID       int64  `json:"company_id"`
	Provider        string `json:"provider"`
	RemoteCompanyID string `json:"remote_company_id"`
	ApiEndpoint     string `json:"api_endpoint"`
	ApiKeyEnc       string `json:"api_key_enc"`
	WebhookSecret   string `json:"webhook_secret"`
	Jurisdiction    string `json:"jurisdiction"`
	Status          string `json:"status"`
}

func (q *Queries) CreateAccountingLink(ctx context.Context, arg CreateAccountingLinkParams) (AccountingLink, error) {
	row := q.db.QueryRow(ctx, createAccountingLink,
		arg.CompanyID,
		arg.Provider,
		arg.RemoteCompanyID,
		arg.ApiEndpoint,
		arg.ApiKeyEnc,
		arg.WebhookSecret,
		arg.Jurisdiction,
		arg.Status,
	)
	var i AccountingLink
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.RemoteCompanyID,
		&i.ApiEndpoint,
		&i.ApiKeyEnc,
		&i.WebhookSecret,
		&i.Jurisdiction,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccountingLink = `-- name: DeleteAccountingLink :exec
DELETE FROM accounting_links
WHERE id = $1 AND company_id = $2
`

type DeleteAccountingLinkParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) DeleteAccountingLink(ctx context.Context, arg DeleteAccountingLinkParams) error {
	_, err := q.db.Exec(ctx, deleteAccountingLink, arg.ID, arg.CompanyID)
	return err
}

const getAccountingLink = `-- name: GetAccountingLink :one
SELECT id, company_id, provider, remote_company_id, api_endpoint, api_key_enc, webhook_secret, jurisdiction, status, last_synced_at, created_at, updated_at FROM accounting_links
WHERE company_id = $1 AND provider = $2
`

type GetAccountingLinkParams struct {
	CompanyID int64  `json:"company_id"`
	Provider  string `json:"provider"`
}

func (q *Queries) GetAccountingLink(ctx context.Context, arg GetAccountingLinkParams) (AccountingLink, error) {
	row := q.db.QueryRow(ctx, getAccountingLink, arg.CompanyID, arg.Provider)
	var i AccountingLink
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.RemoteCompanyID,
		&i.ApiEndpoint,
		&i.ApiKeyEnc,
		&i.WebhookSecret,
		&i.Jurisdiction,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountingLinkByID = `-- name: GetAccountingLinkByID :one
SELECT id, company_id, provider, remote_company_id, api_endpoint, api_key_enc, webhook_secret, jurisdiction, status, last_synced_at, created_at, updated_at FROM accounting_links
WHERE id = $1 AND company_id = $2
`

type GetAccountingLinkByIDParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetAccountingLinkByID(ctx context.Context, arg GetAccountingLinkByIDParams) (AccountingLink, error) {
	row := q.db.QueryRow(ctx, getAccountingLinkByID, arg.ID, arg.CompanyID)
	var i AccountingLink
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.RemoteCompanyID,
		&i.ApiEndpoint,
		&i.ApiKeyEnc,
		&i.WebhookSecret,
		&i.Jurisdiction,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAccountingLink = `-- name: GetActiveAccountingLink :one
SELECT id, company_id, provider, remote_company_id, api_endpoint, api_key_enc, webhook_secret, jurisdiction, status, last_synced_at, created_at, updated_at FROM accounting_links
WHERE company_id = $1 AND status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveAccountingLink(ctx context.Context, companyID int64) (AccountingLink, error) {
	row := q.db.QueryRow(ctx, getActiveAccountingLink, companyID)
	var i AccountingLink
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Provider,
		&i.RemoteCompanyID,
		&i.ApiEndpoint,
		&i.ApiKeyEnc,
		&i.WebhookSecret,
		&i.Jurisdiction,
		&i.Status,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAccountingOutbox = `-- name: InsertAccountingOutbox :one
INSERT INTO accounting_outbox (
    company_id, event_type, aggregate_type, aggregate_id,
    payload, idempotency_key
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, event_type, aggregate_type, aggregate_id, payload, idempotency_key, status, retry_count, max_retries, next_retry_at, sent_at, error_message, created_at
`

type InsertAccountingOutboxParams struct {
	CompanyID      int64           `json:"company_id"`
	EventType      string          `json:"event_type"`
	AggregateType  string          `json:"aggregate_type"`
	AggregateID    int64           `json:"aggregate_id"`
	Payload        json.RawMessage `json:"payload"`
	IdempotencyKey string          `json:"idempotency_key"`
}

func (q *Queries) InsertAccountingOutbox(ctx context.Context, arg InsertAccountingOutboxParams) (AccountingOutbox, error) {
	row := q.db.QueryRow(ctx, insertAccountingOutbox,
		arg.CompanyID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.IdempotencyKey,
	)
	var i AccountingOutbox
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Status,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.SentAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const listAccountingLinks = `-- name: ListAccountingLinks :many
SELECT id, company_id, provider, remote_company_id, api_endpoint, api_key_enc, webhook_secret, jurisdiction, status, last_synced_at, created_at, updated_at FROM accounting_links
WHERE company_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAccountingLinks(ctx context.Context, companyID int64) ([]AccountingLink, error) {
	rows, err := q.db.Query(ctx, listAccountingLinks, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountingLink{}
	for rows.Next() {
		var i AccountingLink
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Provider,
			&i.RemoteCompanyID,
			&i.ApiEndpoint,
			&i.ApiKeyEnc,
			&i.WebhookSecret,
			&i.Jurisdiction,
			&i.Status,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutboxByCompany = `-- name: ListOutboxByCompany :many
SELECT id, company_id, event_type, aggregate_type, aggregate_id, payload, idempotency_key, status, retry_count, max_retries, next_retry_at, sent_at, error_message, created_at FROM accounting_outbox
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOutboxByCompanyParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListOutboxByCompany(ctx context.Context, arg ListOutboxByCompanyParams) ([]AccountingOutbox, error) {
	rows, err := q.db.Query(ctx, listOutboxByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountingOutbox{}
	for rows.Next() {
		var i AccountingOutbox
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.IdempotencyKey,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.SentAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOutboxEvents = `-- name: ListPendingOutboxEvents :many
SELECT id, company_id, event_type, aggregate_type, aggregate_id, payload, idempotency_key, status, retry_count, max_retries, next_retry_at, sent_at, error_message, created_at FROM accounting_outbox
WHERE status IN ('pending', 'failed')
  AND (next_retry_at IS NULL OR next_retry_at <= NOW())
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) ListPendingOutboxEvents(ctx context.Context, limit int32) ([]AccountingOutbox, error) {
	rows, err := q.db.Query(ctx, listPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountingOutbox{}
	for rows.Next() {
		var i AccountingOutbox
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.IdempotencyKey,
			&i.Status,
			&i.RetryCount,
			&i.MaxRetries,
			&i.NextRetryAt,
			&i.SentAt,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :exec
UPDATE accounting_outbox
SET status = CASE WHEN retry_count + 1 >= max_retries THEN 'dead' ELSE 'failed' END,
    retry_count = retry_count + 1,
    next_retry_at = NOW() + (INTERVAL '1 minute' * POWER(2, retry_count)),
    error_message = $2
WHERE id = $1
`

type MarkOutboxFailedParams struct {
	ID           int64   `json:"id"`
	ErrorMessage *string `json:"error_message"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxFailed, arg.ID, arg.ErrorMessage)
	return err
}

const markOutboxSent = `-- name: MarkOutboxSent :exec
UPDATE accounting_outbox
SET status = 'sent', sent_at = NOW(), error_message = NULL
WHERE id = $1
`

func (q *Queries) MarkOutboxSent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxSent, id)
	return err
}

const updateAccountingLinkStatus = `-- name: UpdateAccountingLinkStatus :exec
UPDATE accounting_links
SET status = $3, updated_at = NOW()
WHERE id = $1 AND company_id = $2
`

type UpdateAccountingLinkStatusParams struct {
	ID        int64  `json:"id"`
	CompanyID int64  `json:"company_id"`
	Status    string `json:"status"`
}

func (q *Queries) UpdateAccountingLinkStatus(ctx context.Context, arg UpdateAccountingLinkStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccountingLinkStatus, arg.ID, arg.CompanyID, arg.Status)
	return err
}

const updateAccountingLinkSyncedAt = `-- name: UpdateAccountingLinkSyncedAt :exec
UPDATE accounting_links
SET last_synced_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAccountingLinkSyncedAt(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateAccountingLinkSyncedAt, id)
	return err
}
