// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: action_drafts.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmActionDraft = `-- name: ConfirmActionDraft :one
UPDATE action_drafts SET status = 'confirmed', updated_at = NOW()
WHERE id = $1 AND company_id = $2 AND user_id = $3 AND status = 'pending' AND expires_at > NOW()
RETURNING id, company_id, user_id, session_id, tool_name, tool_input, status, risk_level, description, result, error_message, expires_at, created_at, updated_at
`

type ConfirmActionDraftParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID int64     `json:"company_id"`
	UserID    int64     `json:"user_id"`
}

func (q *Queries) ConfirmActionDraft(ctx context.Context, arg ConfirmActionDraftParams) (ActionDraft, error) {
	row := q.db.QueryRow(ctx, confirmActionDraft, arg.ID, arg.CompanyID, arg.UserID)
	var i ActionDraft
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.SessionID,
		&i.ToolName,
		&i.ToolInput,
		&i.Status,
		&i.RiskLevel,
		&i.Description,
		&i.Result,
		&i.ErrorMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createActionDraft = `-- name: CreateActionDraft :one
INSERT INTO action_drafts (company_id, user_id, session_id, tool_name, tool_input, risk_level, description, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW() + INTERVAL '10 minutes')
RETURNING id, company_id, user_id, session_id, tool_name, tool_input, status, risk_level, description, result, error_message, expires_at, created_at, updated_at
`

type CreateActionDraftParams struct {
	CompanyID   int64           `json:"company_id"`
	UserID      int64           `json:"user_id"`
	SessionID   pgtype.UUID     `json:"session_id"`
	ToolName    string          `json:"tool_name"`
	ToolInput   json.RawMessage `json:"tool_input"`
	RiskLevel   string          `json:"risk_level"`
	Description string          `json:"description"`
}

func (q *Queries) CreateActionDraft(ctx context.Context, arg CreateActionDraftParams) (ActionDraft, error) {
	row := q.db.QueryRow(ctx, createActionDraft,
		arg.CompanyID,
		arg.UserID,
		arg.SessionID,
		arg.ToolName,
		arg.ToolInput,
		arg.RiskLevel,
		arg.Description,
	)
	var i ActionDraft
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.SessionID,
		&i.ToolName,
		&i.ToolInput,
		&i.Status,
		&i.RiskLevel,
		&i.Description,
		&i.Result,
		&i.ErrorMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const executeActionDraft = `-- name: ExecuteActionDraft :exec
UPDATE action_drafts SET status = 'executed', result = $2, updated_at = NOW()
WHERE id = $1
`

type ExecuteActionDraftParams struct {
	ID     uuid.UUID `json:"id"`
	Result []byte    `json:"result"`
}

func (q *Queries) ExecuteActionDraft(ctx context.Context, arg ExecuteActionDraftParams) error {
	_, err := q.db.Exec(ctx, executeActionDraft, arg.ID, arg.Result)
	return err
}

const expirePendingDrafts = `-- name: ExpirePendingDrafts :exec
UPDATE action_drafts SET status = 'expired', updated_at = NOW()
WHERE status = 'pending' AND expires_at < NOW()
`

func (q *Queries) ExpirePendingDrafts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expirePendingDrafts)
	return err
}

const failActionDraft = `-- name: FailActionDraft :exec
UPDATE action_drafts SET status = 'executed', error_message = $2, updated_at = NOW()
WHERE id = $1
`

type FailActionDraftParams struct {
	ID           uuid.UUID `json:"id"`
	ErrorMessage *string   `json:"error_message"`
}

func (q *Queries) FailActionDraft(ctx context.Context, arg FailActionDraftParams) error {
	_, err := q.db.Exec(ctx, failActionDraft, arg.ID, arg.ErrorMessage)
	return err
}

const getActionDraft = `-- name: GetActionDraft :one
SELECT id, company_id, user_id, session_id, tool_name, tool_input, status, risk_level, description, result, error_message, expires_at, created_at, updated_at FROM action_drafts
WHERE id = $1 AND company_id = $2 AND user_id = $3
`

type GetActionDraftParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID int64     `json:"company_id"`
	UserID    int64     `json:"user_id"`
}

func (q *Queries) GetActionDraft(ctx context.Context, arg GetActionDraftParams) (ActionDraft, error) {
	row := q.db.QueryRow(ctx, getActionDraft, arg.ID, arg.CompanyID, arg.UserID)
	var i ActionDraft
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.SessionID,
		&i.ToolName,
		&i.ToolInput,
		&i.Status,
		&i.RiskLevel,
		&i.Description,
		&i.Result,
		&i.ErrorMessage,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingDrafts = `-- name: ListPendingDrafts :many
SELECT id, company_id, user_id, session_id, tool_name, tool_input, status, risk_level, description, result, error_message, expires_at, created_at, updated_at FROM action_drafts
WHERE company_id = $1 AND user_id = $2 AND status = 'pending' AND expires_at > NOW()
ORDER BY created_at DESC
`

type ListPendingDraftsParams struct {
	CompanyID int64 `json:"company_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) ListPendingDrafts(ctx context.Context, arg ListPendingDraftsParams) ([]ActionDraft, error) {
	rows, err := q.db.Query(ctx, listPendingDrafts, arg.CompanyID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionDraft{}
	for rows.Next() {
		var i ActionDraft
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.SessionID,
			&i.ToolName,
			&i.ToolInput,
			&i.Status,
			&i.RiskLevel,
			&i.Description,
			&i.Result,
			&i.ErrorMessage,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectActionDraft = `-- name: RejectActionDraft :exec
UPDATE action_drafts SET status = 'rejected', updated_at = NOW()
WHERE id = $1 AND company_id = $2 AND user_id = $3 AND status = 'pending'
`

type RejectActionDraftParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID int64     `json:"company_id"`
	UserID    int64     `json:"user_id"`
}

func (q *Queries) RejectActionDraft(ctx context.Context, arg RejectActionDraftParams) error {
	_, err := q.db.Exec(ctx, rejectActionDraft, arg.ID, arg.CompanyID, arg.UserID)
	return err
}
