// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimAgentTask = `-- name: ClaimAgentTask :one
UPDATE agent_tasks
SET status = 'running', started_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, company_id, user_id, agent_slug, status, input, output, tokens_consumed, error_message, started_at, completed_at, created_at
`

func (q *Queries) ClaimAgentTask(ctx context.Context, id int64) (AgentTask, error) {
	row := q.db.QueryRow(ctx, claimAgentTask, id)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AgentSlug,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.TokensConsumed,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (company_id, slug, name, description, system_prompt, tools,
  cost_multiplier, is_autonomous, max_rounds, max_tokens, icon, model)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, slug, name, description, system_prompt, tools, cost_multiplier, is_active, is_autonomous, max_rounds, max_tokens, icon, created_at, updated_at, model, company_id
`

type CreateAgentParams struct {
	CompanyID      *int64         `json:"company_id"`
	Slug           string         `json:"slug"`
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	SystemPrompt   string         `json:"system_prompt"`
	Tools          []string       `json:"tools"`
	CostMultiplier pgtype.Numeric `json:"cost_multiplier"`
	IsAutonomous   bool           `json:"is_autonomous"`
	MaxRounds      int32          `json:"max_rounds"`
	MaxTokens      int32          `json:"max_tokens"`
	Icon           string         `json:"icon"`
	Model          string         `json:"model"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.CompanyID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.Tools,
		arg.CostMultiplier,
		arg.IsAutonomous,
		arg.MaxRounds,
		arg.MaxTokens,
		arg.Icon,
		arg.Model,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.Tools,
		&i.CostMultiplier,
		&i.IsActive,
		&i.IsAutonomous,
		&i.MaxRounds,
		&i.MaxTokens,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Model,
		&i.CompanyID,
	)
	return i, err
}

const createAgentTask = `-- name: CreateAgentTask :one
INSERT INTO agent_tasks (company_id, user_id, agent_slug, status, input)
VALUES ($1, $2, $3, 'pending', $4)
RETURNING id, company_id, user_id, agent_slug, status, input, output, tokens_consumed, error_message, started_at, completed_at, created_at
`

type CreateAgentTaskParams struct {
	CompanyID int64  `json:"company_id"`
	UserID    int64  `json:"user_id"`
	AgentSlug string `json:"agent_slug"`
	Input     string `json:"input"`
}

func (q *Queries) CreateAgentTask(ctx context.Context, arg CreateAgentTaskParams) (AgentTask, error) {
	row := q.db.QueryRow(ctx, createAgentTask,
		arg.CompanyID,
		arg.UserID,
		arg.AgentSlug,
		arg.Input,
	)
	var i AgentTask
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AgentSlug,
		&i.Status,
		&i.Input,
		&i.Output,
		&i.TokensConsumed,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateAgent = `-- name: DeactivateAgent :exec
UPDATE agents SET is_active = false, updated_at = now()
WHERE slug = $1 AND company_id = $2
`

type DeactivateAgentParams struct {
	Slug      string `json:"slug"`
	CompanyID *int64 `json:"company_id"`
}

func (q *Queries) DeactivateAgent(ctx context.Context, arg DeactivateAgentParams) error {
	_, err := q.db.Exec(ctx, deactivateAgent, arg.Slug, arg.CompanyID)
	return err
}

const getAgentBySlug = `-- name: GetAgentBySlug :one
SELECT id, slug, name, description, system_prompt, tools, cost_multiplier, is_active, is_autonomous, max_rounds, max_tokens, icon, created_at, updated_at, model, company_id FROM agents WHERE slug = $1 AND is_active = true
`

func (q *Queries) GetAgentBySlug(ctx context.Context, slug string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgentBySlug, slug)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.Tools,
		&i.CostMultiplier,
		&i.IsActive,
		&i.IsAutonomous,
		&i.MaxRounds,
		&i.MaxTokens,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Model,
		&i.CompanyID,
	)
	return i, err
}

const getPendingAgentTasks = `-- name: GetPendingAgentTasks :many
SELECT id, company_id, user_id, agent_slug, status, input, output, tokens_consumed, error_message, started_at, completed_at, created_at FROM agent_tasks
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) GetPendingAgentTasks(ctx context.Context, limit int32) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, getPendingAgentTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AgentSlug,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.TokensConsumed,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentTasks = `-- name: ListAgentTasks :many
SELECT id, company_id, user_id, agent_slug, status, input, output, tokens_consumed, error_message, started_at, completed_at, created_at FROM agent_tasks
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAgentTasksParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListAgentTasks(ctx context.Context, arg ListAgentTasksParams) ([]AgentTask, error) {
	rows, err := q.db.Query(ctx, listAgentTasks, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentTask{}
	for rows.Next() {
		var i AgentTask
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AgentSlug,
			&i.Status,
			&i.Input,
			&i.Output,
			&i.TokensConsumed,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgents = `-- name: ListAgents :many
SELECT id, slug, name, description, system_prompt, tools, cost_multiplier, is_active, is_autonomous, max_rounds, max_tokens, icon, created_at, updated_at, model, company_id FROM agents WHERE is_active = true ORDER BY slug
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.SystemPrompt,
			&i.Tools,
			&i.CostMultiplier,
			&i.IsActive,
			&i.IsAutonomous,
			&i.MaxRounds,
			&i.MaxTokens,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Model,
			&i.CompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByCompany = `-- name: ListAgentsByCompany :many
SELECT id, slug, name, description, system_prompt, tools, cost_multiplier, is_active, is_autonomous, max_rounds, max_tokens, icon, created_at, updated_at, model, company_id FROM agents
WHERE is_active = true
  AND (company_id IS NULL OR company_id = $1)
ORDER BY company_id NULLS FIRST, slug
`

func (q *Queries) ListAgentsByCompany(ctx context.Context, companyID *int64) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Agent{}
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.SystemPrompt,
			&i.Tools,
			&i.CostMultiplier,
			&i.IsActive,
			&i.IsAutonomous,
			&i.MaxRounds,
			&i.MaxTokens,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Model,
			&i.CompanyID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET
  name = COALESCE(NULLIF($1::varchar, ''), name),
  description = COALESCE(NULLIF($2::text, ''), description),
  system_prompt = COALESCE(NULLIF($3::text, ''), system_prompt),
  tools = $4,
  cost_multiplier = $5,
  is_autonomous = $6,
  max_rounds = $7,
  max_tokens = $8,
  icon = COALESCE(NULLIF($9::varchar, ''), icon),
  model = $10,
  updated_at = now()
WHERE slug = $11 AND is_active = true
RETURNING id, slug, name, description, system_prompt, tools, cost_multiplier, is_active, is_autonomous, max_rounds, max_tokens, icon, created_at, updated_at, model, company_id
`

type UpdateAgentParams struct {
	Name           string         `json:"name"`
	Description    string         `json:"description"`
	SystemPrompt   string         `json:"system_prompt"`
	Tools          []string       `json:"tools"`
	CostMultiplier pgtype.Numeric `json:"cost_multiplier"`
	IsAutonomous   bool           `json:"is_autonomous"`
	MaxRounds      int32          `json:"max_rounds"`
	MaxTokens      int32          `json:"max_tokens"`
	Icon           string         `json:"icon"`
	Model          string         `json:"model"`
	Slug           string         `json:"slug"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.Tools,
		arg.CostMultiplier,
		arg.IsAutonomous,
		arg.MaxRounds,
		arg.MaxTokens,
		arg.Icon,
		arg.Model,
		arg.Slug,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.Tools,
		&i.CostMultiplier,
		&i.IsActive,
		&i.IsAutonomous,
		&i.MaxRounds,
		&i.MaxTokens,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Model,
		&i.CompanyID,
	)
	return i, err
}

const updateAgentTask = `-- name: UpdateAgentTask :exec
UPDATE agent_tasks
SET status = $2,
    output = $3,
    tokens_consumed = $4,
    error_message = $5,
    started_at = CASE WHEN $2 = 'running' AND started_at IS NULL THEN now() ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed') THEN now() ELSE completed_at END
WHERE id = $1
`

type UpdateAgentTaskParams struct {
	ID             int64   `json:"id"`
	Status         string  `json:"status"`
	Output         *string `json:"output"`
	TokensConsumed int64   `json:"tokens_consumed"`
	ErrorMessage   *string `json:"error_message"`
}

func (q *Queries) UpdateAgentTask(ctx context.Context, arg UpdateAgentTaskParams) error {
	_, err := q.db.Exec(ctx, updateAgentTask,
		arg.ID,
		arg.Status,
		arg.Output,
		arg.TokensConsumed,
		arg.ErrorMessage,
	)
	return err
}
