// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attendance.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignSchedule = `-- name: AssignSchedule :one
INSERT INTO work_schedules (company_id, employee_id, shift_id, work_date, is_rest_day)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (company_id, employee_id, work_date) DO UPDATE SET
    shift_id = EXCLUDED.shift_id,
    is_rest_day = EXCLUDED.is_rest_day
RETURNING id, company_id, employee_id, shift_id, work_date, is_rest_day, created_at
`

type AssignScheduleParams struct {
	CompanyID  int64     `json:"company_id"`
	EmployeeID int64     `json:"employee_id"`
	ShiftID    int64     `json:"shift_id"`
	WorkDate   time.Time `json:"work_date"`
	IsRestDay  bool      `json:"is_rest_day"`
}

func (q *Queries) AssignSchedule(ctx context.Context, arg AssignScheduleParams) (WorkSchedule, error) {
	row := q.db.QueryRow(ctx, assignSchedule,
		arg.CompanyID,
		arg.EmployeeID,
		arg.ShiftID,
		arg.WorkDate,
		arg.IsRestDay,
	)
	var i WorkSchedule
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ShiftID,
		&i.WorkDate,
		&i.IsRestDay,
		&i.CreatedAt,
	)
	return i, err
}

const autoCloseAttendance = `-- name: AutoCloseAttendance :exec
UPDATE attendance_logs SET
    clock_out_at = clock_in_at + INTERVAL '8 hours',
    clock_out_source = 'system_auto_close',
    clock_out_note = 'Auto-closed by system (no clock-out recorded)',
    work_hours = 8,
    overtime_hours = 0,
    status = 'present'
WHERE id = $1
`

func (q *Queries) AutoCloseAttendance(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, autoCloseAttendance, id)
	return err
}

const bulkAssignSchedule = `-- name: BulkAssignSchedule :exec
INSERT INTO work_schedules (company_id, employee_id, shift_id, work_date, is_rest_day)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (company_id, employee_id, work_date) DO UPDATE SET
    shift_id = EXCLUDED.shift_id,
    is_rest_day = EXCLUDED.is_rest_day
`

type BulkAssignScheduleParams struct {
	CompanyID  int64     `json:"company_id"`
	EmployeeID int64     `json:"employee_id"`
	ShiftID    int64     `json:"shift_id"`
	WorkDate   time.Time `json:"work_date"`
	IsRestDay  bool      `json:"is_rest_day"`
}

func (q *Queries) BulkAssignSchedule(ctx context.Context, arg BulkAssignScheduleParams) error {
	_, err := q.db.Exec(ctx, bulkAssignSchedule,
		arg.CompanyID,
		arg.EmployeeID,
		arg.ShiftID,
		arg.WorkDate,
		arg.IsRestDay,
	)
	return err
}

const clockIn = `-- name: ClockIn :one
INSERT INTO attendance_logs (
    company_id, employee_id, clock_in_at, clock_in_source,
    clock_in_lat, clock_in_lng, clock_in_note
) VALUES ($1, $2, NOW(), $3, $4, $5, $6)
RETURNING id, company_id, employee_id, clock_in_at, clock_out_at, clock_in_source, clock_out_source, clock_in_lat, clock_in_lng, clock_out_lat, clock_out_lng, clock_in_note, clock_out_note, work_hours, overtime_hours, late_minutes, undertime_minutes, status, is_corrected, corrected_by, created_at, updated_at, clock_in_geofence_id, clock_in_geofence_status, clock_out_geofence_id, clock_out_geofence_status
`

type ClockInParams struct {
	CompanyID     int64          `json:"company_id"`
	EmployeeID    int64          `json:"employee_id"`
	ClockInSource string         `json:"clock_in_source"`
	ClockInLat    pgtype.Numeric `json:"clock_in_lat"`
	ClockInLng    pgtype.Numeric `json:"clock_in_lng"`
	ClockInNote   *string        `json:"clock_in_note"`
}

func (q *Queries) ClockIn(ctx context.Context, arg ClockInParams) (AttendanceLog, error) {
	row := q.db.QueryRow(ctx, clockIn,
		arg.CompanyID,
		arg.EmployeeID,
		arg.ClockInSource,
		arg.ClockInLat,
		arg.ClockInLng,
		arg.ClockInNote,
	)
	var i AttendanceLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ClockInAt,
		&i.ClockOutAt,
		&i.ClockInSource,
		&i.ClockOutSource,
		&i.ClockInLat,
		&i.ClockInLng,
		&i.ClockOutLat,
		&i.ClockOutLng,
		&i.ClockInNote,
		&i.ClockOutNote,
		&i.WorkHours,
		&i.OvertimeHours,
		&i.LateMinutes,
		&i.UndertimeMinutes,
		&i.Status,
		&i.IsCorrected,
		&i.CorrectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClockInGeofenceID,
		&i.ClockInGeofenceStatus,
		&i.ClockOutGeofenceID,
		&i.ClockOutGeofenceStatus,
	)
	return i, err
}

const clockOut = `-- name: ClockOut :one
UPDATE attendance_logs SET
    clock_out_at = NOW(),
    clock_out_source = $3,
    clock_out_lat = $4,
    clock_out_lng = $5,
    clock_out_note = $6,
    updated_at = NOW()
WHERE id = $1 AND employee_id = $2 AND clock_out_at IS NULL
RETURNING id, company_id, employee_id, clock_in_at, clock_out_at, clock_in_source, clock_out_source, clock_in_lat, clock_in_lng, clock_out_lat, clock_out_lng, clock_in_note, clock_out_note, work_hours, overtime_hours, late_minutes, undertime_minutes, status, is_corrected, corrected_by, created_at, updated_at, clock_in_geofence_id, clock_in_geofence_status, clock_out_geofence_id, clock_out_geofence_status
`

type ClockOutParams struct {
	ID             int64          `json:"id"`
	EmployeeID     int64          `json:"employee_id"`
	ClockOutSource *string        `json:"clock_out_source"`
	ClockOutLat    pgtype.Numeric `json:"clock_out_lat"`
	ClockOutLng    pgtype.Numeric `json:"clock_out_lng"`
	ClockOutNote   *string        `json:"clock_out_note"`
}

func (q *Queries) ClockOut(ctx context.Context, arg ClockOutParams) (AttendanceLog, error) {
	row := q.db.QueryRow(ctx, clockOut,
		arg.ID,
		arg.EmployeeID,
		arg.ClockOutSource,
		arg.ClockOutLat,
		arg.ClockOutLng,
		arg.ClockOutNote,
	)
	var i AttendanceLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ClockInAt,
		&i.ClockOutAt,
		&i.ClockInSource,
		&i.ClockOutSource,
		&i.ClockInLat,
		&i.ClockInLng,
		&i.ClockOutLat,
		&i.ClockOutLng,
		&i.ClockInNote,
		&i.ClockOutNote,
		&i.WorkHours,
		&i.OvertimeHours,
		&i.LateMinutes,
		&i.UndertimeMinutes,
		&i.Status,
		&i.IsCorrected,
		&i.CorrectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClockInGeofenceID,
		&i.ClockInGeofenceStatus,
		&i.ClockOutGeofenceID,
		&i.ClockOutGeofenceStatus,
	)
	return i, err
}

const countAttendanceLogs = `-- name: CountAttendanceLogs :one
SELECT COUNT(*) FROM attendance_logs
WHERE company_id = $1
  AND ($2::bigint IS NULL OR employee_id = $2)
  AND clock_in_at >= $3
  AND clock_in_at < $4
`

type CountAttendanceLogsParams struct {
	CompanyID   int64              `json:"company_id"`
	Column2     int64              `json:"column_2"`
	ClockInAt   pgtype.Timestamptz `json:"clock_in_at"`
	ClockInAt_2 pgtype.Timestamptz `json:"clock_in_at_2"`
}

func (q *Queries) CountAttendanceLogs(ctx context.Context, arg CountAttendanceLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttendanceLogs,
		arg.CompanyID,
		arg.Column2,
		arg.ClockInAt,
		arg.ClockInAt_2,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShift = `-- name: CreateShift :one
INSERT INTO shifts (company_id, name, start_time, end_time, break_minutes, grace_minutes, is_overnight)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, name, start_time, end_time, break_minutes, grace_minutes, is_overnight, is_active, created_at, updated_at
`

type CreateShiftParams struct {
	CompanyID    int64       `json:"company_id"`
	Name         string      `json:"name"`
	StartTime    pgtype.Time `json:"start_time"`
	EndTime      pgtype.Time `json:"end_time"`
	BreakMinutes int32       `json:"break_minutes"`
	GraceMinutes int32       `json:"grace_minutes"`
	IsOvernight  bool        `json:"is_overnight"`
}

func (q *Queries) CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, createShift,
		arg.CompanyID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMinutes,
		arg.GraceMinutes,
		arg.IsOvernight,
	)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.GraceMinutes,
		&i.IsOvernight,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :exec
DELETE FROM work_schedules WHERE id = $1 AND company_id = $2
`

type DeleteScheduleParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) DeleteSchedule(ctx context.Context, arg DeleteScheduleParams) error {
	_, err := q.db.Exec(ctx, deleteSchedule, arg.ID, arg.CompanyID)
	return err
}

const exportAttendanceLogs = `-- name: ExportAttendanceLogs :many
SELECT al.clock_in_at, al.clock_out_at, al.work_hours, al.overtime_hours,
       al.late_minutes, al.undertime_minutes, al.status,
       e.employee_no, e.first_name, e.last_name
FROM attendance_logs al
JOIN employees e ON e.id = al.employee_id
WHERE al.company_id = $1
  AND al.clock_in_at >= $2
  AND al.clock_in_at < $3
ORDER BY al.clock_in_at DESC
`

type ExportAttendanceLogsParams struct {
	CompanyID   int64              `json:"company_id"`
	ClockInAt   pgtype.Timestamptz `json:"clock_in_at"`
	ClockInAt_2 pgtype.Timestamptz `json:"clock_in_at_2"`
}

type ExportAttendanceLogsRow struct {
	ClockInAt        pgtype.Timestamptz `json:"clock_in_at"`
	ClockOutAt       pgtype.Timestamptz `json:"clock_out_at"`
	WorkHours        pgtype.Numeric     `json:"work_hours"`
	OvertimeHours    pgtype.Numeric     `json:"overtime_hours"`
	LateMinutes      *int32             `json:"late_minutes"`
	UndertimeMinutes *int32             `json:"undertime_minutes"`
	Status           string             `json:"status"`
	EmployeeNo       string             `json:"employee_no"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
}

func (q *Queries) ExportAttendanceLogs(ctx context.Context, arg ExportAttendanceLogsParams) ([]ExportAttendanceLogsRow, error) {
	rows, err := q.db.Query(ctx, exportAttendanceLogs, arg.CompanyID, arg.ClockInAt, arg.ClockInAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportAttendanceLogsRow{}
	for rows.Next() {
		var i ExportAttendanceLogsRow
		if err := rows.Scan(
			&i.ClockInAt,
			&i.ClockOutAt,
			&i.WorkHours,
			&i.OvertimeHours,
			&i.LateMinutes,
			&i.UndertimeMinutes,
			&i.Status,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendanceByID = `-- name: GetAttendanceByID :one
SELECT id, company_id, employee_id, clock_in_at, clock_out_at, clock_in_source, clock_out_source, clock_in_lat, clock_in_lng, clock_out_lat, clock_out_lng, clock_in_note, clock_out_note, work_hours, overtime_hours, late_minutes, undertime_minutes, status, is_corrected, corrected_by, created_at, updated_at, clock_in_geofence_id, clock_in_geofence_status, clock_out_geofence_id, clock_out_geofence_status FROM attendance_logs
WHERE id = $1 AND company_id = $2
`

type GetAttendanceByIDParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetAttendanceByID(ctx context.Context, arg GetAttendanceByIDParams) (AttendanceLog, error) {
	row := q.db.QueryRow(ctx, getAttendanceByID, arg.ID, arg.CompanyID)
	var i AttendanceLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ClockInAt,
		&i.ClockOutAt,
		&i.ClockInSource,
		&i.ClockOutSource,
		&i.ClockInLat,
		&i.ClockInLng,
		&i.ClockOutLat,
		&i.ClockOutLng,
		&i.ClockInNote,
		&i.ClockOutNote,
		&i.WorkHours,
		&i.OvertimeHours,
		&i.LateMinutes,
		&i.UndertimeMinutes,
		&i.Status,
		&i.IsCorrected,
		&i.CorrectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClockInGeofenceID,
		&i.ClockInGeofenceStatus,
		&i.ClockOutGeofenceID,
		&i.ClockOutGeofenceStatus,
	)
	return i, err
}

const getAttendanceRecordsForPeriod = `-- name: GetAttendanceRecordsForPeriod :many
SELECT id, employee_id, clock_in_at, clock_out_at
FROM attendance_logs
WHERE company_id = $1
  AND clock_in_at >= $2
  AND clock_in_at < $3
  AND clock_out_at IS NOT NULL
  AND status IN ('present', 'late', 'undertime')
ORDER BY employee_id, clock_in_at
`

type GetAttendanceRecordsForPeriodParams struct {
	CompanyID   int64              `json:"company_id"`
	ClockInAt   pgtype.Timestamptz `json:"clock_in_at"`
	ClockInAt_2 pgtype.Timestamptz `json:"clock_in_at_2"`
}

type GetAttendanceRecordsForPeriodRow struct {
	ID         int64              `json:"id"`
	EmployeeID int64              `json:"employee_id"`
	ClockInAt  pgtype.Timestamptz `json:"clock_in_at"`
	ClockOutAt pgtype.Timestamptz `json:"clock_out_at"`
}

func (q *Queries) GetAttendanceRecordsForPeriod(ctx context.Context, arg GetAttendanceRecordsForPeriodParams) ([]GetAttendanceRecordsForPeriodRow, error) {
	rows, err := q.db.Query(ctx, getAttendanceRecordsForPeriod, arg.CompanyID, arg.ClockInAt, arg.ClockInAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttendanceRecordsForPeriodRow{}
	for rows.Next() {
		var i GetAttendanceRecordsForPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ClockInAt,
			&i.ClockOutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendanceReport = `-- name: GetAttendanceReport :many
SELECT
    e.id as employee_id, e.employee_no, e.first_name, e.last_name,
    COALESCE(d.name, '') as department_name,
    COUNT(al.id) as days_worked,
    COALESCE(SUM(al.work_hours), 0) as total_work_hours,
    COALESCE(SUM(al.overtime_hours), 0) as total_overtime_hours,
    COALESCE(SUM(al.late_minutes), 0) as total_late_minutes,
    COALESCE(SUM(al.undertime_minutes), 0) as total_undertime_minutes,
    COUNT(CASE WHEN al.status = 'late' THEN 1 END) as late_count,
    COUNT(CASE WHEN al.status = 'undertime' THEN 1 END) as undertime_count
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN attendance_logs al ON al.employee_id = e.id
    AND al.clock_in_at >= $2
    AND al.clock_in_at < $3
    AND al.status IN ('present', 'late', 'undertime')
WHERE e.company_id = $1 AND e.status = 'active'
GROUP BY e.id, e.employee_no, e.first_name, e.last_name, d.name
ORDER BY e.last_name, e.first_name
`

type GetAttendanceReportParams struct {
	CompanyID   int64              `json:"company_id"`
	ClockInAt   pgtype.Timestamptz `json:"clock_in_at"`
	ClockInAt_2 pgtype.Timestamptz `json:"clock_in_at_2"`
}

type GetAttendanceReportRow struct {
	EmployeeID            int64       `json:"employee_id"`
	EmployeeNo            string      `json:"employee_no"`
	FirstName             string      `json:"first_name"`
	LastName              string      `json:"last_name"`
	DepartmentName        string      `json:"department_name"`
	DaysWorked            int64       `json:"days_worked"`
	TotalWorkHours        interface{} `json:"total_work_hours"`
	TotalOvertimeHours    interface{} `json:"total_overtime_hours"`
	TotalLateMinutes      interface{} `json:"total_late_minutes"`
	TotalUndertimeMinutes interface{} `json:"total_undertime_minutes"`
	LateCount             int64       `json:"late_count"`
	UndertimeCount        int64       `json:"undertime_count"`
}

func (q *Queries) GetAttendanceReport(ctx context.Context, arg GetAttendanceReportParams) ([]GetAttendanceReportRow, error) {
	rows, err := q.db.Query(ctx, getAttendanceReport, arg.CompanyID, arg.ClockInAt, arg.ClockInAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttendanceReportRow{}
	for rows.Next() {
		var i GetAttendanceReportRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.DepartmentName,
			&i.DaysWorked,
			&i.TotalWorkHours,
			&i.TotalOvertimeHours,
			&i.TotalLateMinutes,
			&i.TotalUndertimeMinutes,
			&i.LateCount,
			&i.UndertimeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttendanceSummaryForPeriod = `-- name: GetAttendanceSummaryForPeriod :many
SELECT
    employee_id,
    COUNT(*) as days_worked,
    COALESCE(SUM(work_hours), 0) as total_work_hours,
    COALESCE(SUM(overtime_hours), 0) as total_overtime_hours,
    COALESCE(SUM(late_minutes), 0) as total_late_minutes,
    COALESCE(SUM(undertime_minutes), 0) as total_undertime_minutes
FROM attendance_logs
WHERE company_id = $1
  AND clock_in_at >= $2
  AND clock_in_at < $3
  AND status IN ('present', 'late', 'undertime')
GROUP BY employee_id
`

type GetAttendanceSummaryForPeriodParams struct {
	CompanyID   int64              `json:"company_id"`
	ClockInAt   pgtype.Timestamptz `json:"clock_in_at"`
	ClockInAt_2 pgtype.Timestamptz `json:"clock_in_at_2"`
}

type GetAttendanceSummaryForPeriodRow struct {
	EmployeeID            int64       `json:"employee_id"`
	DaysWorked            int64       `json:"days_worked"`
	TotalWorkHours        interface{} `json:"total_work_hours"`
	TotalOvertimeHours    interface{} `json:"total_overtime_hours"`
	TotalLateMinutes      interface{} `json:"total_late_minutes"`
	TotalUndertimeMinutes interface{} `json:"total_undertime_minutes"`
}

func (q *Queries) GetAttendanceSummaryForPeriod(ctx context.Context, arg GetAttendanceSummaryForPeriodParams) ([]GetAttendanceSummaryForPeriodRow, error) {
	rows, err := q.db.Query(ctx, getAttendanceSummaryForPeriod, arg.CompanyID, arg.ClockInAt, arg.ClockInAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttendanceSummaryForPeriodRow{}
	for rows.Next() {
		var i GetAttendanceSummaryForPeriodRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.DaysWorked,
			&i.TotalWorkHours,
			&i.TotalOvertimeHours,
			&i.TotalLateMinutes,
			&i.TotalUndertimeMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDTR = `-- name: GetDTR :many
SELECT al.id, al.employee_id, al.clock_in_at, al.clock_out_at,
       al.work_hours, al.overtime_hours, al.late_minutes, al.undertime_minutes,
       al.status, al.clock_in_source, al.clock_out_source,
       e.employee_no, e.first_name, e.last_name,
       COALESCE(d.name, '') as department_name,
       COALESCE(p.title, '') as position_name
FROM attendance_logs al
JOIN employees e ON e.id = al.employee_id
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
WHERE al.company_id = $1
  AND al.employee_id = $2
  AND al.clock_in_at >= $3
  AND al.clock_in_at < $4
ORDER BY al.clock_in_at
`

type GetDTRParams struct {
	CompanyID   int64              `json:"company_id"`
	EmployeeID  int64              `json:"employee_id"`
	ClockInAt   pgtype.Timestamptz `json:"clock_in_at"`
	ClockInAt_2 pgtype.Timestamptz `json:"clock_in_at_2"`
}

type GetDTRRow struct {
	ID               int64              `json:"id"`
	EmployeeID       int64              `json:"employee_id"`
	ClockInAt        pgtype.Timestamptz `json:"clock_in_at"`
	ClockOutAt       pgtype.Timestamptz `json:"clock_out_at"`
	WorkHours        pgtype.Numeric     `json:"work_hours"`
	OvertimeHours    pgtype.Numeric     `json:"overtime_hours"`
	LateMinutes      *int32             `json:"late_minutes"`
	UndertimeMinutes *int32             `json:"undertime_minutes"`
	Status           string             `json:"status"`
	ClockInSource    string             `json:"clock_in_source"`
	ClockOutSource   *string            `json:"clock_out_source"`
	EmployeeNo       string             `json:"employee_no"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	DepartmentName   string             `json:"department_name"`
	PositionName     string             `json:"position_name"`
}

func (q *Queries) GetDTR(ctx context.Context, arg GetDTRParams) ([]GetDTRRow, error) {
	rows, err := q.db.Query(ctx, getDTR,
		arg.CompanyID,
		arg.EmployeeID,
		arg.ClockInAt,
		arg.ClockInAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDTRRow{}
	for rows.Next() {
		var i GetDTRRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ClockInAt,
			&i.ClockOutAt,
			&i.WorkHours,
			&i.OvertimeHours,
			&i.LateMinutes,
			&i.UndertimeMinutes,
			&i.Status,
			&i.ClockInSource,
			&i.ClockOutSource,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.DepartmentName,
			&i.PositionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDTRAllEmployees = `-- name: GetDTRAllEmployees :many
SELECT al.id, al.employee_id, al.clock_in_at, al.clock_out_at,
       al.work_hours, al.overtime_hours, al.late_minutes, al.undertime_minutes,
       al.status, al.clock_in_source, al.clock_out_source,
       e.employee_no, e.first_name, e.last_name,
       COALESCE(d.name, '') as department_name,
       COALESCE(p.title, '') as position_name
FROM attendance_logs al
JOIN employees e ON e.id = al.employee_id
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
WHERE al.company_id = $1
  AND al.clock_in_at >= $2
  AND al.clock_in_at < $3
ORDER BY e.last_name, e.first_name, al.clock_in_at
`

type GetDTRAllEmployeesParams struct {
	CompanyID   int64              `json:"company_id"`
	ClockInAt   pgtype.Timestamptz `json:"clock_in_at"`
	ClockInAt_2 pgtype.Timestamptz `json:"clock_in_at_2"`
}

type GetDTRAllEmployeesRow struct {
	ID               int64              `json:"id"`
	EmployeeID       int64              `json:"employee_id"`
	ClockInAt        pgtype.Timestamptz `json:"clock_in_at"`
	ClockOutAt       pgtype.Timestamptz `json:"clock_out_at"`
	WorkHours        pgtype.Numeric     `json:"work_hours"`
	OvertimeHours    pgtype.Numeric     `json:"overtime_hours"`
	LateMinutes      *int32             `json:"late_minutes"`
	UndertimeMinutes *int32             `json:"undertime_minutes"`
	Status           string             `json:"status"`
	ClockInSource    string             `json:"clock_in_source"`
	ClockOutSource   *string            `json:"clock_out_source"`
	EmployeeNo       string             `json:"employee_no"`
	FirstName        string             `json:"first_name"`
	LastName         string             `json:"last_name"`
	DepartmentName   string             `json:"department_name"`
	PositionName     string             `json:"position_name"`
}

func (q *Queries) GetDTRAllEmployees(ctx context.Context, arg GetDTRAllEmployeesParams) ([]GetDTRAllEmployeesRow, error) {
	rows, err := q.db.Query(ctx, getDTRAllEmployees, arg.CompanyID, arg.ClockInAt, arg.ClockInAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDTRAllEmployeesRow{}
	for rows.Next() {
		var i GetDTRAllEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ClockInAt,
			&i.ClockOutAt,
			&i.WorkHours,
			&i.OvertimeHours,
			&i.LateMinutes,
			&i.UndertimeMinutes,
			&i.Status,
			&i.ClockInSource,
			&i.ClockOutSource,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.DepartmentName,
			&i.PositionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHolidayAttendanceForPeriod = `-- name: GetHolidayAttendanceForPeriod :many
SELECT
    al.employee_id,
    h.holiday_type,
    COUNT(*) as days_worked
FROM attendance_logs al
JOIN holidays h ON h.company_id = al.company_id
    AND h.holiday_date = (al.clock_in_at AT TIME ZONE 'Asia/Manila')::date
WHERE al.company_id = $1
  AND al.clock_in_at >= $2
  AND al.clock_in_at < $3
  AND al.status IN ('present', 'late', 'undertime')
GROUP BY al.employee_id, h.holiday_type
`

type GetHolidayAttendanceForPeriodParams struct {
	CompanyID   int64              `json:"company_id"`
	ClockInAt   pgtype.Timestamptz `json:"clock_in_at"`
	ClockInAt_2 pgtype.Timestamptz `json:"clock_in_at_2"`
}

type GetHolidayAttendanceForPeriodRow struct {
	EmployeeID  int64  `json:"employee_id"`
	HolidayType string `json:"holiday_type"`
	DaysWorked  int64  `json:"days_worked"`
}

func (q *Queries) GetHolidayAttendanceForPeriod(ctx context.Context, arg GetHolidayAttendanceForPeriodParams) ([]GetHolidayAttendanceForPeriodRow, error) {
	rows, err := q.db.Query(ctx, getHolidayAttendanceForPeriod, arg.CompanyID, arg.ClockInAt, arg.ClockInAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHolidayAttendanceForPeriodRow{}
	for rows.Next() {
		var i GetHolidayAttendanceForPeriodRow
		if err := rows.Scan(&i.EmployeeID, &i.HolidayType, &i.DaysWorked); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenAttendance = `-- name: GetOpenAttendance :one
SELECT id, company_id, employee_id, clock_in_at, clock_out_at, clock_in_source, clock_out_source, clock_in_lat, clock_in_lng, clock_out_lat, clock_out_lng, clock_in_note, clock_out_note, work_hours, overtime_hours, late_minutes, undertime_minutes, status, is_corrected, corrected_by, created_at, updated_at, clock_in_geofence_id, clock_in_geofence_status, clock_out_geofence_id, clock_out_geofence_status FROM attendance_logs
WHERE employee_id = $1 AND company_id = $2 AND clock_out_at IS NULL
ORDER BY clock_in_at DESC LIMIT 1
`

type GetOpenAttendanceParams struct {
	EmployeeID int64 `json:"employee_id"`
	CompanyID  int64 `json:"company_id"`
}

func (q *Queries) GetOpenAttendance(ctx context.Context, arg GetOpenAttendanceParams) (AttendanceLog, error) {
	row := q.db.QueryRow(ctx, getOpenAttendance, arg.EmployeeID, arg.CompanyID)
	var i AttendanceLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ClockInAt,
		&i.ClockOutAt,
		&i.ClockInSource,
		&i.ClockOutSource,
		&i.ClockInLat,
		&i.ClockInLng,
		&i.ClockOutLat,
		&i.ClockOutLng,
		&i.ClockInNote,
		&i.ClockOutNote,
		&i.WorkHours,
		&i.OvertimeHours,
		&i.LateMinutes,
		&i.UndertimeMinutes,
		&i.Status,
		&i.IsCorrected,
		&i.CorrectedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClockInGeofenceID,
		&i.ClockInGeofenceStatus,
		&i.ClockOutGeofenceID,
		&i.ClockOutGeofenceStatus,
	)
	return i, err
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, company_id, employee_id, shift_id, work_date, is_rest_day, created_at FROM work_schedules
WHERE employee_id = $1 AND company_id = $2 AND work_date = $3
`

type GetScheduleParams struct {
	EmployeeID int64     `json:"employee_id"`
	CompanyID  int64     `json:"company_id"`
	WorkDate   time.Time `json:"work_date"`
}

func (q *Queries) GetSchedule(ctx context.Context, arg GetScheduleParams) (WorkSchedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, arg.EmployeeID, arg.CompanyID, arg.WorkDate)
	var i WorkSchedule
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ShiftID,
		&i.WorkDate,
		&i.IsRestDay,
		&i.CreatedAt,
	)
	return i, err
}

const getTodayAttendanceSummary = `-- name: GetTodayAttendanceSummary :many
SELECT
    status,
    COUNT(*) as count
FROM attendance_logs
WHERE company_id = $1 AND clock_in_at::date = CURRENT_DATE
GROUP BY status
`

type GetTodayAttendanceSummaryRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetTodayAttendanceSummary(ctx context.Context, companyID int64) ([]GetTodayAttendanceSummaryRow, error) {
	rows, err := q.db.Query(ctx, getTodayAttendanceSummary, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTodayAttendanceSummaryRow{}
	for rows.Next() {
		var i GetTodayAttendanceSummaryRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSchedules = `-- name: ListAllSchedules :many
SELECT ws.id, ws.company_id, ws.employee_id, ws.shift_id, ws.work_date, ws.is_rest_day,
       s.name as shift_name, s.start_time, s.end_time,
       e.first_name, e.last_name, e.employee_no
FROM work_schedules ws
JOIN shifts s ON s.id = ws.shift_id
JOIN employees e ON e.id = ws.employee_id
WHERE ws.company_id = $1
  AND ws.work_date >= $2 AND ws.work_date <= $3
ORDER BY ws.work_date, e.last_name
`

type ListAllSchedulesParams struct {
	CompanyID  int64     `json:"company_id"`
	WorkDate   time.Time `json:"work_date"`
	WorkDate_2 time.Time `json:"work_date_2"`
}

type ListAllSchedulesRow struct {
	ID         int64       `json:"id"`
	CompanyID  int64       `json:"company_id"`
	EmployeeID int64       `json:"employee_id"`
	ShiftID    int64       `json:"shift_id"`
	WorkDate   time.Time   `json:"work_date"`
	IsRestDay  bool        `json:"is_rest_day"`
	ShiftName  string      `json:"shift_name"`
	StartTime  pgtype.Time `json:"start_time"`
	EndTime    pgtype.Time `json:"end_time"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	EmployeeNo string      `json:"employee_no"`
}

func (q *Queries) ListAllSchedules(ctx context.Context, arg ListAllSchedulesParams) ([]ListAllSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listAllSchedules, arg.CompanyID, arg.WorkDate, arg.WorkDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllSchedulesRow{}
	for rows.Next() {
		var i ListAllSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.ShiftID,
			&i.WorkDate,
			&i.IsRestDay,
			&i.ShiftName,
			&i.StartTime,
			&i.EndTime,
			&i.FirstName,
			&i.LastName,
			&i.EmployeeNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttendanceLogs = `-- name: ListAttendanceLogs :many
SELECT id, company_id, employee_id, clock_in_at, clock_out_at, clock_in_source, clock_out_source, clock_in_lat, clock_in_lng, clock_out_lat, clock_out_lng, clock_in_note, clock_out_note, work_hours, overtime_hours, late_minutes, undertime_minutes, status, is_corrected, corrected_by, created_at, updated_at, clock_in_geofence_id, clock_in_geofence_status, clock_out_geofence_id, clock_out_geofence_status FROM attendance_logs
WHERE company_id = $1
  AND ($2::bigint IS NULL OR employee_id = $2)
  AND clock_in_at >= $3
  AND clock_in_at < $4
ORDER BY clock_in_at DESC
LIMIT $5 OFFSET $6
`

type ListAttendanceLogsParams struct {
	CompanyID   int64              `json:"company_id"`
	Column2     int64              `json:"column_2"`
	ClockInAt   pgtype.Timestamptz `json:"clock_in_at"`
	ClockInAt_2 pgtype.Timestamptz `json:"clock_in_at_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) ListAttendanceLogs(ctx context.Context, arg ListAttendanceLogsParams) ([]AttendanceLog, error) {
	rows, err := q.db.Query(ctx, listAttendanceLogs,
		arg.CompanyID,
		arg.Column2,
		arg.ClockInAt,
		arg.ClockInAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceLog{}
	for rows.Next() {
		var i AttendanceLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.ClockInAt,
			&i.ClockOutAt,
			&i.ClockInSource,
			&i.ClockOutSource,
			&i.ClockInLat,
			&i.ClockInLng,
			&i.ClockOutLat,
			&i.ClockOutLng,
			&i.ClockInNote,
			&i.ClockOutNote,
			&i.WorkHours,
			&i.OvertimeHours,
			&i.LateMinutes,
			&i.UndertimeMinutes,
			&i.Status,
			&i.IsCorrected,
			&i.CorrectedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClockInGeofenceID,
			&i.ClockInGeofenceStatus,
			&i.ClockOutGeofenceID,
			&i.ClockOutGeofenceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAttendanceRecords = `-- name: ListOpenAttendanceRecords :many
SELECT al.id, al.company_id, al.employee_id, al.clock_in_at, al.clock_out_at, al.clock_in_source, al.clock_out_source, al.clock_in_lat, al.clock_in_lng, al.clock_out_lat, al.clock_out_lng, al.clock_in_note, al.clock_out_note, al.work_hours, al.overtime_hours, al.late_minutes, al.undertime_minutes, al.status, al.is_corrected, al.corrected_by, al.created_at, al.updated_at, al.clock_in_geofence_id, al.clock_in_geofence_status, al.clock_out_geofence_id, al.clock_out_geofence_status FROM attendance_logs al
WHERE al.clock_out_at IS NULL
  AND al.clock_in_at < NOW() - INTERVAL '16 hours'
ORDER BY al.clock_in_at
`

func (q *Queries) ListOpenAttendanceRecords(ctx context.Context) ([]AttendanceLog, error) {
	rows, err := q.db.Query(ctx, listOpenAttendanceRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttendanceLog{}
	for rows.Next() {
		var i AttendanceLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.ClockInAt,
			&i.ClockOutAt,
			&i.ClockInSource,
			&i.ClockOutSource,
			&i.ClockInLat,
			&i.ClockInLng,
			&i.ClockOutLat,
			&i.ClockOutLng,
			&i.ClockInNote,
			&i.ClockOutNote,
			&i.WorkHours,
			&i.OvertimeHours,
			&i.LateMinutes,
			&i.UndertimeMinutes,
			&i.Status,
			&i.IsCorrected,
			&i.CorrectedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClockInGeofenceID,
			&i.ClockInGeofenceStatus,
			&i.ClockOutGeofenceID,
			&i.ClockOutGeofenceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedules = `-- name: ListSchedules :many
SELECT ws.id, ws.company_id, ws.employee_id, ws.shift_id, ws.work_date, ws.is_rest_day, ws.created_at, s.name as shift_name, s.start_time, s.end_time
FROM work_schedules ws
JOIN shifts s ON s.id = ws.shift_id
WHERE ws.company_id = $1 AND ws.employee_id = $2
  AND ws.work_date >= $3 AND ws.work_date <= $4
ORDER BY ws.work_date
`

type ListSchedulesParams struct {
	CompanyID  int64     `json:"company_id"`
	EmployeeID int64     `json:"employee_id"`
	WorkDate   time.Time `json:"work_date"`
	WorkDate_2 time.Time `json:"work_date_2"`
}

type ListSchedulesRow struct {
	ID         int64       `json:"id"`
	CompanyID  int64       `json:"company_id"`
	EmployeeID int64       `json:"employee_id"`
	ShiftID    int64       `json:"shift_id"`
	WorkDate   time.Time   `json:"work_date"`
	IsRestDay  bool        `json:"is_rest_day"`
	CreatedAt  time.Time   `json:"created_at"`
	ShiftName  string      `json:"shift_name"`
	StartTime  pgtype.Time `json:"start_time"`
	EndTime    pgtype.Time `json:"end_time"`
}

func (q *Queries) ListSchedules(ctx context.Context, arg ListSchedulesParams) ([]ListSchedulesRow, error) {
	rows, err := q.db.Query(ctx, listSchedules,
		arg.CompanyID,
		arg.EmployeeID,
		arg.WorkDate,
		arg.WorkDate_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchedulesRow{}
	for rows.Next() {
		var i ListSchedulesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.ShiftID,
			&i.WorkDate,
			&i.IsRestDay,
			&i.CreatedAt,
			&i.ShiftName,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShifts = `-- name: ListShifts :many
SELECT id, company_id, name, start_time, end_time, break_minutes, grace_minutes, is_overnight, is_active, created_at, updated_at FROM shifts WHERE company_id = $1 AND is_active = true ORDER BY name
`

func (q *Queries) ListShifts(ctx context.Context, companyID int64) ([]Shift, error) {
	rows, err := q.db.Query(ctx, listShifts, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shift{}
	for rows.Next() {
		var i Shift
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.StartTime,
			&i.EndTime,
			&i.BreakMinutes,
			&i.GraceMinutes,
			&i.IsOvernight,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttendanceCalc = `-- name: UpdateAttendanceCalc :exec
UPDATE attendance_logs SET
    work_hours = $2,
    overtime_hours = $3,
    late_minutes = $4,
    undertime_minutes = $5,
    status = $6,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAttendanceCalcParams struct {
	ID               int64          `json:"id"`
	WorkHours        pgtype.Numeric `json:"work_hours"`
	OvertimeHours    pgtype.Numeric `json:"overtime_hours"`
	LateMinutes      *int32         `json:"late_minutes"`
	UndertimeMinutes *int32         `json:"undertime_minutes"`
	Status           string         `json:"status"`
}

func (q *Queries) UpdateAttendanceCalc(ctx context.Context, arg UpdateAttendanceCalcParams) error {
	_, err := q.db.Exec(ctx, updateAttendanceCalc,
		arg.ID,
		arg.WorkHours,
		arg.OvertimeHours,
		arg.LateMinutes,
		arg.UndertimeMinutes,
		arg.Status,
	)
	return err
}

const updateShift = `-- name: UpdateShift :one
UPDATE shifts SET
    name = COALESCE($3, name),
    start_time = $4,
    end_time = $5,
    break_minutes = COALESCE($6, break_minutes),
    grace_minutes = COALESCE($7, grace_minutes),
    is_overnight = COALESCE($8, is_overnight),
    is_active = COALESCE($9, is_active),
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, start_time, end_time, break_minutes, grace_minutes, is_overnight, is_active, created_at, updated_at
`

type UpdateShiftParams struct {
	ID           int64       `json:"id"`
	CompanyID    int64       `json:"company_id"`
	Name         string      `json:"name"`
	StartTime    pgtype.Time `json:"start_time"`
	EndTime      pgtype.Time `json:"end_time"`
	BreakMinutes int32       `json:"break_minutes"`
	GraceMinutes int32       `json:"grace_minutes"`
	IsOvernight  bool        `json:"is_overnight"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) UpdateShift(ctx context.Context, arg UpdateShiftParams) (Shift, error) {
	row := q.db.QueryRow(ctx, updateShift,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.StartTime,
		arg.EndTime,
		arg.BreakMinutes,
		arg.GraceMinutes,
		arg.IsOvernight,
		arg.IsActive,
	)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.StartTime,
		&i.EndTime,
		&i.BreakMinutes,
		&i.GraceMinutes,
		&i.IsOvernight,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
