// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package store

import (
	"context"
	"time"
)

const countActivityLogs = `-- name: CountActivityLogs :one
SELECT COUNT(*) FROM activity_logs
WHERE company_id = $1
  AND ($2::varchar = '' OR action = $2)
  AND ($3::varchar = '' OR entity_type = $3)
`

type CountActivityLogsParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Column3   string `json:"column_3"`
}

func (q *Queries) CountActivityLogs(ctx context.Context, arg CountActivityLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActivityLogs, arg.CompanyID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_logs (company_id, user_id, action, entity_type, entity_id, description, ip_address, user_agent, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, user_id, action, entity_type, entity_id, description, ip_address, user_agent, metadata, created_at
`

type CreateActivityLogParams struct {
	CompanyID   int64   `json:"company_id"`
	UserID      int64   `json:"user_id"`
	Action      string  `json:"action"`
	EntityType  string  `json:"entity_type"`
	EntityID    *string `json:"entity_id"`
	Description string  `json:"description"`
	IpAddress   *string `json:"ip_address"`
	UserAgent   *string `json:"user_agent"`
	Metadata    []byte  `json:"metadata"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.CompanyID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Description,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Description,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listActivityLogs = `-- name: ListActivityLogs :many
SELECT al.id, al.company_id, al.user_id, al.action, al.entity_type, al.entity_id, al.description, al.ip_address, al.user_agent, al.metadata, al.created_at, u.email as user_email, u.first_name, u.last_name
FROM activity_logs al
JOIN users u ON u.id = al.user_id
WHERE al.company_id = $1
  AND ($2::varchar = '' OR al.action = $2)
  AND ($3::varchar = '' OR al.entity_type = $3)
ORDER BY al.created_at DESC
LIMIT $4 OFFSET $5
`

type ListActivityLogsParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Column3   string `json:"column_3"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListActivityLogsRow struct {
	ID          int64     `json:"id"`
	CompanyID   int64     `json:"company_id"`
	UserID      int64     `json:"user_id"`
	Action      string    `json:"action"`
	EntityType  string    `json:"entity_type"`
	EntityID    *string   `json:"entity_id"`
	Description string    `json:"description"`
	IpAddress   *string   `json:"ip_address"`
	UserAgent   *string   `json:"user_agent"`
	Metadata    []byte    `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
	UserEmail   string    `json:"user_email"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
}

func (q *Queries) ListActivityLogs(ctx context.Context, arg ListActivityLogsParams) ([]ListActivityLogsRow, error) {
	rows, err := q.db.Query(ctx, listActivityLogs,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityLogsRow{}
	for rows.Next() {
		var i ListActivityLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Description,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
			&i.UserEmail,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
