// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bonus.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkApproveBonusAllocations = `-- name: BulkApproveBonusAllocations :exec
UPDATE bonus_allocations SET
    status = 'approved',
    approved_by = $2,
    approved_at = NOW(),
    updated_at = NOW()
WHERE id = ANY($1::bigint[]) AND status = 'pending'
`

type BulkApproveBonusAllocationsParams struct {
	Column1    []int64 `json:"column_1"`
	ApprovedBy *int64  `json:"approved_by"`
}

func (q *Queries) BulkApproveBonusAllocations(ctx context.Context, arg BulkApproveBonusAllocationsParams) error {
	_, err := q.db.Exec(ctx, bulkApproveBonusAllocations, arg.Column1, arg.ApprovedBy)
	return err
}

const createBonusAllocation = `-- name: CreateBonusAllocation :one
INSERT INTO bonus_allocations (
    company_id, structure_id, employee_id, performance_review_id,
    rating, multiplier, base_amount, final_amount, manual_override, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (structure_id, employee_id) DO UPDATE SET
    performance_review_id = EXCLUDED.performance_review_id,
    rating = EXCLUDED.rating,
    multiplier = EXCLUDED.multiplier,
    base_amount = EXCLUDED.base_amount,
    final_amount = EXCLUDED.final_amount,
    manual_override = EXCLUDED.manual_override,
    notes = EXCLUDED.notes,
    updated_at = NOW()
RETURNING id, company_id, structure_id, employee_id, performance_review_id, rating, multiplier, base_amount, final_amount, manual_override, status, payroll_cycle_id, approved_by, approved_at, notes, created_at, updated_at
`

type CreateBonusAllocationParams struct {
	CompanyID           int64          `json:"company_id"`
	StructureID         int64          `json:"structure_id"`
	EmployeeID          int64          `json:"employee_id"`
	PerformanceReviewID *int64         `json:"performance_review_id"`
	Rating              *int32         `json:"rating"`
	Multiplier          pgtype.Numeric `json:"multiplier"`
	BaseAmount          pgtype.Numeric `json:"base_amount"`
	FinalAmount         pgtype.Numeric `json:"final_amount"`
	ManualOverride      pgtype.Numeric `json:"manual_override"`
	Notes               *string        `json:"notes"`
}

func (q *Queries) CreateBonusAllocation(ctx context.Context, arg CreateBonusAllocationParams) (BonusAllocation, error) {
	row := q.db.QueryRow(ctx, createBonusAllocation,
		arg.CompanyID,
		arg.StructureID,
		arg.EmployeeID,
		arg.PerformanceReviewID,
		arg.Rating,
		arg.Multiplier,
		arg.BaseAmount,
		arg.FinalAmount,
		arg.ManualOverride,
		arg.Notes,
	)
	var i BonusAllocation
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.StructureID,
		&i.EmployeeID,
		&i.PerformanceReviewID,
		&i.Rating,
		&i.Multiplier,
		&i.BaseAmount,
		&i.FinalAmount,
		&i.ManualOverride,
		&i.Status,
		&i.PayrollCycleID,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBonusStructure = `-- name: CreateBonusStructure :one
INSERT INTO bonus_structures (
    company_id, name, description, bonus_type, base_amount, base_type,
    rating_map, review_cycle_id, is_taxable, status, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, company_id, name, description, bonus_type, base_amount, base_type, rating_map, review_cycle_id, is_taxable, status, created_by, created_at, updated_at
`

type CreateBonusStructureParams struct {
	CompanyID     int64           `json:"company_id"`
	Name          string          `json:"name"`
	Description   *string         `json:"description"`
	BonusType     string          `json:"bonus_type"`
	BaseAmount    pgtype.Numeric  `json:"base_amount"`
	BaseType      string          `json:"base_type"`
	RatingMap     json.RawMessage `json:"rating_map"`
	ReviewCycleID *int64          `json:"review_cycle_id"`
	IsTaxable     bool            `json:"is_taxable"`
	Status        string          `json:"status"`
	CreatedBy     *int64          `json:"created_by"`
}

func (q *Queries) CreateBonusStructure(ctx context.Context, arg CreateBonusStructureParams) (BonusStructure, error) {
	row := q.db.QueryRow(ctx, createBonusStructure,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.BonusType,
		arg.BaseAmount,
		arg.BaseType,
		arg.RatingMap,
		arg.ReviewCycleID,
		arg.IsTaxable,
		arg.Status,
		arg.CreatedBy,
	)
	var i BonusStructure
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.BonusType,
		&i.BaseAmount,
		&i.BaseType,
		&i.RatingMap,
		&i.ReviewCycleID,
		&i.IsTaxable,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovedBonusesForPayroll = `-- name: GetApprovedBonusesForPayroll :many
SELECT ba.employee_id, SUM(
    CASE WHEN ba.manual_override IS NOT NULL THEN ba.manual_override ELSE ba.final_amount END
)::NUMERIC(12,2) AS total_bonus
FROM bonus_allocations ba
WHERE ba.company_id = $1
  AND ba.payroll_cycle_id = $2
  AND ba.status = 'approved'
GROUP BY ba.employee_id
`

type GetApprovedBonusesForPayrollParams struct {
	CompanyID      int64  `json:"company_id"`
	PayrollCycleID *int64 `json:"payroll_cycle_id"`
}

type GetApprovedBonusesForPayrollRow struct {
	EmployeeID int64          `json:"employee_id"`
	TotalBonus pgtype.Numeric `json:"total_bonus"`
}

func (q *Queries) GetApprovedBonusesForPayroll(ctx context.Context, arg GetApprovedBonusesForPayrollParams) ([]GetApprovedBonusesForPayrollRow, error) {
	rows, err := q.db.Query(ctx, getApprovedBonusesForPayroll, arg.CompanyID, arg.PayrollCycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetApprovedBonusesForPayrollRow{}
	for rows.Next() {
		var i GetApprovedBonusesForPayrollRow
		if err := rows.Scan(&i.EmployeeID, &i.TotalBonus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBonusStructure = `-- name: GetBonusStructure :one
SELECT bs.id, bs.company_id, bs.name, bs.description, bs.bonus_type, bs.base_amount, bs.base_type, bs.rating_map, bs.review_cycle_id, bs.is_taxable, bs.status, bs.created_by, bs.created_at, bs.updated_at, rc.name AS review_cycle_name
FROM bonus_structures bs
LEFT JOIN review_cycles rc ON rc.id = bs.review_cycle_id
WHERE bs.id = $1 AND bs.company_id = $2
`

type GetBonusStructureParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

type GetBonusStructureRow struct {
	ID              int64           `json:"id"`
	CompanyID       int64           `json:"company_id"`
	Name            string          `json:"name"`
	Description     *string         `json:"description"`
	BonusType       string          `json:"bonus_type"`
	BaseAmount      pgtype.Numeric  `json:"base_amount"`
	BaseType        string          `json:"base_type"`
	RatingMap       json.RawMessage `json:"rating_map"`
	ReviewCycleID   *int64          `json:"review_cycle_id"`
	IsTaxable       bool            `json:"is_taxable"`
	Status          string          `json:"status"`
	CreatedBy       *int64          `json:"created_by"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	ReviewCycleName *string         `json:"review_cycle_name"`
}

func (q *Queries) GetBonusStructure(ctx context.Context, arg GetBonusStructureParams) (GetBonusStructureRow, error) {
	row := q.db.QueryRow(ctx, getBonusStructure, arg.ID, arg.CompanyID)
	var i GetBonusStructureRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.BonusType,
		&i.BaseAmount,
		&i.BaseType,
		&i.RatingMap,
		&i.ReviewCycleID,
		&i.IsTaxable,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReviewCycleName,
	)
	return i, err
}

const getCompletedReviewsForBonusCalc = `-- name: GetCompletedReviewsForBonusCalc :many
SELECT pr.employee_id, pr.final_rating, pr.id AS review_id
FROM performance_reviews pr
WHERE pr.company_id = $1
  AND pr.review_cycle_id = $2
  AND pr.status = 'completed'
  AND pr.final_rating IS NOT NULL
`

type GetCompletedReviewsForBonusCalcParams struct {
	CompanyID     int64 `json:"company_id"`
	ReviewCycleID int64 `json:"review_cycle_id"`
}

type GetCompletedReviewsForBonusCalcRow struct {
	EmployeeID  int64  `json:"employee_id"`
	FinalRating *int32 `json:"final_rating"`
	ReviewID    int64  `json:"review_id"`
}

func (q *Queries) GetCompletedReviewsForBonusCalc(ctx context.Context, arg GetCompletedReviewsForBonusCalcParams) ([]GetCompletedReviewsForBonusCalcRow, error) {
	rows, err := q.db.Query(ctx, getCompletedReviewsForBonusCalc, arg.CompanyID, arg.ReviewCycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCompletedReviewsForBonusCalcRow{}
	for rows.Next() {
		var i GetCompletedReviewsForBonusCalcRow
		if err := rows.Scan(&i.EmployeeID, &i.FinalRating, &i.ReviewID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeSalaryForBonus = `-- name: GetEmployeeSalaryForBonus :one
SELECT es.basic_salary
FROM employee_salaries es
WHERE es.company_id = $1 AND es.employee_id = $2
  AND es.effective_from <= NOW()
  AND (es.effective_to IS NULL OR es.effective_to >= NOW())
ORDER BY es.effective_from DESC
LIMIT 1
`

type GetEmployeeSalaryForBonusParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
}

func (q *Queries) GetEmployeeSalaryForBonus(ctx context.Context, arg GetEmployeeSalaryForBonusParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getEmployeeSalaryForBonus, arg.CompanyID, arg.EmployeeID)
	var basic_salary pgtype.Numeric
	err := row.Scan(&basic_salary)
	return basic_salary, err
}

const linkBonusToPayrollCycle = `-- name: LinkBonusToPayrollCycle :exec
UPDATE bonus_allocations SET
    payroll_cycle_id = $2,
    updated_at = NOW()
WHERE structure_id = $1 AND status = 'approved'
`

type LinkBonusToPayrollCycleParams struct {
	StructureID    int64  `json:"structure_id"`
	PayrollCycleID *int64 `json:"payroll_cycle_id"`
}

func (q *Queries) LinkBonusToPayrollCycle(ctx context.Context, arg LinkBonusToPayrollCycleParams) error {
	_, err := q.db.Exec(ctx, linkBonusToPayrollCycle, arg.StructureID, arg.PayrollCycleID)
	return err
}

const listBonusAllocations = `-- name: ListBonusAllocations :many
SELECT ba.id, ba.company_id, ba.structure_id, ba.employee_id, ba.performance_review_id, ba.rating, ba.multiplier, ba.base_amount, ba.final_amount, ba.manual_override, ba.status, ba.payroll_cycle_id, ba.approved_by, ba.approved_at, ba.notes, ba.created_at, ba.updated_at, e.first_name, e.last_name, e.employee_no
FROM bonus_allocations ba
JOIN employees e ON e.id = ba.employee_id
WHERE ba.structure_id = $1
ORDER BY e.last_name, e.first_name
`

type ListBonusAllocationsRow struct {
	ID                  int64              `json:"id"`
	CompanyID           int64              `json:"company_id"`
	StructureID         int64              `json:"structure_id"`
	EmployeeID          int64              `json:"employee_id"`
	PerformanceReviewID *int64             `json:"performance_review_id"`
	Rating              *int32             `json:"rating"`
	Multiplier          pgtype.Numeric     `json:"multiplier"`
	BaseAmount          pgtype.Numeric     `json:"base_amount"`
	FinalAmount         pgtype.Numeric     `json:"final_amount"`
	ManualOverride      pgtype.Numeric     `json:"manual_override"`
	Status              string             `json:"status"`
	PayrollCycleID      *int64             `json:"payroll_cycle_id"`
	ApprovedBy          *int64             `json:"approved_by"`
	ApprovedAt          pgtype.Timestamptz `json:"approved_at"`
	Notes               *string            `json:"notes"`
	CreatedAt           time.Time          `json:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	EmployeeNo          string             `json:"employee_no"`
}

func (q *Queries) ListBonusAllocations(ctx context.Context, structureID int64) ([]ListBonusAllocationsRow, error) {
	rows, err := q.db.Query(ctx, listBonusAllocations, structureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBonusAllocationsRow{}
	for rows.Next() {
		var i ListBonusAllocationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.StructureID,
			&i.EmployeeID,
			&i.PerformanceReviewID,
			&i.Rating,
			&i.Multiplier,
			&i.BaseAmount,
			&i.FinalAmount,
			&i.ManualOverride,
			&i.Status,
			&i.PayrollCycleID,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.EmployeeNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBonusStructures = `-- name: ListBonusStructures :many
SELECT bs.id, bs.company_id, bs.name, bs.description, bs.bonus_type, bs.base_amount, bs.base_type, bs.rating_map, bs.review_cycle_id, bs.is_taxable, bs.status, bs.created_by, bs.created_at, bs.updated_at, rc.name AS review_cycle_name
FROM bonus_structures bs
LEFT JOIN review_cycles rc ON rc.id = bs.review_cycle_id
WHERE bs.company_id = $1
  AND ($2::text = '' OR bs.status = $2)
ORDER BY bs.created_at DESC
`

type ListBonusStructuresParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
}

type ListBonusStructuresRow struct {
	ID              int64           `json:"id"`
	CompanyID       int64           `json:"company_id"`
	Name            string          `json:"name"`
	Description     *string         `json:"description"`
	BonusType       string          `json:"bonus_type"`
	BaseAmount      pgtype.Numeric  `json:"base_amount"`
	BaseType        string          `json:"base_type"`
	RatingMap       json.RawMessage `json:"rating_map"`
	ReviewCycleID   *int64          `json:"review_cycle_id"`
	IsTaxable       bool            `json:"is_taxable"`
	Status          string          `json:"status"`
	CreatedBy       *int64          `json:"created_by"`
	CreatedAt       time.Time       `json:"created_at"`
	UpdatedAt       time.Time       `json:"updated_at"`
	ReviewCycleName *string         `json:"review_cycle_name"`
}

func (q *Queries) ListBonusStructures(ctx context.Context, arg ListBonusStructuresParams) ([]ListBonusStructuresRow, error) {
	rows, err := q.db.Query(ctx, listBonusStructures, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBonusStructuresRow{}
	for rows.Next() {
		var i ListBonusStructuresRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.BonusType,
			&i.BaseAmount,
			&i.BaseType,
			&i.RatingMap,
			&i.ReviewCycleID,
			&i.IsTaxable,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReviewCycleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBonusAllocationStatus = `-- name: UpdateBonusAllocationStatus :exec
UPDATE bonus_allocations SET
    status = $2,
    approved_by = $3,
    approved_at = CASE WHEN $2 = 'approved' THEN NOW() ELSE approved_at END,
    updated_at = NOW()
WHERE id = $1
`

type UpdateBonusAllocationStatusParams struct {
	ID         int64  `json:"id"`
	Status     string `json:"status"`
	ApprovedBy *int64 `json:"approved_by"`
}

func (q *Queries) UpdateBonusAllocationStatus(ctx context.Context, arg UpdateBonusAllocationStatusParams) error {
	_, err := q.db.Exec(ctx, updateBonusAllocationStatus, arg.ID, arg.Status, arg.ApprovedBy)
	return err
}

const updateBonusStructureStatus = `-- name: UpdateBonusStructureStatus :one
UPDATE bonus_structures SET status = $3, updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, description, bonus_type, base_amount, base_type, rating_map, review_cycle_id, is_taxable, status, created_by, created_at, updated_at
`

type UpdateBonusStructureStatusParams struct {
	ID        int64  `json:"id"`
	CompanyID int64  `json:"company_id"`
	Status    string `json:"status"`
}

func (q *Queries) UpdateBonusStructureStatus(ctx context.Context, arg UpdateBonusStructureStatusParams) (BonusStructure, error) {
	row := q.db.QueryRow(ctx, updateBonusStructureStatus, arg.ID, arg.CompanyID, arg.Status)
	var i BonusStructure
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.BonusType,
		&i.BaseAmount,
		&i.BaseType,
		&i.RatingMap,
		&i.ReviewCycleID,
		&i.IsTaxable,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
