// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: breaks.sql

package store

import (
	"context"
	"time"
)

const createBreakLog = `-- name: CreateBreakLog :one
INSERT INTO break_logs (company_id, employee_id, attendance_log_id, break_type, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, employee_id, attendance_log_id, break_type, start_at, end_at, duration_minutes, overtime_minutes, note, created_at
`

type CreateBreakLogParams struct {
	CompanyID       int64   `json:"company_id"`
	EmployeeID      int64   `json:"employee_id"`
	AttendanceLogID int64   `json:"attendance_log_id"`
	BreakType       string  `json:"break_type"`
	Note            *string `json:"note"`
}

func (q *Queries) CreateBreakLog(ctx context.Context, arg CreateBreakLogParams) (BreakLog, error) {
	row := q.db.QueryRow(ctx, createBreakLog,
		arg.CompanyID,
		arg.EmployeeID,
		arg.AttendanceLogID,
		arg.BreakType,
		arg.Note,
	)
	var i BreakLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.AttendanceLogID,
		&i.BreakType,
		&i.StartAt,
		&i.EndAt,
		&i.DurationMinutes,
		&i.OvertimeMinutes,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const endBreakLog = `-- name: EndBreakLog :one
UPDATE break_logs SET
    end_at = NOW(),
    duration_minutes = EXTRACT(EPOCH FROM (NOW() - start_at))::int / 60,
    overtime_minutes = CASE
        WHEN $2::int > 0 AND EXTRACT(EPOCH FROM (NOW() - start_at))::int / 60 > $2::int
        THEN EXTRACT(EPOCH FROM (NOW() - start_at))::int / 60 - $2::int
        ELSE 0
    END
WHERE id = $1 AND end_at IS NULL
RETURNING id, company_id, employee_id, attendance_log_id, break_type, start_at, end_at, duration_minutes, overtime_minutes, note, created_at
`

type EndBreakLogParams struct {
	ID      int64 `json:"id"`
	Column2 int32 `json:"column_2"`
}

func (q *Queries) EndBreakLog(ctx context.Context, arg EndBreakLogParams) (BreakLog, error) {
	row := q.db.QueryRow(ctx, endBreakLog, arg.ID, arg.Column2)
	var i BreakLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.AttendanceLogID,
		&i.BreakType,
		&i.StartAt,
		&i.EndAt,
		&i.DurationMinutes,
		&i.OvertimeMinutes,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveBreak = `-- name: GetActiveBreak :one
SELECT id, company_id, employee_id, attendance_log_id, break_type, start_at, end_at, duration_minutes, overtime_minutes, note, created_at FROM break_logs
WHERE employee_id = $1 AND company_id = $2 AND end_at IS NULL
ORDER BY start_at DESC LIMIT 1
`

type GetActiveBreakParams struct {
	EmployeeID int64 `json:"employee_id"`
	CompanyID  int64 `json:"company_id"`
}

func (q *Queries) GetActiveBreak(ctx context.Context, arg GetActiveBreakParams) (BreakLog, error) {
	row := q.db.QueryRow(ctx, getActiveBreak, arg.EmployeeID, arg.CompanyID)
	var i BreakLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.AttendanceLogID,
		&i.BreakType,
		&i.StartAt,
		&i.EndAt,
		&i.DurationMinutes,
		&i.OvertimeMinutes,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getBreakPolicy = `-- name: GetBreakPolicy :one
SELECT id, company_id, break_type, max_minutes, is_active, created_at, updated_at FROM break_policies
WHERE company_id = $1 AND break_type = $2 AND is_active = true
`

type GetBreakPolicyParams struct {
	CompanyID int64  `json:"company_id"`
	BreakType string `json:"break_type"`
}

func (q *Queries) GetBreakPolicy(ctx context.Context, arg GetBreakPolicyParams) (BreakPolicy, error) {
	row := q.db.QueryRow(ctx, getBreakPolicy, arg.CompanyID, arg.BreakType)
	var i BreakPolicy
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BreakType,
		&i.MaxMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMonthlyBreakSummary = `-- name: GetMonthlyBreakSummary :many
SELECT
    bl.employee_id,
    bl.break_type,
    COUNT(*)::int as total_count,
    COALESCE(SUM(bl.duration_minutes), 0)::int as total_minutes,
    COALESCE(SUM(bl.overtime_minutes), 0)::int as total_overtime_minutes,
    COUNT(CASE WHEN bl.overtime_minutes > 0 THEN 1 END)::int as overtime_count
FROM break_logs bl
WHERE bl.company_id = $1
    AND bl.start_at >= $2 AND bl.start_at < $3
    AND bl.end_at IS NOT NULL
GROUP BY bl.employee_id, bl.break_type
`

type GetMonthlyBreakSummaryParams struct {
	CompanyID int64     `json:"company_id"`
	StartAt   time.Time `json:"start_at"`
	StartAt_2 time.Time `json:"start_at_2"`
}

type GetMonthlyBreakSummaryRow struct {
	EmployeeID           int64  `json:"employee_id"`
	BreakType            string `json:"break_type"`
	TotalCount           int32  `json:"total_count"`
	TotalMinutes         int32  `json:"total_minutes"`
	TotalOvertimeMinutes int32  `json:"total_overtime_minutes"`
	OvertimeCount        int32  `json:"overtime_count"`
}

func (q *Queries) GetMonthlyBreakSummary(ctx context.Context, arg GetMonthlyBreakSummaryParams) ([]GetMonthlyBreakSummaryRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyBreakSummary, arg.CompanyID, arg.StartAt, arg.StartAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyBreakSummaryRow{}
	for rows.Next() {
		var i GetMonthlyBreakSummaryRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.BreakType,
			&i.TotalCount,
			&i.TotalMinutes,
			&i.TotalOvertimeMinutes,
			&i.OvertimeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBreakPolicies = `-- name: ListBreakPolicies :many
SELECT id, company_id, break_type, max_minutes, is_active, created_at, updated_at FROM break_policies
WHERE company_id = $1 AND is_active = true
`

func (q *Queries) ListBreakPolicies(ctx context.Context, companyID int64) ([]BreakPolicy, error) {
	rows, err := q.db.Query(ctx, listBreakPolicies, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakPolicy{}
	for rows.Next() {
		var i BreakPolicy
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.BreakType,
			&i.MaxMinutes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBreaksByAttendance = `-- name: ListBreaksByAttendance :many
SELECT id, company_id, employee_id, attendance_log_id, break_type, start_at, end_at, duration_minutes, overtime_minutes, note, created_at FROM break_logs
WHERE attendance_log_id = $1
ORDER BY start_at
`

func (q *Queries) ListBreaksByAttendance(ctx context.Context, attendanceLogID int64) ([]BreakLog, error) {
	rows, err := q.db.Query(ctx, listBreaksByAttendance, attendanceLogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakLog{}
	for rows.Next() {
		var i BreakLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.AttendanceLogID,
			&i.BreakType,
			&i.StartAt,
			&i.EndAt,
			&i.DurationMinutes,
			&i.OvertimeMinutes,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBreaksByDate = `-- name: ListBreaksByDate :many
SELECT id, company_id, employee_id, attendance_log_id, break_type, start_at, end_at, duration_minutes, overtime_minutes, note, created_at FROM break_logs
WHERE employee_id = $1 AND company_id = $2
    AND start_at >= $3 AND start_at < $4
ORDER BY start_at
`

type ListBreaksByDateParams struct {
	EmployeeID int64     `json:"employee_id"`
	CompanyID  int64     `json:"company_id"`
	StartAt    time.Time `json:"start_at"`
	StartAt_2  time.Time `json:"start_at_2"`
}

func (q *Queries) ListBreaksByDate(ctx context.Context, arg ListBreaksByDateParams) ([]BreakLog, error) {
	rows, err := q.db.Query(ctx, listBreaksByDate,
		arg.EmployeeID,
		arg.CompanyID,
		arg.StartAt,
		arg.StartAt_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BreakLog{}
	for rows.Next() {
		var i BreakLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.AttendanceLogID,
			&i.BreakType,
			&i.StartAt,
			&i.EndAt,
			&i.DurationMinutes,
			&i.OvertimeMinutes,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBreakPolicy = `-- name: UpsertBreakPolicy :one
INSERT INTO break_policies (company_id, break_type, max_minutes)
VALUES ($1, $2, $3)
ON CONFLICT (company_id, break_type)
DO UPDATE SET max_minutes = $3, updated_at = NOW()
RETURNING id, company_id, break_type, max_minutes, is_active, created_at, updated_at
`

type UpsertBreakPolicyParams struct {
	CompanyID  int64  `json:"company_id"`
	BreakType  string `json:"break_type"`
	MaxMinutes int32  `json:"max_minutes"`
}

func (q *Queries) UpsertBreakPolicy(ctx context.Context, arg UpsertBreakPolicyParams) (BreakPolicy, error) {
	row := q.db.QueryRow(ctx, upsertBreakPolicy, arg.CompanyID, arg.BreakType, arg.MaxMinutes)
	var i BreakPolicy
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.BreakType,
		&i.MaxMinutes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
