// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createChatSession = `-- name: CreateChatSession :one
INSERT INTO chat_sessions (company_id, user_id, agent_slug, title)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, user_id, agent_slug, title, created_at, updated_at
`

type CreateChatSessionParams struct {
	CompanyID int64  `json:"company_id"`
	UserID    int64  `json:"user_id"`
	AgentSlug string `json:"agent_slug"`
	Title     string `json:"title"`
}

func (q *Queries) CreateChatSession(ctx context.Context, arg CreateChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createChatSession,
		arg.CompanyID,
		arg.UserID,
		arg.AgentSlug,
		arg.Title,
	)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AgentSlug,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChatSession = `-- name: DeleteChatSession :exec
DELETE FROM chat_sessions
WHERE id = $1 AND user_id = $2
`

type DeleteChatSessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID int64     `json:"user_id"`
}

func (q *Queries) DeleteChatSession(ctx context.Context, arg DeleteChatSessionParams) error {
	_, err := q.db.Exec(ctx, deleteChatSession, arg.ID, arg.UserID)
	return err
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, company_id, user_id, agent_slug, title, created_at, updated_at FROM chat_sessions
WHERE id = $1 AND company_id = $2
`

type GetChatSessionParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID int64     `json:"company_id"`
}

func (q *Queries) GetChatSession(ctx context.Context, arg GetChatSessionParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSession, arg.ID, arg.CompanyID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AgentSlug,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChatMessage = `-- name: InsertChatMessage :one
INSERT INTO chat_messages (session_id, role, content, tokens_used)
VALUES ($1, $2, $3, $4)
RETURNING id, session_id, role, content, tokens_used, created_at
`

type InsertChatMessageParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	Role       string    `json:"role"`
	Content    string    `json:"content"`
	TokensUsed int32     `json:"tokens_used"`
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, insertChatMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.TokensUsed,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.TokensUsed,
		&i.CreatedAt,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT id, session_id, role, content, tokens_used, created_at FROM chat_messages
WHERE session_id = $1
ORDER BY created_at ASC
LIMIT 50
`

func (q *Queries) ListChatMessages(ctx context.Context, sessionID uuid.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, listChatMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.TokensUsed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChatSessions = `-- name: ListUserChatSessions :many
SELECT id, company_id, user_id, agent_slug, title, created_at, updated_at FROM chat_sessions
WHERE user_id = $1 AND company_id = $2
ORDER BY updated_at DESC
LIMIT 20
`

type ListUserChatSessionsParams struct {
	UserID    int64 `json:"user_id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) ListUserChatSessions(ctx context.Context, arg ListUserChatSessionsParams) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listUserChatSessions, arg.UserID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AgentSlug,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchChatSession = `-- name: TouchChatSession :exec
UPDATE chat_sessions SET updated_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchChatSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchChatSession, id)
	return err
}

const updateChatSessionTitle = `-- name: UpdateChatSessionTitle :exec
UPDATE chat_sessions SET title = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateChatSessionTitleParams struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) UpdateChatSessionTitle(ctx context.Context, arg UpdateChatSessionTitleParams) error {
	_, err := q.db.Exec(ctx, updateChatSessionTitle, arg.ID, arg.Title)
	return err
}
