// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_feedback.sql

package store

import (
	"context"
	"time"
)

const getFeedbackByMessage = `-- name: GetFeedbackByMessage :one
SELECT id, message_id, company_id, user_id, rating, comment, created_at FROM chat_message_feedback WHERE message_id = $1 AND user_id = $2
`

type GetFeedbackByMessageParams struct {
	MessageID int64 `json:"message_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetFeedbackByMessage(ctx context.Context, arg GetFeedbackByMessageParams) (ChatMessageFeedback, error) {
	row := q.db.QueryRow(ctx, getFeedbackByMessage, arg.MessageID, arg.UserID)
	var i ChatMessageFeedback
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.CompanyID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getFeedbackStats = `-- name: GetFeedbackStats :many
SELECT rating, COUNT(*) as count
FROM chat_message_feedback
WHERE company_id = $1
GROUP BY rating
`

type GetFeedbackStatsRow struct {
	Rating string `json:"rating"`
	Count  int64  `json:"count"`
}

func (q *Queries) GetFeedbackStats(ctx context.Context, companyID int64) ([]GetFeedbackStatsRow, error) {
	rows, err := q.db.Query(ctx, getFeedbackStats, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFeedbackStatsRow{}
	for rows.Next() {
		var i GetFeedbackStatsRow
		if err := rows.Scan(&i.Rating, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChatFeedback = `-- name: InsertChatFeedback :one
INSERT INTO chat_message_feedback (message_id, company_id, user_id, rating, comment)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (message_id, user_id) DO UPDATE SET rating = $4, comment = $5
RETURNING id, message_id, company_id, user_id, rating, comment, created_at
`

type InsertChatFeedbackParams struct {
	MessageID int64   `json:"message_id"`
	CompanyID int64   `json:"company_id"`
	UserID    int64   `json:"user_id"`
	Rating    string  `json:"rating"`
	Comment   *string `json:"comment"`
}

func (q *Queries) InsertChatFeedback(ctx context.Context, arg InsertChatFeedbackParams) (ChatMessageFeedback, error) {
	row := q.db.QueryRow(ctx, insertChatFeedback,
		arg.MessageID,
		arg.CompanyID,
		arg.UserID,
		arg.Rating,
		arg.Comment,
	)
	var i ChatMessageFeedback
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.CompanyID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentFeedback = `-- name: ListRecentFeedback :many
SELECT f.id, f.message_id, f.company_id, f.user_id, f.rating, f.comment, f.created_at, m.content as message_content, m.role as message_role
FROM chat_message_feedback f
JOIN chat_messages m ON m.id = f.message_id
WHERE f.company_id = $1
ORDER BY f.created_at DESC
LIMIT $2 OFFSET $3
`

type ListRecentFeedbackParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListRecentFeedbackRow struct {
	ID             int64     `json:"id"`
	MessageID      int64     `json:"message_id"`
	CompanyID      int64     `json:"company_id"`
	UserID         int64     `json:"user_id"`
	Rating         string    `json:"rating"`
	Comment        *string   `json:"comment"`
	CreatedAt      time.Time `json:"created_at"`
	MessageContent string    `json:"message_content"`
	MessageRole    string    `json:"message_role"`
}

func (q *Queries) ListRecentFeedback(ctx context.Context, arg ListRecentFeedbackParams) ([]ListRecentFeedbackRow, error) {
	rows, err := q.db.Query(ctx, listRecentFeedback, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentFeedbackRow{}
	for rows.Next() {
		var i ListRecentFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.CompanyID,
			&i.UserID,
			&i.Rating,
			&i.Comment,
			&i.CreatedAt,
			&i.MessageContent,
			&i.MessageRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
