// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compliance.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGovernmentForm = `-- name: CreateGovernmentForm :one
INSERT INTO government_forms (company_id, form_type, tax_year, period, payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, form_type, tax_year, period, status, payload, file_path, submitted_at, submitted_by, created_at
`

type CreateGovernmentFormParams struct {
	CompanyID int64           `json:"company_id"`
	FormType  string          `json:"form_type"`
	TaxYear   int32           `json:"tax_year"`
	Period    *string         `json:"period"`
	Payload   json.RawMessage `json:"payload"`
}

func (q *Queries) CreateGovernmentForm(ctx context.Context, arg CreateGovernmentFormParams) (GovernmentForm, error) {
	row := q.db.QueryRow(ctx, createGovernmentForm,
		arg.CompanyID,
		arg.FormType,
		arg.TaxYear,
		arg.Period,
		arg.Payload,
	)
	var i GovernmentForm
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FormType,
		&i.TaxYear,
		&i.Period,
		&i.Status,
		&i.Payload,
		&i.FilePath,
		&i.SubmittedAt,
		&i.SubmittedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getBIRTaxBracket = `-- name: GetBIRTaxBracket :one
SELECT id, effective_from, effective_to, frequency, bracket_min, bracket_max, fixed_tax, rate, excess_over FROM bir_tax_table
WHERE frequency = $1
  AND bracket_min <= $2
  AND (bracket_max IS NULL OR bracket_max > $2)
  AND effective_from <= $3
  AND (effective_to IS NULL OR effective_to >= $3)
LIMIT 1
`

type GetBIRTaxBracketParams struct {
	Frequency     string         `json:"frequency"`
	BracketMin    pgtype.Numeric `json:"bracket_min"`
	EffectiveFrom time.Time      `json:"effective_from"`
}

func (q *Queries) GetBIRTaxBracket(ctx context.Context, arg GetBIRTaxBracketParams) (BirTaxTable, error) {
	row := q.db.QueryRow(ctx, getBIRTaxBracket, arg.Frequency, arg.BracketMin, arg.EffectiveFrom)
	var i BirTaxTable
	err := row.Scan(
		&i.ID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Frequency,
		&i.BracketMin,
		&i.BracketMax,
		&i.FixedTax,
		&i.Rate,
		&i.ExcessOver,
	)
	return i, err
}

const getPagIBIGContribution = `-- name: GetPagIBIGContribution :one
SELECT id, effective_from, effective_to, salary_min, salary_max, ee_rate, er_rate, max_ee, max_er FROM pagibig_contribution_table
WHERE salary_min <= $1 AND salary_max >= $1
  AND effective_from <= $2
  AND (effective_to IS NULL OR effective_to >= $2)
LIMIT 1
`

type GetPagIBIGContributionParams struct {
	SalaryMin     pgtype.Numeric `json:"salary_min"`
	EffectiveFrom time.Time      `json:"effective_from"`
}

func (q *Queries) GetPagIBIGContribution(ctx context.Context, arg GetPagIBIGContributionParams) (PagibigContributionTable, error) {
	row := q.db.QueryRow(ctx, getPagIBIGContribution, arg.SalaryMin, arg.EffectiveFrom)
	var i PagibigContributionTable
	err := row.Scan(
		&i.ID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.EeRate,
		&i.ErRate,
		&i.MaxEe,
		&i.MaxEr,
	)
	return i, err
}

const getPayrollItemsForYear = `-- name: GetPayrollItemsForYear :many
SELECT pi.employee_id,
       e.employee_no, e.first_name, e.last_name, e.middle_name,
       e.birth_date, e.hire_date,
       ep.tin, ep.sss_no, ep.philhealth_no, ep.pagibig_no,
       pi.basic_pay, pi.gross_pay, pi.taxable_income,
       pi.total_deductions, pi.net_pay,
       pi.sss_ee, pi.sss_er, pi.sss_ec,
       pi.philhealth_ee, pi.philhealth_er,
       pi.pagibig_ee, pi.pagibig_er,
       pi.withholding_tax, pi.ot_hours, pi.work_days
FROM payroll_items pi
JOIN payroll_runs pr ON pr.id = pi.run_id
JOIN payroll_cycles pc ON pc.id = pr.cycle_id
JOIN employees e ON e.id = pi.employee_id
LEFT JOIN employee_profiles ep ON ep.employee_id = e.id
WHERE pc.company_id = $1
  AND pc.period_start >= $2
  AND pc.period_start < $3
  AND pr.status = 'completed'
ORDER BY e.last_name, e.first_name, pc.period_start
`

type GetPayrollItemsForYearParams struct {
	CompanyID     int64     `json:"company_id"`
	PeriodStart   time.Time `json:"period_start"`
	PeriodStart_2 time.Time `json:"period_start_2"`
}

type GetPayrollItemsForYearRow struct {
	EmployeeID      int64          `json:"employee_id"`
	EmployeeNo      string         `json:"employee_no"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	MiddleName      *string        `json:"middle_name"`
	BirthDate       pgtype.Date    `json:"birth_date"`
	HireDate        time.Time      `json:"hire_date"`
	Tin             *string        `json:"tin"`
	SssNo           *string        `json:"sss_no"`
	PhilhealthNo    *string        `json:"philhealth_no"`
	PagibigNo       *string        `json:"pagibig_no"`
	BasicPay        pgtype.Numeric `json:"basic_pay"`
	GrossPay        pgtype.Numeric `json:"gross_pay"`
	TaxableIncome   pgtype.Numeric `json:"taxable_income"`
	TotalDeductions pgtype.Numeric `json:"total_deductions"`
	NetPay          pgtype.Numeric `json:"net_pay"`
	SssEe           pgtype.Numeric `json:"sss_ee"`
	SssEr           pgtype.Numeric `json:"sss_er"`
	SssEc           pgtype.Numeric `json:"sss_ec"`
	PhilhealthEe    pgtype.Numeric `json:"philhealth_ee"`
	PhilhealthEr    pgtype.Numeric `json:"philhealth_er"`
	PagibigEe       pgtype.Numeric `json:"pagibig_ee"`
	PagibigEr       pgtype.Numeric `json:"pagibig_er"`
	WithholdingTax  pgtype.Numeric `json:"withholding_tax"`
	OtHours         pgtype.Numeric `json:"ot_hours"`
	WorkDays        pgtype.Numeric `json:"work_days"`
}

func (q *Queries) GetPayrollItemsForYear(ctx context.Context, arg GetPayrollItemsForYearParams) ([]GetPayrollItemsForYearRow, error) {
	rows, err := q.db.Query(ctx, getPayrollItemsForYear, arg.CompanyID, arg.PeriodStart, arg.PeriodStart_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPayrollItemsForYearRow{}
	for rows.Next() {
		var i GetPayrollItemsForYearRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.BirthDate,
			&i.HireDate,
			&i.Tin,
			&i.SssNo,
			&i.PhilhealthNo,
			&i.PagibigNo,
			&i.BasicPay,
			&i.GrossPay,
			&i.TaxableIncome,
			&i.TotalDeductions,
			&i.NetPay,
			&i.SssEe,
			&i.SssEr,
			&i.SssEc,
			&i.PhilhealthEe,
			&i.PhilhealthEr,
			&i.PagibigEe,
			&i.PagibigEr,
			&i.WithholdingTax,
			&i.OtHours,
			&i.WorkDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPayrollItemsWithEmployeeForPeriod = `-- name: GetPayrollItemsWithEmployeeForPeriod :many
SELECT pi.employee_id,
       e.employee_no, e.first_name, e.last_name, e.middle_name,
       e.birth_date, e.hire_date,
       ep.tin, ep.sss_no, ep.philhealth_no, ep.pagibig_no,
       pi.basic_pay, pi.gross_pay, pi.taxable_income,
       pi.total_deductions, pi.net_pay,
       pi.sss_ee, pi.sss_er, pi.sss_ec,
       pi.philhealth_ee, pi.philhealth_er,
       pi.pagibig_ee, pi.pagibig_er,
       pi.withholding_tax, pi.ot_hours, pi.work_days
FROM payroll_items pi
JOIN payroll_runs pr ON pr.id = pi.run_id
JOIN payroll_cycles pc ON pc.id = pr.cycle_id
JOIN employees e ON e.id = pi.employee_id
LEFT JOIN employee_profiles ep ON ep.employee_id = e.id
WHERE pc.company_id = $1
  AND pc.period_start >= $2
  AND pc.period_end <= $3
  AND pr.status = 'completed'
ORDER BY e.last_name, e.first_name
`

type GetPayrollItemsWithEmployeeForPeriodParams struct {
	CompanyID   int64     `json:"company_id"`
	PeriodStart time.Time `json:"period_start"`
	PeriodEnd   time.Time `json:"period_end"`
}

type GetPayrollItemsWithEmployeeForPeriodRow struct {
	EmployeeID      int64          `json:"employee_id"`
	EmployeeNo      string         `json:"employee_no"`
	FirstName       string         `json:"first_name"`
	LastName        string         `json:"last_name"`
	MiddleName      *string        `json:"middle_name"`
	BirthDate       pgtype.Date    `json:"birth_date"`
	HireDate        time.Time      `json:"hire_date"`
	Tin             *string        `json:"tin"`
	SssNo           *string        `json:"sss_no"`
	PhilhealthNo    *string        `json:"philhealth_no"`
	PagibigNo       *string        `json:"pagibig_no"`
	BasicPay        pgtype.Numeric `json:"basic_pay"`
	GrossPay        pgtype.Numeric `json:"gross_pay"`
	TaxableIncome   pgtype.Numeric `json:"taxable_income"`
	TotalDeductions pgtype.Numeric `json:"total_deductions"`
	NetPay          pgtype.Numeric `json:"net_pay"`
	SssEe           pgtype.Numeric `json:"sss_ee"`
	SssEr           pgtype.Numeric `json:"sss_er"`
	SssEc           pgtype.Numeric `json:"sss_ec"`
	PhilhealthEe    pgtype.Numeric `json:"philhealth_ee"`
	PhilhealthEr    pgtype.Numeric `json:"philhealth_er"`
	PagibigEe       pgtype.Numeric `json:"pagibig_ee"`
	PagibigEr       pgtype.Numeric `json:"pagibig_er"`
	WithholdingTax  pgtype.Numeric `json:"withholding_tax"`
	OtHours         pgtype.Numeric `json:"ot_hours"`
	WorkDays        pgtype.Numeric `json:"work_days"`
}

func (q *Queries) GetPayrollItemsWithEmployeeForPeriod(ctx context.Context, arg GetPayrollItemsWithEmployeeForPeriodParams) ([]GetPayrollItemsWithEmployeeForPeriodRow, error) {
	rows, err := q.db.Query(ctx, getPayrollItemsWithEmployeeForPeriod, arg.CompanyID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPayrollItemsWithEmployeeForPeriodRow{}
	for rows.Next() {
		var i GetPayrollItemsWithEmployeeForPeriodRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.BirthDate,
			&i.HireDate,
			&i.Tin,
			&i.SssNo,
			&i.PhilhealthNo,
			&i.PagibigNo,
			&i.BasicPay,
			&i.GrossPay,
			&i.TaxableIncome,
			&i.TotalDeductions,
			&i.NetPay,
			&i.SssEe,
			&i.SssEr,
			&i.SssEc,
			&i.PhilhealthEe,
			&i.PhilhealthEr,
			&i.PagibigEe,
			&i.PagibigEr,
			&i.WithholdingTax,
			&i.OtHours,
			&i.WorkDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPhilHealthContribution = `-- name: GetPhilHealthContribution :one
SELECT id, effective_from, effective_to, salary_min, salary_max, premium_rate, ee_share_rate, er_share_rate, floor_premium, ceiling_premium FROM philhealth_contribution_table
WHERE salary_min <= $1 AND salary_max >= $1
  AND effective_from <= $2
  AND (effective_to IS NULL OR effective_to >= $2)
LIMIT 1
`

type GetPhilHealthContributionParams struct {
	SalaryMin     pgtype.Numeric `json:"salary_min"`
	EffectiveFrom time.Time      `json:"effective_from"`
}

func (q *Queries) GetPhilHealthContribution(ctx context.Context, arg GetPhilHealthContributionParams) (PhilhealthContributionTable, error) {
	row := q.db.QueryRow(ctx, getPhilHealthContribution, arg.SalaryMin, arg.EffectiveFrom)
	var i PhilhealthContributionTable
	err := row.Scan(
		&i.ID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.SalaryMin,
		&i.SalaryMax,
		&i.PremiumRate,
		&i.EeShareRate,
		&i.ErShareRate,
		&i.FloorPremium,
		&i.CeilingPremium,
	)
	return i, err
}

const getSSSContribution = `-- name: GetSSSContribution :one
SELECT id, effective_from, effective_to, msc_min, msc_max, msc, ee_share, er_share, ec, total FROM sss_contribution_table
WHERE msc_min <= $1 AND msc_max >= $1
  AND effective_from <= $2
  AND (effective_to IS NULL OR effective_to >= $2)
LIMIT 1
`

type GetSSSContributionParams struct {
	MscMin        pgtype.Numeric `json:"msc_min"`
	EffectiveFrom time.Time      `json:"effective_from"`
}

func (q *Queries) GetSSSContribution(ctx context.Context, arg GetSSSContributionParams) (SssContributionTable, error) {
	row := q.db.QueryRow(ctx, getSSSContribution, arg.MscMin, arg.EffectiveFrom)
	var i SssContributionTable
	err := row.Scan(
		&i.ID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.MscMin,
		&i.MscMax,
		&i.Msc,
		&i.EeShare,
		&i.ErShare,
		&i.Ec,
		&i.Total,
	)
	return i, err
}

const listBIRTaxTable = `-- name: ListBIRTaxTable :many
SELECT id, effective_from, effective_to, frequency, bracket_min, bracket_max, fixed_tax, rate, excess_over FROM bir_tax_table
WHERE frequency = $1
  AND effective_from <= $2 AND (effective_to IS NULL OR effective_to >= $2)
ORDER BY bracket_min
`

type ListBIRTaxTableParams struct {
	Frequency     string    `json:"frequency"`
	EffectiveFrom time.Time `json:"effective_from"`
}

func (q *Queries) ListBIRTaxTable(ctx context.Context, arg ListBIRTaxTableParams) ([]BirTaxTable, error) {
	rows, err := q.db.Query(ctx, listBIRTaxTable, arg.Frequency, arg.EffectiveFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BirTaxTable{}
	for rows.Next() {
		var i BirTaxTable
		if err := rows.Scan(
			&i.ID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Frequency,
			&i.BracketMin,
			&i.BracketMax,
			&i.FixedTax,
			&i.Rate,
			&i.ExcessOver,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGovernmentForms = `-- name: ListGovernmentForms :many
SELECT id, company_id, form_type, tax_year, period, status, payload, file_path, submitted_at, submitted_by, created_at FROM government_forms
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListGovernmentFormsParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListGovernmentForms(ctx context.Context, arg ListGovernmentFormsParams) ([]GovernmentForm, error) {
	rows, err := q.db.Query(ctx, listGovernmentForms, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GovernmentForm{}
	for rows.Next() {
		var i GovernmentForm
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FormType,
			&i.TaxYear,
			&i.Period,
			&i.Status,
			&i.Payload,
			&i.FilePath,
			&i.SubmittedAt,
			&i.SubmittedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPagIBIGTable = `-- name: ListPagIBIGTable :many
SELECT id, effective_from, effective_to, salary_min, salary_max, ee_rate, er_rate, max_ee, max_er FROM pagibig_contribution_table
WHERE effective_from <= $1 AND (effective_to IS NULL OR effective_to >= $1)
ORDER BY salary_min
`

func (q *Queries) ListPagIBIGTable(ctx context.Context, effectiveFrom time.Time) ([]PagibigContributionTable, error) {
	rows, err := q.db.Query(ctx, listPagIBIGTable, effectiveFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PagibigContributionTable{}
	for rows.Next() {
		var i PagibigContributionTable
		if err := rows.Scan(
			&i.ID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.EeRate,
			&i.ErRate,
			&i.MaxEe,
			&i.MaxEr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhilHealthTable = `-- name: ListPhilHealthTable :many
SELECT id, effective_from, effective_to, salary_min, salary_max, premium_rate, ee_share_rate, er_share_rate, floor_premium, ceiling_premium FROM philhealth_contribution_table
WHERE effective_from <= $1 AND (effective_to IS NULL OR effective_to >= $1)
ORDER BY salary_min
`

func (q *Queries) ListPhilHealthTable(ctx context.Context, effectiveFrom time.Time) ([]PhilhealthContributionTable, error) {
	rows, err := q.db.Query(ctx, listPhilHealthTable, effectiveFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PhilhealthContributionTable{}
	for rows.Next() {
		var i PhilhealthContributionTable
		if err := rows.Scan(
			&i.ID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.SalaryMin,
			&i.SalaryMax,
			&i.PremiumRate,
			&i.EeShareRate,
			&i.ErShareRate,
			&i.FloorPremium,
			&i.CeilingPremium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSSTable = `-- name: ListSSSTable :many
SELECT id, effective_from, effective_to, msc_min, msc_max, msc, ee_share, er_share, ec, total FROM sss_contribution_table
WHERE effective_from <= $1 AND (effective_to IS NULL OR effective_to >= $1)
ORDER BY msc_min
`

func (q *Queries) ListSSSTable(ctx context.Context, effectiveFrom time.Time) ([]SssContributionTable, error) {
	rows, err := q.db.Query(ctx, listSSSTable, effectiveFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SssContributionTable{}
	for rows.Next() {
		var i SssContributionTable
		if err := rows.Scan(
			&i.ID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.MscMin,
			&i.MscMax,
			&i.Msc,
			&i.EeShare,
			&i.ErShare,
			&i.Ec,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
