// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contract_milestone.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeMilestone = `-- name: AcknowledgeMilestone :one
UPDATE contract_milestones SET
    status = 'acknowledged',
    acknowledged_by = $3,
    acknowledged_at = NOW(),
    notes = $4,
    updated_at = NOW()
WHERE id = $1 AND company_id = $2 AND status = 'pending'
RETURNING id, company_id, employee_id, milestone_type, milestone_date, days_remaining, status, acknowledged_by, acknowledged_at, notes, created_at, updated_at
`

type AcknowledgeMilestoneParams struct {
	ID             int64   `json:"id"`
	CompanyID      int64   `json:"company_id"`
	AcknowledgedBy *int64  `json:"acknowledged_by"`
	Notes          *string `json:"notes"`
}

func (q *Queries) AcknowledgeMilestone(ctx context.Context, arg AcknowledgeMilestoneParams) (ContractMilestone, error) {
	row := q.db.QueryRow(ctx, acknowledgeMilestone,
		arg.ID,
		arg.CompanyID,
		arg.AcknowledgedBy,
		arg.Notes,
	)
	var i ContractMilestone
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.MilestoneType,
		&i.MilestoneDate,
		&i.DaysRemaining,
		&i.Status,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const actionMilestone = `-- name: ActionMilestone :one
UPDATE contract_milestones SET
    status = 'actioned',
    notes = $3,
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, employee_id, milestone_type, milestone_date, days_remaining, status, acknowledged_by, acknowledged_at, notes, created_at, updated_at
`

type ActionMilestoneParams struct {
	ID        int64   `json:"id"`
	CompanyID int64   `json:"company_id"`
	Notes     *string `json:"notes"`
}

func (q *Queries) ActionMilestone(ctx context.Context, arg ActionMilestoneParams) (ContractMilestone, error) {
	row := q.db.QueryRow(ctx, actionMilestone, arg.ID, arg.CompanyID, arg.Notes)
	var i ContractMilestone
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.MilestoneType,
		&i.MilestoneDate,
		&i.DaysRemaining,
		&i.Status,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countContractMilestones = `-- name: CountContractMilestones :one
SELECT COUNT(*) FROM contract_milestones
WHERE company_id = $1
  AND ($2 = '' OR status = $2)
  AND ($3 = '' OR milestone_type = $3)
`

type CountContractMilestonesParams struct {
	CompanyID     int64       `json:"company_id"`
	Status        interface{} `json:"status"`
	MilestoneType interface{} `json:"milestone_type"`
}

func (q *Queries) CountContractMilestones(ctx context.Context, arg CountContractMilestonesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countContractMilestones, arg.CompanyID, arg.Status, arg.MilestoneType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldMilestones = `-- name: DeleteOldMilestones :exec
DELETE FROM contract_milestones
WHERE status IN ('acknowledged', 'actioned')
  AND milestone_date < CURRENT_DATE - INTERVAL '90 days'
`

func (q *Queries) DeleteOldMilestones(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldMilestones)
	return err
}

const listContractMilestones = `-- name: ListContractMilestones :many
SELECT cm.id, cm.company_id, cm.employee_id, cm.milestone_type, cm.milestone_date, cm.days_remaining, cm.status, cm.acknowledged_by, cm.acknowledged_at, cm.notes, cm.created_at, cm.updated_at, e.employee_no, e.first_name, e.last_name, e.employment_type,
       COALESCE(d.name, '') as department_name
FROM contract_milestones cm
JOIN employees e ON e.id = cm.employee_id
LEFT JOIN departments d ON d.id = e.department_id
WHERE cm.company_id = $1
  AND ($2 = '' OR cm.status = $2)
  AND ($3 = '' OR cm.milestone_type = $3)
ORDER BY cm.milestone_date ASC
LIMIT $5 OFFSET $4
`

type ListContractMilestonesParams struct {
	CompanyID     int64       `json:"company_id"`
	Status        interface{} `json:"status"`
	MilestoneType interface{} `json:"milestone_type"`
	Off           int32       `json:"off"`
	Lim           int32       `json:"lim"`
}

type ListContractMilestonesRow struct {
	ID             int64              `json:"id"`
	CompanyID      int64              `json:"company_id"`
	EmployeeID     int64              `json:"employee_id"`
	MilestoneType  string             `json:"milestone_type"`
	MilestoneDate  time.Time          `json:"milestone_date"`
	DaysRemaining  int32              `json:"days_remaining"`
	Status         string             `json:"status"`
	AcknowledgedBy *int64             `json:"acknowledged_by"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	Notes          *string            `json:"notes"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	EmployeeNo     string             `json:"employee_no"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	EmploymentType string             `json:"employment_type"`
	DepartmentName string             `json:"department_name"`
}

func (q *Queries) ListContractMilestones(ctx context.Context, arg ListContractMilestonesParams) ([]ListContractMilestonesRow, error) {
	rows, err := q.db.Query(ctx, listContractMilestones,
		arg.CompanyID,
		arg.Status,
		arg.MilestoneType,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContractMilestonesRow{}
	for rows.Next() {
		var i ListContractMilestonesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.MilestoneType,
			&i.MilestoneDate,
			&i.DaysRemaining,
			&i.Status,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.EmploymentType,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContractualEmployees = `-- name: ListContractualEmployees :many
SELECT id, company_id, employee_no, first_name, last_name,
       hire_date, contract_end_date, employment_type, status
FROM employees
WHERE company_id = $1
  AND employment_type = 'contractual'
  AND status = 'active'
  AND contract_end_date IS NOT NULL
ORDER BY contract_end_date
`

type ListContractualEmployeesRow struct {
	ID              int64       `json:"id"`
	CompanyID       int64       `json:"company_id"`
	EmployeeNo      string      `json:"employee_no"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	HireDate        time.Time   `json:"hire_date"`
	ContractEndDate pgtype.Date `json:"contract_end_date"`
	EmploymentType  string      `json:"employment_type"`
	Status          string      `json:"status"`
}

func (q *Queries) ListContractualEmployees(ctx context.Context, companyID int64) ([]ListContractualEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listContractualEmployees, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContractualEmployeesRow{}
	for rows.Next() {
		var i ListContractualEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.HireDate,
			&i.ContractEndDate,
			&i.EmploymentType,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMilestonesByCompany = `-- name: ListPendingMilestonesByCompany :many
SELECT cm.id, cm.company_id, cm.employee_id, cm.milestone_type, cm.milestone_date, cm.days_remaining, cm.status, cm.acknowledged_by, cm.acknowledged_at, cm.notes, cm.created_at, cm.updated_at, e.employee_no, e.first_name, e.last_name, e.employment_type,
       COALESCE(d.name, '') as department_name
FROM contract_milestones cm
JOIN employees e ON e.id = cm.employee_id
LEFT JOIN departments d ON d.id = e.department_id
WHERE cm.company_id = $1
  AND cm.status = 'pending'
  AND cm.milestone_date <= CURRENT_DATE + INTERVAL '30 days'
ORDER BY cm.milestone_date ASC
`

type ListPendingMilestonesByCompanyRow struct {
	ID             int64              `json:"id"`
	CompanyID      int64              `json:"company_id"`
	EmployeeID     int64              `json:"employee_id"`
	MilestoneType  string             `json:"milestone_type"`
	MilestoneDate  time.Time          `json:"milestone_date"`
	DaysRemaining  int32              `json:"days_remaining"`
	Status         string             `json:"status"`
	AcknowledgedBy *int64             `json:"acknowledged_by"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	Notes          *string            `json:"notes"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	EmployeeNo     string             `json:"employee_no"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	EmploymentType string             `json:"employment_type"`
	DepartmentName string             `json:"department_name"`
}

func (q *Queries) ListPendingMilestonesByCompany(ctx context.Context, companyID int64) ([]ListPendingMilestonesByCompanyRow, error) {
	rows, err := q.db.Query(ctx, listPendingMilestonesByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingMilestonesByCompanyRow{}
	for rows.Next() {
		var i ListPendingMilestonesByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.MilestoneType,
			&i.MilestoneDate,
			&i.DaysRemaining,
			&i.Status,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.EmploymentType,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProbationaryEmployees = `-- name: ListProbationaryEmployees :many
SELECT id, company_id, employee_no, first_name, last_name,
       hire_date, regularization_date, employment_type, status
FROM employees
WHERE company_id = $1
  AND employment_type = 'probationary'
  AND status IN ('active', 'probationary')
ORDER BY hire_date
`

type ListProbationaryEmployeesRow struct {
	ID                 int64       `json:"id"`
	CompanyID          int64       `json:"company_id"`
	EmployeeNo         string      `json:"employee_no"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	HireDate           time.Time   `json:"hire_date"`
	RegularizationDate pgtype.Date `json:"regularization_date"`
	EmploymentType     string      `json:"employment_type"`
	Status             string      `json:"status"`
}

func (q *Queries) ListProbationaryEmployees(ctx context.Context, companyID int64) ([]ListProbationaryEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listProbationaryEmployees, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProbationaryEmployeesRow{}
	for rows.Next() {
		var i ListProbationaryEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.HireDate,
			&i.RegularizationDate,
			&i.EmploymentType,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingAnniversaries = `-- name: ListUpcomingAnniversaries :many
SELECT id, company_id, employee_no, first_name, last_name,
       hire_date, employment_type, status
FROM employees
WHERE company_id = $1
  AND status = 'active'
  AND EXTRACT(MONTH FROM hire_date) = $2::int
  AND EXTRACT(DAY FROM hire_date) BETWEEN $3::int AND $4::int
ORDER BY hire_date
`

type ListUpcomingAnniversariesParams struct {
	CompanyID int64 `json:"company_id"`
	Column2   int32 `json:"column_2"`
	Column3   int32 `json:"column_3"`
	Column4   int32 `json:"column_4"`
}

type ListUpcomingAnniversariesRow struct {
	ID             int64     `json:"id"`
	CompanyID      int64     `json:"company_id"`
	EmployeeNo     string    `json:"employee_no"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	HireDate       time.Time `json:"hire_date"`
	EmploymentType string    `json:"employment_type"`
	Status         string    `json:"status"`
}

func (q *Queries) ListUpcomingAnniversaries(ctx context.Context, arg ListUpcomingAnniversariesParams) ([]ListUpcomingAnniversariesRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingAnniversaries,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingAnniversariesRow{}
	for rows.Next() {
		var i ListUpcomingAnniversariesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.HireDate,
			&i.EmploymentType,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContractMilestone = `-- name: UpsertContractMilestone :one
INSERT INTO contract_milestones (company_id, employee_id, milestone_type, milestone_date, days_remaining)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (company_id, employee_id, milestone_type, milestone_date) DO UPDATE SET
    days_remaining = EXCLUDED.days_remaining,
    updated_at = NOW()
RETURNING id, company_id, employee_id, milestone_type, milestone_date, days_remaining, status, acknowledged_by, acknowledged_at, notes, created_at, updated_at
`

type UpsertContractMilestoneParams struct {
	CompanyID     int64     `json:"company_id"`
	EmployeeID    int64     `json:"employee_id"`
	MilestoneType string    `json:"milestone_type"`
	MilestoneDate time.Time `json:"milestone_date"`
	DaysRemaining int32     `json:"days_remaining"`
}

func (q *Queries) UpsertContractMilestone(ctx context.Context, arg UpsertContractMilestoneParams) (ContractMilestone, error) {
	row := q.db.QueryRow(ctx, upsertContractMilestone,
		arg.CompanyID,
		arg.EmployeeID,
		arg.MilestoneType,
		arg.MilestoneDate,
		arg.DaysRemaining,
	)
	var i ContractMilestone
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.MilestoneType,
		&i.MilestoneDate,
		&i.DaysRemaining,
		&i.Status,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
