// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: country_payroll.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCountryContributionRate = `-- name: GetCountryContributionRate :one
SELECT id, country, contribution_type, rate, effective_from, effective_to, description, created_at FROM country_contribution_rates
WHERE country = $1
  AND contribution_type = $2
  AND effective_from <= $3
  AND (effective_to IS NULL OR effective_to >= $3)
ORDER BY effective_from DESC
LIMIT 1
`

type GetCountryContributionRateParams struct {
	Country          string    `json:"country"`
	ContributionType string    `json:"contribution_type"`
	EffectiveFrom    time.Time `json:"effective_from"`
}

// Get a specific contribution rate for a country
func (q *Queries) GetCountryContributionRate(ctx context.Context, arg GetCountryContributionRateParams) (CountryContributionRate, error) {
	row := q.db.QueryRow(ctx, getCountryContributionRate, arg.Country, arg.ContributionType, arg.EffectiveFrom)
	var i CountryContributionRate
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.ContributionType,
		&i.Rate,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getCountryPayrollConfig = `-- name: GetCountryPayrollConfig :one
SELECT id, country, config_key, config_value, description, created_at FROM country_payroll_config
WHERE country = $1 AND config_key = $2
`

type GetCountryPayrollConfigParams struct {
	Country   string `json:"country"`
	ConfigKey string `json:"config_key"`
}

// Get a specific payroll config key for a country
func (q *Queries) GetCountryPayrollConfig(ctx context.Context, arg GetCountryPayrollConfigParams) (CountryPayrollConfig, error) {
	row := q.db.QueryRow(ctx, getCountryPayrollConfig, arg.Country, arg.ConfigKey)
	var i CountryPayrollConfig
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.ConfigKey,
		&i.ConfigValue,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getCountryTaxBracket = `-- name: GetCountryTaxBracket :one
SELECT id, country, effective_from, effective_to, frequency, bracket_min, bracket_max, tax_rate, fixed_amount, description, created_at FROM country_tax_brackets
WHERE country = $1
  AND frequency = $2
  AND bracket_min <= $3
  AND (bracket_max IS NULL OR bracket_max >= $3)
  AND effective_from <= $4
  AND (effective_to IS NULL OR effective_to >= $4)
ORDER BY bracket_min DESC
LIMIT 1
`

type GetCountryTaxBracketParams struct {
	Country       string         `json:"country"`
	Frequency     string         `json:"frequency"`
	BracketMin    pgtype.Numeric `json:"bracket_min"`
	EffectiveFrom time.Time      `json:"effective_from"`
}

// Lookup the tax bracket for a given country, income amount, frequency, and date
func (q *Queries) GetCountryTaxBracket(ctx context.Context, arg GetCountryTaxBracketParams) (CountryTaxBracket, error) {
	row := q.db.QueryRow(ctx, getCountryTaxBracket,
		arg.Country,
		arg.Frequency,
		arg.BracketMin,
		arg.EffectiveFrom,
	)
	var i CountryTaxBracket
	err := row.Scan(
		&i.ID,
		&i.Country,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.Frequency,
		&i.BracketMin,
		&i.BracketMax,
		&i.TaxRate,
		&i.FixedAmount,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listCountryContributionRates = `-- name: ListCountryContributionRates :many
SELECT id, country, contribution_type, rate, effective_from, effective_to, description, created_at FROM country_contribution_rates
WHERE country = $1
  AND effective_from <= $2
  AND (effective_to IS NULL OR effective_to >= $2)
`

type ListCountryContributionRatesParams struct {
	Country       string    `json:"country"`
	EffectiveFrom time.Time `json:"effective_from"`
}

// List all contribution rates for a country at a given date
func (q *Queries) ListCountryContributionRates(ctx context.Context, arg ListCountryContributionRatesParams) ([]CountryContributionRate, error) {
	rows, err := q.db.Query(ctx, listCountryContributionRates, arg.Country, arg.EffectiveFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountryContributionRate{}
	for rows.Next() {
		var i CountryContributionRate
		if err := rows.Scan(
			&i.ID,
			&i.Country,
			&i.ContributionType,
			&i.Rate,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountryPayrollConfigs = `-- name: ListCountryPayrollConfigs :many
SELECT id, country, config_key, config_value, description, created_at FROM country_payroll_config
WHERE country = $1
`

// List all payroll config for a country
func (q *Queries) ListCountryPayrollConfigs(ctx context.Context, country string) ([]CountryPayrollConfig, error) {
	rows, err := q.db.Query(ctx, listCountryPayrollConfigs, country)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountryPayrollConfig{}
	for rows.Next() {
		var i CountryPayrollConfig
		if err := rows.Scan(
			&i.ID,
			&i.Country,
			&i.ConfigKey,
			&i.ConfigValue,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCountryTaxBrackets = `-- name: ListCountryTaxBrackets :many
SELECT id, country, effective_from, effective_to, frequency, bracket_min, bracket_max, tax_rate, fixed_amount, description, created_at FROM country_tax_brackets
WHERE country = $1
  AND effective_from <= $2
  AND (effective_to IS NULL OR effective_to >= $2)
ORDER BY bracket_min
`

type ListCountryTaxBracketsParams struct {
	Country       string    `json:"country"`
	EffectiveFrom time.Time `json:"effective_from"`
}

// List all tax brackets for a country at a given date
func (q *Queries) ListCountryTaxBrackets(ctx context.Context, arg ListCountryTaxBracketsParams) ([]CountryTaxBracket, error) {
	rows, err := q.db.Query(ctx, listCountryTaxBrackets, arg.Country, arg.EffectiveFrom)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountryTaxBracket{}
	for rows.Next() {
		var i CountryTaxBracket
		if err := rows.Scan(
			&i.ID,
			&i.Country,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Frequency,
			&i.BracketMin,
			&i.BracketMax,
			&i.TaxRate,
			&i.FixedAmount,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
