// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: disciplinary.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acknowledgeDisciplinaryAction = `-- name: AcknowledgeDisciplinaryAction :one
UPDATE disciplinary_actions SET
    employee_acknowledged = true,
    acknowledged_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, employee_id, incident_id, action_type, action_date, issued_by, description, suspension_days, effective_date, end_date, employee_acknowledged, acknowledged_at, appeal_status, appeal_reason, appeal_date, appeal_resolved_at, appeal_resolved_by, appeal_resolution, notes, created_at, updated_at
`

type AcknowledgeDisciplinaryActionParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) AcknowledgeDisciplinaryAction(ctx context.Context, arg AcknowledgeDisciplinaryActionParams) (DisciplinaryAction, error) {
	row := q.db.QueryRow(ctx, acknowledgeDisciplinaryAction, arg.ID, arg.CompanyID)
	var i DisciplinaryAction
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.IncidentID,
		&i.ActionType,
		&i.ActionDate,
		&i.IssuedBy,
		&i.Description,
		&i.SuspensionDays,
		&i.EffectiveDate,
		&i.EndDate,
		&i.EmployeeAcknowledged,
		&i.AcknowledgedAt,
		&i.AppealStatus,
		&i.AppealReason,
		&i.AppealDate,
		&i.AppealResolvedAt,
		&i.AppealResolvedBy,
		&i.AppealResolution,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const appealDisciplinaryAction = `-- name: AppealDisciplinaryAction :one
UPDATE disciplinary_actions SET
    appeal_status = 'appealed',
    appeal_reason = $3,
    appeal_date = NOW(),
    updated_at = NOW()
WHERE id = $1 AND company_id = $2 AND (appeal_status IS NULL)
RETURNING id, company_id, employee_id, incident_id, action_type, action_date, issued_by, description, suspension_days, effective_date, end_date, employee_acknowledged, acknowledged_at, appeal_status, appeal_reason, appeal_date, appeal_resolved_at, appeal_resolved_by, appeal_resolution, notes, created_at, updated_at
`

type AppealDisciplinaryActionParams struct {
	ID           int64   `json:"id"`
	CompanyID    int64   `json:"company_id"`
	AppealReason *string `json:"appeal_reason"`
}

func (q *Queries) AppealDisciplinaryAction(ctx context.Context, arg AppealDisciplinaryActionParams) (DisciplinaryAction, error) {
	row := q.db.QueryRow(ctx, appealDisciplinaryAction, arg.ID, arg.CompanyID, arg.AppealReason)
	var i DisciplinaryAction
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.IncidentID,
		&i.ActionType,
		&i.ActionDate,
		&i.IssuedBy,
		&i.Description,
		&i.SuspensionDays,
		&i.EffectiveDate,
		&i.EndDate,
		&i.EmployeeAcknowledged,
		&i.AcknowledgedAt,
		&i.AppealStatus,
		&i.AppealReason,
		&i.AppealDate,
		&i.AppealResolvedAt,
		&i.AppealResolvedBy,
		&i.AppealResolution,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countDisciplinaryActions = `-- name: CountDisciplinaryActions :one
SELECT COUNT(*) FROM disciplinary_actions
WHERE company_id = $1
  AND ($2 = 0 OR employee_id = $2)
`

type CountDisciplinaryActionsParams struct {
	CompanyID  int64       `json:"company_id"`
	EmployeeID interface{} `json:"employee_id"`
}

func (q *Queries) CountDisciplinaryActions(ctx context.Context, arg CountDisciplinaryActionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDisciplinaryActions, arg.CompanyID, arg.EmployeeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDisciplinaryIncidents = `-- name: CountDisciplinaryIncidents :one
SELECT COUNT(*) FROM disciplinary_incidents
WHERE company_id = $1
  AND ($2 = '' OR status = $2)
  AND ($3 = 0 OR employee_id = $3)
`

type CountDisciplinaryIncidentsParams struct {
	CompanyID  int64       `json:"company_id"`
	Status     interface{} `json:"status"`
	EmployeeID interface{} `json:"employee_id"`
}

func (q *Queries) CountDisciplinaryIncidents(ctx context.Context, arg CountDisciplinaryIncidentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDisciplinaryIncidents, arg.CompanyID, arg.Status, arg.EmployeeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDisciplinaryAction = `-- name: CreateDisciplinaryAction :one
INSERT INTO disciplinary_actions (
    company_id, employee_id, incident_id, action_type,
    action_date, issued_by, description, suspension_days,
    effective_date, end_date, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, company_id, employee_id, incident_id, action_type, action_date, issued_by, description, suspension_days, effective_date, end_date, employee_acknowledged, acknowledged_at, appeal_status, appeal_reason, appeal_date, appeal_resolved_at, appeal_resolved_by, appeal_resolution, notes, created_at, updated_at
`

type CreateDisciplinaryActionParams struct {
	CompanyID      int64       `json:"company_id"`
	EmployeeID     int64       `json:"employee_id"`
	IncidentID     *int64      `json:"incident_id"`
	ActionType     string      `json:"action_type"`
	ActionDate     time.Time   `json:"action_date"`
	IssuedBy       int64       `json:"issued_by"`
	Description    string      `json:"description"`
	SuspensionDays *int32      `json:"suspension_days"`
	EffectiveDate  pgtype.Date `json:"effective_date"`
	EndDate        pgtype.Date `json:"end_date"`
	Notes          *string     `json:"notes"`
}

func (q *Queries) CreateDisciplinaryAction(ctx context.Context, arg CreateDisciplinaryActionParams) (DisciplinaryAction, error) {
	row := q.db.QueryRow(ctx, createDisciplinaryAction,
		arg.CompanyID,
		arg.EmployeeID,
		arg.IncidentID,
		arg.ActionType,
		arg.ActionDate,
		arg.IssuedBy,
		arg.Description,
		arg.SuspensionDays,
		arg.EffectiveDate,
		arg.EndDate,
		arg.Notes,
	)
	var i DisciplinaryAction
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.IncidentID,
		&i.ActionType,
		&i.ActionDate,
		&i.IssuedBy,
		&i.Description,
		&i.SuspensionDays,
		&i.EffectiveDate,
		&i.EndDate,
		&i.EmployeeAcknowledged,
		&i.AcknowledgedAt,
		&i.AppealStatus,
		&i.AppealReason,
		&i.AppealDate,
		&i.AppealResolvedAt,
		&i.AppealResolvedBy,
		&i.AppealResolution,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDisciplinaryIncident = `-- name: CreateDisciplinaryIncident :one
INSERT INTO disciplinary_incidents (
    company_id, employee_id, reported_by, incident_date,
    category, severity, description, witnesses, evidence_notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, employee_id, reported_by, incident_date, category, severity, description, witnesses, evidence_notes, status, resolution_notes, resolved_at, resolved_by, created_at, updated_at
`

type CreateDisciplinaryIncidentParams struct {
	CompanyID     int64     `json:"company_id"`
	EmployeeID    int64     `json:"employee_id"`
	ReportedBy    *int64    `json:"reported_by"`
	IncidentDate  time.Time `json:"incident_date"`
	Category      string    `json:"category"`
	Severity      string    `json:"severity"`
	Description   string    `json:"description"`
	Witnesses     *string   `json:"witnesses"`
	EvidenceNotes *string   `json:"evidence_notes"`
}

func (q *Queries) CreateDisciplinaryIncident(ctx context.Context, arg CreateDisciplinaryIncidentParams) (DisciplinaryIncident, error) {
	row := q.db.QueryRow(ctx, createDisciplinaryIncident,
		arg.CompanyID,
		arg.EmployeeID,
		arg.ReportedBy,
		arg.IncidentDate,
		arg.Category,
		arg.Severity,
		arg.Description,
		arg.Witnesses,
		arg.EvidenceNotes,
	)
	var i DisciplinaryIncident
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ReportedBy,
		&i.IncidentDate,
		&i.Category,
		&i.Severity,
		&i.Description,
		&i.Witnesses,
		&i.EvidenceNotes,
		&i.Status,
		&i.ResolutionNotes,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDisciplinaryIncident = `-- name: GetDisciplinaryIncident :one
SELECT di.id, di.company_id, di.employee_id, di.reported_by, di.incident_date, di.category, di.severity, di.description, di.witnesses, di.evidence_notes, di.status, di.resolution_notes, di.resolved_at, di.resolved_by, di.created_at, di.updated_at, e.employee_no, e.first_name, e.last_name,
       COALESCE(d.name, '') as department_name
FROM disciplinary_incidents di
JOIN employees e ON e.id = di.employee_id
LEFT JOIN departments d ON d.id = e.department_id
WHERE di.id = $1 AND di.company_id = $2
`

type GetDisciplinaryIncidentParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

type GetDisciplinaryIncidentRow struct {
	ID              int64              `json:"id"`
	CompanyID       int64              `json:"company_id"`
	EmployeeID      int64              `json:"employee_id"`
	ReportedBy      *int64             `json:"reported_by"`
	IncidentDate    time.Time          `json:"incident_date"`
	Category        string             `json:"category"`
	Severity        string             `json:"severity"`
	Description     string             `json:"description"`
	Witnesses       *string            `json:"witnesses"`
	EvidenceNotes   *string            `json:"evidence_notes"`
	Status          string             `json:"status"`
	ResolutionNotes *string            `json:"resolution_notes"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy      *int64             `json:"resolved_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	EmployeeNo      string             `json:"employee_no"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	DepartmentName  string             `json:"department_name"`
}

func (q *Queries) GetDisciplinaryIncident(ctx context.Context, arg GetDisciplinaryIncidentParams) (GetDisciplinaryIncidentRow, error) {
	row := q.db.QueryRow(ctx, getDisciplinaryIncident, arg.ID, arg.CompanyID)
	var i GetDisciplinaryIncidentRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ReportedBy,
		&i.IncidentDate,
		&i.Category,
		&i.Severity,
		&i.Description,
		&i.Witnesses,
		&i.EvidenceNotes,
		&i.Status,
		&i.ResolutionNotes,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.EmployeeNo,
		&i.FirstName,
		&i.LastName,
		&i.DepartmentName,
	)
	return i, err
}

const getEmployeeActionCounts = `-- name: GetEmployeeActionCounts :one
SELECT
    COUNT(*) as total_actions,
    COUNT(CASE WHEN da.action_type = 'verbal_warning' THEN 1 END) as verbal_warnings,
    COUNT(CASE WHEN da.action_type = 'written_warning' THEN 1 END) as written_warnings,
    COUNT(CASE WHEN da.action_type = 'final_warning' THEN 1 END) as final_warnings,
    COUNT(CASE WHEN da.action_type = 'suspension' THEN 1 END) as suspensions
FROM disciplinary_actions da
WHERE da.company_id = $1 AND da.employee_id = $2
`

type GetEmployeeActionCountsParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
}

type GetEmployeeActionCountsRow struct {
	TotalActions    int64 `json:"total_actions"`
	VerbalWarnings  int64 `json:"verbal_warnings"`
	WrittenWarnings int64 `json:"written_warnings"`
	FinalWarnings   int64 `json:"final_warnings"`
	Suspensions     int64 `json:"suspensions"`
}

func (q *Queries) GetEmployeeActionCounts(ctx context.Context, arg GetEmployeeActionCountsParams) (GetEmployeeActionCountsRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeActionCounts, arg.CompanyID, arg.EmployeeID)
	var i GetEmployeeActionCountsRow
	err := row.Scan(
		&i.TotalActions,
		&i.VerbalWarnings,
		&i.WrittenWarnings,
		&i.FinalWarnings,
		&i.Suspensions,
	)
	return i, err
}

const getEmployeeDisciplinarySummary = `-- name: GetEmployeeDisciplinarySummary :one
SELECT
    COUNT(*) as total_incidents,
    COUNT(CASE WHEN di.severity = 'grave' THEN 1 END) as grave_count,
    COUNT(CASE WHEN di.status = 'open' THEN 1 END) as open_count
FROM disciplinary_incidents di
WHERE di.company_id = $1 AND di.employee_id = $2
`

type GetEmployeeDisciplinarySummaryParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
}

type GetEmployeeDisciplinarySummaryRow struct {
	TotalIncidents int64 `json:"total_incidents"`
	GraveCount     int64 `json:"grave_count"`
	OpenCount      int64 `json:"open_count"`
}

func (q *Queries) GetEmployeeDisciplinarySummary(ctx context.Context, arg GetEmployeeDisciplinarySummaryParams) (GetEmployeeDisciplinarySummaryRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeDisciplinarySummary, arg.CompanyID, arg.EmployeeID)
	var i GetEmployeeDisciplinarySummaryRow
	err := row.Scan(&i.TotalIncidents, &i.GraveCount, &i.OpenCount)
	return i, err
}

const listActionsByIncident = `-- name: ListActionsByIncident :many
SELECT da.id, da.company_id, da.employee_id, da.incident_id, da.action_type, da.action_date, da.issued_by, da.description, da.suspension_days, da.effective_date, da.end_date, da.employee_acknowledged, da.acknowledged_at, da.appeal_status, da.appeal_reason, da.appeal_date, da.appeal_resolved_at, da.appeal_resolved_by, da.appeal_resolution, da.notes, da.created_at, da.updated_at, e.employee_no, e.first_name, e.last_name
FROM disciplinary_actions da
JOIN employees e ON e.id = da.employee_id
WHERE da.incident_id = $1 AND da.company_id = $2
ORDER BY da.action_date
`

type ListActionsByIncidentParams struct {
	IncidentID *int64 `json:"incident_id"`
	CompanyID  int64  `json:"company_id"`
}

type ListActionsByIncidentRow struct {
	ID                   int64              `json:"id"`
	CompanyID            int64              `json:"company_id"`
	EmployeeID           int64              `json:"employee_id"`
	IncidentID           *int64             `json:"incident_id"`
	ActionType           string             `json:"action_type"`
	ActionDate           time.Time          `json:"action_date"`
	IssuedBy             int64              `json:"issued_by"`
	Description          string             `json:"description"`
	SuspensionDays       *int32             `json:"suspension_days"`
	EffectiveDate        pgtype.Date        `json:"effective_date"`
	EndDate              pgtype.Date        `json:"end_date"`
	EmployeeAcknowledged *bool              `json:"employee_acknowledged"`
	AcknowledgedAt       pgtype.Timestamptz `json:"acknowledged_at"`
	AppealStatus         *string            `json:"appeal_status"`
	AppealReason         *string            `json:"appeal_reason"`
	AppealDate           pgtype.Timestamptz `json:"appeal_date"`
	AppealResolvedAt     pgtype.Timestamptz `json:"appeal_resolved_at"`
	AppealResolvedBy     *int64             `json:"appeal_resolved_by"`
	AppealResolution     *string            `json:"appeal_resolution"`
	Notes                *string            `json:"notes"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	EmployeeNo           string             `json:"employee_no"`
	FirstName            string             `json:"first_name"`
	LastName             string             `json:"last_name"`
}

func (q *Queries) ListActionsByIncident(ctx context.Context, arg ListActionsByIncidentParams) ([]ListActionsByIncidentRow, error) {
	rows, err := q.db.Query(ctx, listActionsByIncident, arg.IncidentID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActionsByIncidentRow{}
	for rows.Next() {
		var i ListActionsByIncidentRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.IncidentID,
			&i.ActionType,
			&i.ActionDate,
			&i.IssuedBy,
			&i.Description,
			&i.SuspensionDays,
			&i.EffectiveDate,
			&i.EndDate,
			&i.EmployeeAcknowledged,
			&i.AcknowledgedAt,
			&i.AppealStatus,
			&i.AppealReason,
			&i.AppealDate,
			&i.AppealResolvedAt,
			&i.AppealResolvedBy,
			&i.AppealResolution,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisciplinaryActions = `-- name: ListDisciplinaryActions :many
SELECT da.id, da.company_id, da.employee_id, da.incident_id, da.action_type, da.action_date, da.issued_by, da.description, da.suspension_days, da.effective_date, da.end_date, da.employee_acknowledged, da.acknowledged_at, da.appeal_status, da.appeal_reason, da.appeal_date, da.appeal_resolved_at, da.appeal_resolved_by, da.appeal_resolution, da.notes, da.created_at, da.updated_at, e.employee_no, e.first_name, e.last_name,
       COALESCE(d.name, '') as department_name
FROM disciplinary_actions da
JOIN employees e ON e.id = da.employee_id
LEFT JOIN departments d ON d.id = e.department_id
WHERE da.company_id = $1
  AND ($2 = 0 OR da.employee_id = $2)
ORDER BY da.action_date DESC
LIMIT $4 OFFSET $3
`

type ListDisciplinaryActionsParams struct {
	CompanyID  int64       `json:"company_id"`
	EmployeeID interface{} `json:"employee_id"`
	Off        int32       `json:"off"`
	Lim        int32       `json:"lim"`
}

type ListDisciplinaryActionsRow struct {
	ID                   int64              `json:"id"`
	CompanyID            int64              `json:"company_id"`
	EmployeeID           int64              `json:"employee_id"`
	IncidentID           *int64             `json:"incident_id"`
	ActionType           string             `json:"action_type"`
	ActionDate           time.Time          `json:"action_date"`
	IssuedBy             int64              `json:"issued_by"`
	Description          string             `json:"description"`
	SuspensionDays       *int32             `json:"suspension_days"`
	EffectiveDate        pgtype.Date        `json:"effective_date"`
	EndDate              pgtype.Date        `json:"end_date"`
	EmployeeAcknowledged *bool              `json:"employee_acknowledged"`
	AcknowledgedAt       pgtype.Timestamptz `json:"acknowledged_at"`
	AppealStatus         *string            `json:"appeal_status"`
	AppealReason         *string            `json:"appeal_reason"`
	AppealDate           pgtype.Timestamptz `json:"appeal_date"`
	AppealResolvedAt     pgtype.Timestamptz `json:"appeal_resolved_at"`
	AppealResolvedBy     *int64             `json:"appeal_resolved_by"`
	AppealResolution     *string            `json:"appeal_resolution"`
	Notes                *string            `json:"notes"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	EmployeeNo           string             `json:"employee_no"`
	FirstName            string             `json:"first_name"`
	LastName             string             `json:"last_name"`
	DepartmentName       string             `json:"department_name"`
}

func (q *Queries) ListDisciplinaryActions(ctx context.Context, arg ListDisciplinaryActionsParams) ([]ListDisciplinaryActionsRow, error) {
	rows, err := q.db.Query(ctx, listDisciplinaryActions,
		arg.CompanyID,
		arg.EmployeeID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisciplinaryActionsRow{}
	for rows.Next() {
		var i ListDisciplinaryActionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.IncidentID,
			&i.ActionType,
			&i.ActionDate,
			&i.IssuedBy,
			&i.Description,
			&i.SuspensionDays,
			&i.EffectiveDate,
			&i.EndDate,
			&i.EmployeeAcknowledged,
			&i.AcknowledgedAt,
			&i.AppealStatus,
			&i.AppealReason,
			&i.AppealDate,
			&i.AppealResolvedAt,
			&i.AppealResolvedBy,
			&i.AppealResolution,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDisciplinaryIncidents = `-- name: ListDisciplinaryIncidents :many
SELECT di.id, di.company_id, di.employee_id, di.reported_by, di.incident_date, di.category, di.severity, di.description, di.witnesses, di.evidence_notes, di.status, di.resolution_notes, di.resolved_at, di.resolved_by, di.created_at, di.updated_at, e.employee_no, e.first_name, e.last_name,
       COALESCE(d.name, '') as department_name
FROM disciplinary_incidents di
JOIN employees e ON e.id = di.employee_id
LEFT JOIN departments d ON d.id = e.department_id
WHERE di.company_id = $1
  AND ($2 = '' OR di.status = $2)
  AND ($3 = 0 OR di.employee_id = $3)
ORDER BY di.incident_date DESC
LIMIT $5 OFFSET $4
`

type ListDisciplinaryIncidentsParams struct {
	CompanyID  int64       `json:"company_id"`
	Status     interface{} `json:"status"`
	EmployeeID interface{} `json:"employee_id"`
	Off        int32       `json:"off"`
	Lim        int32       `json:"lim"`
}

type ListDisciplinaryIncidentsRow struct {
	ID              int64              `json:"id"`
	CompanyID       int64              `json:"company_id"`
	EmployeeID      int64              `json:"employee_id"`
	ReportedBy      *int64             `json:"reported_by"`
	IncidentDate    time.Time          `json:"incident_date"`
	Category        string             `json:"category"`
	Severity        string             `json:"severity"`
	Description     string             `json:"description"`
	Witnesses       *string            `json:"witnesses"`
	EvidenceNotes   *string            `json:"evidence_notes"`
	Status          string             `json:"status"`
	ResolutionNotes *string            `json:"resolution_notes"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	ResolvedBy      *int64             `json:"resolved_by"`
	CreatedAt       time.Time          `json:"created_at"`
	UpdatedAt       time.Time          `json:"updated_at"`
	EmployeeNo      string             `json:"employee_no"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	DepartmentName  string             `json:"department_name"`
}

func (q *Queries) ListDisciplinaryIncidents(ctx context.Context, arg ListDisciplinaryIncidentsParams) ([]ListDisciplinaryIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listDisciplinaryIncidents,
		arg.CompanyID,
		arg.Status,
		arg.EmployeeID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDisciplinaryIncidentsRow{}
	for rows.Next() {
		var i ListDisciplinaryIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.ReportedBy,
			&i.IncidentDate,
			&i.Category,
			&i.Severity,
			&i.Description,
			&i.Witnesses,
			&i.EvidenceNotes,
			&i.Status,
			&i.ResolutionNotes,
			&i.ResolvedAt,
			&i.ResolvedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAppeal = `-- name: ResolveAppeal :one
UPDATE disciplinary_actions SET
    appeal_status = $3,
    appeal_resolution = $4,
    appeal_resolved_at = NOW(),
    appeal_resolved_by = $5,
    updated_at = NOW()
WHERE id = $1 AND company_id = $2 AND appeal_status = 'appealed'
RETURNING id, company_id, employee_id, incident_id, action_type, action_date, issued_by, description, suspension_days, effective_date, end_date, employee_acknowledged, acknowledged_at, appeal_status, appeal_reason, appeal_date, appeal_resolved_at, appeal_resolved_by, appeal_resolution, notes, created_at, updated_at
`

type ResolveAppealParams struct {
	ID               int64   `json:"id"`
	CompanyID        int64   `json:"company_id"`
	AppealStatus     *string `json:"appeal_status"`
	AppealResolution *string `json:"appeal_resolution"`
	AppealResolvedBy *int64  `json:"appeal_resolved_by"`
}

func (q *Queries) ResolveAppeal(ctx context.Context, arg ResolveAppealParams) (DisciplinaryAction, error) {
	row := q.db.QueryRow(ctx, resolveAppeal,
		arg.ID,
		arg.CompanyID,
		arg.AppealStatus,
		arg.AppealResolution,
		arg.AppealResolvedBy,
	)
	var i DisciplinaryAction
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.IncidentID,
		&i.ActionType,
		&i.ActionDate,
		&i.IssuedBy,
		&i.Description,
		&i.SuspensionDays,
		&i.EffectiveDate,
		&i.EndDate,
		&i.EmployeeAcknowledged,
		&i.AcknowledgedAt,
		&i.AppealStatus,
		&i.AppealReason,
		&i.AppealDate,
		&i.AppealResolvedAt,
		&i.AppealResolvedBy,
		&i.AppealResolution,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncidentStatus = `-- name: UpdateIncidentStatus :one
UPDATE disciplinary_incidents SET
    status = $3,
    resolution_notes = $4,
    resolved_at = CASE WHEN $3 IN ('resolved', 'dismissed') THEN NOW() ELSE NULL END,
    resolved_by = $5,
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, employee_id, reported_by, incident_date, category, severity, description, witnesses, evidence_notes, status, resolution_notes, resolved_at, resolved_by, created_at, updated_at
`

type UpdateIncidentStatusParams struct {
	ID              int64   `json:"id"`
	CompanyID       int64   `json:"company_id"`
	Status          string  `json:"status"`
	ResolutionNotes *string `json:"resolution_notes"`
	ResolvedBy      *int64  `json:"resolved_by"`
}

func (q *Queries) UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) (DisciplinaryIncident, error) {
	row := q.db.QueryRow(ctx, updateIncidentStatus,
		arg.ID,
		arg.CompanyID,
		arg.Status,
		arg.ResolutionNotes,
		arg.ResolvedBy,
	)
	var i DisciplinaryIncident
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ReportedBy,
		&i.IncidentDate,
		&i.Category,
		&i.Severity,
		&i.Description,
		&i.Witnesses,
		&i.EvidenceNotes,
		&i.Status,
		&i.ResolutionNotes,
		&i.ResolvedAt,
		&i.ResolvedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
