// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDocumentCategory = `-- name: CreateDocumentCategory :one
INSERT INTO document_categories (company_id, name, slug, description, sort_order)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, name, slug, description, sort_order, is_system, created_at
`

type CreateDocumentCategoryParams struct {
	CompanyID   int64   `json:"company_id"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	SortOrder   int32   `json:"sort_order"`
}

func (q *Queries) CreateDocumentCategory(ctx context.Context, arg CreateDocumentCategoryParams) (DocumentCategory, error) {
	row := q.db.QueryRow(ctx, createDocumentCategory,
		arg.CompanyID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
	)
	var i DocumentCategory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.IsSystem,
		&i.CreatedAt,
	)
	return i, err
}

const createDocumentRequirement = `-- name: CreateDocumentRequirement :one
INSERT INTO document_requirements (company_id, category_id, document_name, is_required, applies_to, expiry_months)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, category_id, document_name, is_required, applies_to, expiry_months, created_at
`

type CreateDocumentRequirementParams struct {
	CompanyID    int64  `json:"company_id"`
	CategoryID   int64  `json:"category_id"`
	DocumentName string `json:"document_name"`
	IsRequired   bool   `json:"is_required"`
	AppliesTo    string `json:"applies_to"`
	ExpiryMonths *int32 `json:"expiry_months"`
}

func (q *Queries) CreateDocumentRequirement(ctx context.Context, arg CreateDocumentRequirementParams) (DocumentRequirement, error) {
	row := q.db.QueryRow(ctx, createDocumentRequirement,
		arg.CompanyID,
		arg.CategoryID,
		arg.DocumentName,
		arg.IsRequired,
		arg.AppliesTo,
		arg.ExpiryMonths,
	)
	var i DocumentRequirement
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CategoryID,
		&i.DocumentName,
		&i.IsRequired,
		&i.AppliesTo,
		&i.ExpiryMonths,
		&i.CreatedAt,
	)
	return i, err
}

const delete201Document = `-- name: Delete201Document :exec
DELETE FROM employee_documents WHERE id = $1 AND company_id = $2
`

type Delete201DocumentParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID int64     `json:"company_id"`
}

func (q *Queries) Delete201Document(ctx context.Context, arg Delete201DocumentParams) error {
	_, err := q.db.Exec(ctx, delete201Document, arg.ID, arg.CompanyID)
	return err
}

const deleteDocumentRequirement = `-- name: DeleteDocumentRequirement :exec
DELETE FROM document_requirements WHERE id = $1 AND company_id = $2
`

type DeleteDocumentRequirementParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) DeleteDocumentRequirement(ctx context.Context, arg DeleteDocumentRequirementParams) error {
	_, err := q.db.Exec(ctx, deleteDocumentRequirement, arg.ID, arg.CompanyID)
	return err
}

const ensureDefaultCategories = `-- name: EnsureDefaultCategories :exec
INSERT INTO document_categories (company_id, name, slug, description, sort_order, is_system)
VALUES
    ($1, 'Hiring & Pre-Employment', 'hiring', 'Application, resume, NBI clearance, medical results, SSS/TIN/PhilHealth/Pag-IBIG', 1, true),
    ($1, 'Personal Information', 'personal', 'Birth certificate, marriage certificate, IDs, emergency contacts', 2, true),
    ($1, 'Employment Contracts', 'contracts', 'Job offer, employment contract, amendments, regularization', 3, true),
    ($1, 'Compensation & Benefits', 'compensation', 'Salary records, benefits enrollment, loan documents', 4, true),
    ($1, 'Performance', 'performance', 'Performance reviews, KPIs, commendations', 5, true),
    ($1, 'Training & Development', 'training', 'Training certificates, seminars, continuing education', 6, true),
    ($1, 'Disciplinary', 'disciplinary', 'Incident reports, NTEs, disciplinary actions', 7, true),
    ($1, 'Medical', 'medical', 'Medical certificates, annual physical exam, drug test results', 8, true),
    ($1, 'Government Compliance', 'compliance', 'SSS, PhilHealth, Pag-IBIG, BIR forms', 9, true),
    ($1, 'Separation', 'separation', 'Resignation letter, clearance, certificate of employment, final pay', 10, true)
ON CONFLICT (company_id, slug) DO NOTHING
`

func (q *Queries) EnsureDefaultCategories(ctx context.Context, companyID int64) error {
	_, err := q.db.Exec(ctx, ensureDefaultCategories, companyID)
	return err
}

const get201Document = `-- name: Get201Document :one
SELECT ed.id, ed.company_id, ed.employee_id, ed.doc_type, ed.file_name, ed.file_path, ed.file_size, ed.mime_type, ed.file_hash, ed.uploaded_by, ed.verified_at, ed.verified_by, ed.notes, ed.created_at, ed.expiry_date, ed.category_id, ed.title, ed.version, ed.is_required, ed.status, ed.updated_at, dc.name as category_name, dc.slug as category_slug
FROM employee_documents ed
LEFT JOIN document_categories dc ON dc.id = ed.category_id
WHERE ed.id = $1 AND ed.company_id = $2
`

type Get201DocumentParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID int64     `json:"company_id"`
}

type Get201DocumentRow struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    int64              `json:"company_id"`
	EmployeeID   int64              `json:"employee_id"`
	DocType      string             `json:"doc_type"`
	FileName     string             `json:"file_name"`
	FilePath     string             `json:"file_path"`
	FileSize     int64              `json:"file_size"`
	MimeType     *string            `json:"mime_type"`
	FileHash     *string            `json:"file_hash"`
	UploadedBy   *int64             `json:"uploaded_by"`
	VerifiedAt   pgtype.Timestamptz `json:"verified_at"`
	VerifiedBy   *int64             `json:"verified_by"`
	Notes        *string            `json:"notes"`
	CreatedAt    time.Time          `json:"created_at"`
	ExpiryDate   pgtype.Date        `json:"expiry_date"`
	CategoryID   *int64             `json:"category_id"`
	Title        *string            `json:"title"`
	Version      int32              `json:"version"`
	IsRequired   bool               `json:"is_required"`
	Status       string             `json:"status"`
	UpdatedAt    time.Time          `json:"updated_at"`
	CategoryName *string            `json:"category_name"`
	CategorySlug *string            `json:"category_slug"`
}

func (q *Queries) Get201Document(ctx context.Context, arg Get201DocumentParams) (Get201DocumentRow, error) {
	row := q.db.QueryRow(ctx, get201Document, arg.ID, arg.CompanyID)
	var i Get201DocumentRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.DocType,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.FileHash,
		&i.UploadedBy,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.ExpiryDate,
		&i.CategoryID,
		&i.Title,
		&i.Version,
		&i.IsRequired,
		&i.Status,
		&i.UpdatedAt,
		&i.CategoryName,
		&i.CategorySlug,
	)
	return i, err
}

const getComplianceChecklist = `-- name: GetComplianceChecklist :many
SELECT dr.id as requirement_id, dr.document_name, dr.is_required, dc.name as category_name,
       CASE WHEN ed.id IS NOT NULL THEN true ELSE false END as is_fulfilled,
       ed.id as document_id, ed.expiry_date, ed.status as document_status
FROM document_requirements dr
JOIN document_categories dc ON dc.id = dr.category_id
LEFT JOIN employee_documents ed ON ed.company_id = dr.company_id
    AND ed.employee_id = $2
    AND ed.category_id = dr.category_id
    AND COALESCE(ed.title, ed.doc_type) = dr.document_name
    AND ed.status = 'active'
WHERE dr.company_id = $1
ORDER BY dc.sort_order, dr.document_name
`

type GetComplianceChecklistParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
}

type GetComplianceChecklistRow struct {
	RequirementID  int64       `json:"requirement_id"`
	DocumentName   string      `json:"document_name"`
	IsRequired     bool        `json:"is_required"`
	CategoryName   string      `json:"category_name"`
	IsFulfilled    bool        `json:"is_fulfilled"`
	DocumentID     pgtype.UUID `json:"document_id"`
	ExpiryDate     pgtype.Date `json:"expiry_date"`
	DocumentStatus *string     `json:"document_status"`
}

func (q *Queries) GetComplianceChecklist(ctx context.Context, arg GetComplianceChecklistParams) ([]GetComplianceChecklistRow, error) {
	rows, err := q.db.Query(ctx, getComplianceChecklist, arg.CompanyID, arg.EmployeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetComplianceChecklistRow{}
	for rows.Next() {
		var i GetComplianceChecklistRow
		if err := rows.Scan(
			&i.RequirementID,
			&i.DocumentName,
			&i.IsRequired,
			&i.CategoryName,
			&i.IsFulfilled,
			&i.DocumentID,
			&i.ExpiryDate,
			&i.DocumentStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployee201Stats = `-- name: GetEmployee201Stats :one
SELECT
    COUNT(*) as total_documents,
    COUNT(*) FILTER (WHERE status = 'active') as active_documents,
    COUNT(*) FILTER (WHERE status = 'expired') as expired_documents,
    COUNT(*) FILTER (WHERE expiry_date IS NOT NULL AND expiry_date <= CURRENT_DATE + INTERVAL '30 days' AND status = 'active') as expiring_soon
FROM employee_documents
WHERE company_id = $1 AND employee_id = $2
`

type GetEmployee201StatsParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
}

type GetEmployee201StatsRow struct {
	TotalDocuments   int64 `json:"total_documents"`
	ActiveDocuments  int64 `json:"active_documents"`
	ExpiredDocuments int64 `json:"expired_documents"`
	ExpiringSoon     int64 `json:"expiring_soon"`
}

func (q *Queries) GetEmployee201Stats(ctx context.Context, arg GetEmployee201StatsParams) (GetEmployee201StatsRow, error) {
	row := q.db.QueryRow(ctx, getEmployee201Stats, arg.CompanyID, arg.EmployeeID)
	var i GetEmployee201StatsRow
	err := row.Scan(
		&i.TotalDocuments,
		&i.ActiveDocuments,
		&i.ExpiredDocuments,
		&i.ExpiringSoon,
	)
	return i, err
}

const list201Documents = `-- name: List201Documents :many
SELECT ed.id, ed.company_id, ed.employee_id, ed.doc_type, ed.file_name, ed.file_path, ed.file_size, ed.mime_type, ed.file_hash, ed.uploaded_by, ed.verified_at, ed.verified_by, ed.notes, ed.created_at, ed.expiry_date, ed.category_id, ed.title, ed.version, ed.is_required, ed.status, ed.updated_at, dc.name as category_name, dc.slug as category_slug
FROM employee_documents ed
LEFT JOIN document_categories dc ON dc.id = ed.category_id
WHERE ed.company_id = $1
  AND ed.employee_id = $2
  AND ($3 = 0 OR ed.category_id = $3)
  AND ($4 = '' OR ed.status = $4)
ORDER BY dc.sort_order, ed.created_at DESC
`

type List201DocumentsParams struct {
	CompanyID  int64       `json:"company_id"`
	EmployeeID int64       `json:"employee_id"`
	CategoryID interface{} `json:"category_id"`
	Status     interface{} `json:"status"`
}

type List201DocumentsRow struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    int64              `json:"company_id"`
	EmployeeID   int64              `json:"employee_id"`
	DocType      string             `json:"doc_type"`
	FileName     string             `json:"file_name"`
	FilePath     string             `json:"file_path"`
	FileSize     int64              `json:"file_size"`
	MimeType     *string            `json:"mime_type"`
	FileHash     *string            `json:"file_hash"`
	UploadedBy   *int64             `json:"uploaded_by"`
	VerifiedAt   pgtype.Timestamptz `json:"verified_at"`
	VerifiedBy   *int64             `json:"verified_by"`
	Notes        *string            `json:"notes"`
	CreatedAt    time.Time          `json:"created_at"`
	ExpiryDate   pgtype.Date        `json:"expiry_date"`
	CategoryID   *int64             `json:"category_id"`
	Title        *string            `json:"title"`
	Version      int32              `json:"version"`
	IsRequired   bool               `json:"is_required"`
	Status       string             `json:"status"`
	UpdatedAt    time.Time          `json:"updated_at"`
	CategoryName *string            `json:"category_name"`
	CategorySlug *string            `json:"category_slug"`
}

func (q *Queries) List201Documents(ctx context.Context, arg List201DocumentsParams) ([]List201DocumentsRow, error) {
	rows, err := q.db.Query(ctx, list201Documents,
		arg.CompanyID,
		arg.EmployeeID,
		arg.CategoryID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List201DocumentsRow{}
	for rows.Next() {
		var i List201DocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.DocType,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.FileHash,
			&i.UploadedBy,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.ExpiryDate,
			&i.CategoryID,
			&i.Title,
			&i.Version,
			&i.IsRequired,
			&i.Status,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const list201ExpiringDocuments = `-- name: List201ExpiringDocuments :many
SELECT ed.id, ed.company_id, ed.employee_id, ed.doc_type, ed.file_name, ed.file_path, ed.file_size, ed.mime_type, ed.file_hash, ed.uploaded_by, ed.verified_at, ed.verified_by, ed.notes, ed.created_at, ed.expiry_date, ed.category_id, ed.title, ed.version, ed.is_required, ed.status, ed.updated_at, dc.name as category_name,
       e.employee_no, e.first_name, e.last_name
FROM employee_documents ed
LEFT JOIN document_categories dc ON dc.id = ed.category_id
JOIN employees e ON e.id = ed.employee_id
WHERE ed.company_id = $1
  AND ed.status = 'active'
  AND ed.expiry_date IS NOT NULL
  AND ed.expiry_date <= CURRENT_DATE + INTERVAL '30 days'
ORDER BY ed.expiry_date
`

type List201ExpiringDocumentsRow struct {
	ID           uuid.UUID          `json:"id"`
	CompanyID    int64              `json:"company_id"`
	EmployeeID   int64              `json:"employee_id"`
	DocType      string             `json:"doc_type"`
	FileName     string             `json:"file_name"`
	FilePath     string             `json:"file_path"`
	FileSize     int64              `json:"file_size"`
	MimeType     *string            `json:"mime_type"`
	FileHash     *string            `json:"file_hash"`
	UploadedBy   *int64             `json:"uploaded_by"`
	VerifiedAt   pgtype.Timestamptz `json:"verified_at"`
	VerifiedBy   *int64             `json:"verified_by"`
	Notes        *string            `json:"notes"`
	CreatedAt    time.Time          `json:"created_at"`
	ExpiryDate   pgtype.Date        `json:"expiry_date"`
	CategoryID   *int64             `json:"category_id"`
	Title        *string            `json:"title"`
	Version      int32              `json:"version"`
	IsRequired   bool               `json:"is_required"`
	Status       string             `json:"status"`
	UpdatedAt    time.Time          `json:"updated_at"`
	CategoryName *string            `json:"category_name"`
	EmployeeNo   string             `json:"employee_no"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
}

func (q *Queries) List201ExpiringDocuments(ctx context.Context, companyID int64) ([]List201ExpiringDocumentsRow, error) {
	rows, err := q.db.Query(ctx, list201ExpiringDocuments, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []List201ExpiringDocumentsRow{}
	for rows.Next() {
		var i List201ExpiringDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.DocType,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.FileHash,
			&i.UploadedBy,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.ExpiryDate,
			&i.CategoryID,
			&i.Title,
			&i.Version,
			&i.IsRequired,
			&i.Status,
			&i.UpdatedAt,
			&i.CategoryName,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentCategories = `-- name: ListDocumentCategories :many
SELECT id, company_id, name, slug, description, sort_order, is_system, created_at FROM document_categories
WHERE company_id = $1
ORDER BY sort_order, name
`

func (q *Queries) ListDocumentCategories(ctx context.Context, companyID int64) ([]DocumentCategory, error) {
	rows, err := q.db.Query(ctx, listDocumentCategories, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DocumentCategory{}
	for rows.Next() {
		var i DocumentCategory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.SortOrder,
			&i.IsSystem,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentRequirements = `-- name: ListDocumentRequirements :many
SELECT dr.id, dr.company_id, dr.category_id, dr.document_name, dr.is_required, dr.applies_to, dr.expiry_months, dr.created_at, dc.name as category_name
FROM document_requirements dr
JOIN document_categories dc ON dc.id = dr.category_id
WHERE dr.company_id = $1
ORDER BY dc.sort_order, dr.document_name
`

type ListDocumentRequirementsRow struct {
	ID           int64     `json:"id"`
	CompanyID    int64     `json:"company_id"`
	CategoryID   int64     `json:"category_id"`
	DocumentName string    `json:"document_name"`
	IsRequired   bool      `json:"is_required"`
	AppliesTo    string    `json:"applies_to"`
	ExpiryMonths *int32    `json:"expiry_months"`
	CreatedAt    time.Time `json:"created_at"`
	CategoryName string    `json:"category_name"`
}

func (q *Queries) ListDocumentRequirements(ctx context.Context, companyID int64) ([]ListDocumentRequirementsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentRequirements, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDocumentRequirementsRow{}
	for rows.Next() {
		var i ListDocumentRequirementsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CategoryID,
			&i.DocumentName,
			&i.IsRequired,
			&i.AppliesTo,
			&i.ExpiryMonths,
			&i.CreatedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExpiredDocuments = `-- name: MarkExpiredDocuments :exec
UPDATE employee_documents SET
    status = 'expired',
    updated_at = NOW()
WHERE status = 'active'
  AND expiry_date IS NOT NULL
  AND expiry_date < CURRENT_DATE
`

func (q *Queries) MarkExpiredDocuments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markExpiredDocuments)
	return err
}

const update201Document = `-- name: Update201Document :one
UPDATE employee_documents SET
    title = COALESCE($3, title),
    category_id = $4,
    expiry_date = $5,
    notes = $6,
    status = COALESCE($7, status),
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, employee_id, doc_type, file_name, file_path, file_size, mime_type, file_hash, uploaded_by, verified_at, verified_by, notes, created_at, expiry_date, category_id, title, version, is_required, status, updated_at
`

type Update201DocumentParams struct {
	ID         uuid.UUID   `json:"id"`
	CompanyID  int64       `json:"company_id"`
	Title      *string     `json:"title"`
	CategoryID *int64      `json:"category_id"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
	Notes      *string     `json:"notes"`
	Status     string      `json:"status"`
}

func (q *Queries) Update201Document(ctx context.Context, arg Update201DocumentParams) (EmployeeDocument, error) {
	row := q.db.QueryRow(ctx, update201Document,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.CategoryID,
		arg.ExpiryDate,
		arg.Notes,
		arg.Status,
	)
	var i EmployeeDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.DocType,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.FileHash,
		&i.UploadedBy,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.ExpiryDate,
		&i.CategoryID,
		&i.Title,
		&i.Version,
		&i.IsRequired,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const upload201Document = `-- name: Upload201Document :one
INSERT INTO employee_documents (
    company_id, employee_id, category_id, title, doc_type,
    file_name, file_path, file_size, mime_type, version,
    expiry_date, is_required, uploaded_by, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, company_id, employee_id, doc_type, file_name, file_path, file_size, mime_type, file_hash, uploaded_by, verified_at, verified_by, notes, created_at, expiry_date, category_id, title, version, is_required, status, updated_at
`

type Upload201DocumentParams struct {
	CompanyID  int64       `json:"company_id"`
	EmployeeID int64       `json:"employee_id"`
	CategoryID *int64      `json:"category_id"`
	Title      *string     `json:"title"`
	DocType    string      `json:"doc_type"`
	FileName   string      `json:"file_name"`
	FilePath   string      `json:"file_path"`
	FileSize   int64       `json:"file_size"`
	MimeType   *string     `json:"mime_type"`
	Version    int32       `json:"version"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
	IsRequired bool        `json:"is_required"`
	UploadedBy *int64      `json:"uploaded_by"`
	Notes      *string     `json:"notes"`
}

func (q *Queries) Upload201Document(ctx context.Context, arg Upload201DocumentParams) (EmployeeDocument, error) {
	row := q.db.QueryRow(ctx, upload201Document,
		arg.CompanyID,
		arg.EmployeeID,
		arg.CategoryID,
		arg.Title,
		arg.DocType,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
		arg.Version,
		arg.ExpiryDate,
		arg.IsRequired,
		arg.UploadedBy,
		arg.Notes,
	)
	var i EmployeeDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.DocType,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.FileHash,
		&i.UploadedBy,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.ExpiryDate,
		&i.CategoryID,
		&i.Title,
		&i.Version,
		&i.IsRequired,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}
