// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employee.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEmployees = `-- name: CountEmployees :one
SELECT COUNT(*) FROM employees
WHERE company_id = $1
  AND ($2::varchar IS NULL OR $2 = '' OR status = $2)
  AND ($3::bigint IS NULL OR $3 = 0 OR department_id = $3)
`

type CountEmployeesParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Column3   int64  `json:"column_3"`
}

func (q *Queries) CountEmployees(ctx context.Context, arg CountEmployeesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees, arg.CompanyID, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (
    company_id, employee_no, first_name, last_name, middle_name, suffix,
    display_name, email, phone, birth_date, gender, civil_status,
    nationality, department_id, position_id, cost_center_id, manager_id,
    hire_date, employment_type, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12,
    $13, $14, $15, $16, $17, $18, $19, 'active'
) RETURNING id, company_id, user_id, employee_no, first_name, last_name, middle_name, suffix, display_name, email, phone, birth_date, gender, civil_status, nationality, department_id, position_id, cost_center_id, manager_id, hire_date, regularization_date, separation_date, employment_type, status, created_at, updated_at, contract_end_date
`

type CreateEmployeeParams struct {
	CompanyID      int64       `json:"company_id"`
	EmployeeNo     string      `json:"employee_no"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	MiddleName     *string     `json:"middle_name"`
	Suffix         *string     `json:"suffix"`
	DisplayName    *string     `json:"display_name"`
	Email          *string     `json:"email"`
	Phone          *string     `json:"phone"`
	BirthDate      pgtype.Date `json:"birth_date"`
	Gender         *string     `json:"gender"`
	CivilStatus    *string     `json:"civil_status"`
	Nationality    *string     `json:"nationality"`
	DepartmentID   *int64      `json:"department_id"`
	PositionID     *int64      `json:"position_id"`
	CostCenterID   *int64      `json:"cost_center_id"`
	ManagerID      *int64      `json:"manager_id"`
	HireDate       time.Time   `json:"hire_date"`
	EmploymentType string      `json:"employment_type"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.CompanyID,
		arg.EmployeeNo,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.Suffix,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.BirthDate,
		arg.Gender,
		arg.CivilStatus,
		arg.Nationality,
		arg.DepartmentID,
		arg.PositionID,
		arg.CostCenterID,
		arg.ManagerID,
		arg.HireDate,
		arg.EmploymentType,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.EmployeeNo,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Suffix,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.BirthDate,
		&i.Gender,
		&i.CivilStatus,
		&i.Nationality,
		&i.DepartmentID,
		&i.PositionID,
		&i.CostCenterID,
		&i.ManagerID,
		&i.HireDate,
		&i.RegularizationDate,
		&i.SeparationDate,
		&i.EmploymentType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractEndDate,
	)
	return i, err
}

const createEmployeeDocument = `-- name: CreateEmployeeDocument :one
INSERT INTO employee_documents (
    company_id, employee_id, doc_type, file_name, file_path,
    file_size, mime_type, file_hash, uploaded_by, expiry_date
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, employee_id, doc_type, file_name, file_path, file_size, mime_type, file_hash, uploaded_by, verified_at, verified_by, notes, created_at, expiry_date, category_id, title, version, is_required, status, updated_at
`

type CreateEmployeeDocumentParams struct {
	CompanyID  int64       `json:"company_id"`
	EmployeeID int64       `json:"employee_id"`
	DocType    string      `json:"doc_type"`
	FileName   string      `json:"file_name"`
	FilePath   string      `json:"file_path"`
	FileSize   int64       `json:"file_size"`
	MimeType   *string     `json:"mime_type"`
	FileHash   *string     `json:"file_hash"`
	UploadedBy *int64      `json:"uploaded_by"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
}

func (q *Queries) CreateEmployeeDocument(ctx context.Context, arg CreateEmployeeDocumentParams) (EmployeeDocument, error) {
	row := q.db.QueryRow(ctx, createEmployeeDocument,
		arg.CompanyID,
		arg.EmployeeID,
		arg.DocType,
		arg.FileName,
		arg.FilePath,
		arg.FileSize,
		arg.MimeType,
		arg.FileHash,
		arg.UploadedBy,
		arg.ExpiryDate,
	)
	var i EmployeeDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.DocType,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.FileHash,
		&i.UploadedBy,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.ExpiryDate,
		&i.CategoryID,
		&i.Title,
		&i.Version,
		&i.IsRequired,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const createEmploymentHistory = `-- name: CreateEmploymentHistory :one
INSERT INTO employment_history (
    company_id, employee_id, action_type, effective_date,
    from_department_id, to_department_id, from_position_id, to_position_id,
    remarks, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, employee_id, action_type, effective_date, from_department_id, to_department_id, from_position_id, to_position_id, remarks, created_by, created_at
`

type CreateEmploymentHistoryParams struct {
	CompanyID        int64     `json:"company_id"`
	EmployeeID       int64     `json:"employee_id"`
	ActionType       string    `json:"action_type"`
	EffectiveDate    time.Time `json:"effective_date"`
	FromDepartmentID *int64    `json:"from_department_id"`
	ToDepartmentID   *int64    `json:"to_department_id"`
	FromPositionID   *int64    `json:"from_position_id"`
	ToPositionID     *int64    `json:"to_position_id"`
	Remarks          *string   `json:"remarks"`
	CreatedBy        *int64    `json:"created_by"`
}

func (q *Queries) CreateEmploymentHistory(ctx context.Context, arg CreateEmploymentHistoryParams) (EmploymentHistory, error) {
	row := q.db.QueryRow(ctx, createEmploymentHistory,
		arg.CompanyID,
		arg.EmployeeID,
		arg.ActionType,
		arg.EffectiveDate,
		arg.FromDepartmentID,
		arg.ToDepartmentID,
		arg.FromPositionID,
		arg.ToPositionID,
		arg.Remarks,
		arg.CreatedBy,
	)
	var i EmploymentHistory
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ActionType,
		&i.EffectiveDate,
		&i.FromDepartmentID,
		&i.ToDepartmentID,
		&i.FromPositionID,
		&i.ToPositionID,
		&i.Remarks,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmployeeDocument = `-- name: DeleteEmployeeDocument :exec
DELETE FROM employee_documents WHERE id = $1 AND company_id = $2
`

type DeleteEmployeeDocumentParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID int64     `json:"company_id"`
}

func (q *Queries) DeleteEmployeeDocument(ctx context.Context, arg DeleteEmployeeDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteEmployeeDocument, arg.ID, arg.CompanyID)
	return err
}

const exportEmployeesCSV = `-- name: ExportEmployeesCSV :many
SELECT e.employee_no, e.first_name, e.last_name,
       COALESCE(e.middle_name, '') as middle_name,
       COALESCE(e.email, '') as email,
       COALESCE(e.phone, '') as phone,
       COALESCE(e.gender, '') as gender,
       e.birth_date, e.hire_date,
       e.employment_type, e.status,
       COALESCE(d.name, '') as department_name,
       COALESCE(p.title, '') as position_title
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
WHERE e.company_id = $1
ORDER BY e.last_name, e.first_name
`

type ExportEmployeesCSVRow struct {
	EmployeeNo     string      `json:"employee_no"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	MiddleName     string      `json:"middle_name"`
	Email          string      `json:"email"`
	Phone          string      `json:"phone"`
	Gender         string      `json:"gender"`
	BirthDate      pgtype.Date `json:"birth_date"`
	HireDate       time.Time   `json:"hire_date"`
	EmploymentType string      `json:"employment_type"`
	Status         string      `json:"status"`
	DepartmentName string      `json:"department_name"`
	PositionTitle  string      `json:"position_title"`
}

func (q *Queries) ExportEmployeesCSV(ctx context.Context, companyID int64) ([]ExportEmployeesCSVRow, error) {
	rows, err := q.db.Query(ctx, exportEmployeesCSV, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportEmployeesCSVRow{}
	for rows.Next() {
		var i ExportEmployeesCSVRow
		if err := rows.Scan(
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Email,
			&i.Phone,
			&i.Gender,
			&i.BirthDate,
			&i.HireDate,
			&i.EmploymentType,
			&i.Status,
			&i.DepartmentName,
			&i.PositionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeByID = `-- name: GetEmployeeByID :one
SELECT id, company_id, user_id, employee_no, first_name, last_name, middle_name, suffix, display_name, email, phone, birth_date, gender, civil_status, nationality, department_id, position_id, cost_center_id, manager_id, hire_date, regularization_date, separation_date, employment_type, status, created_at, updated_at, contract_end_date FROM employees WHERE id = $1 AND company_id = $2
`

type GetEmployeeByIDParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetEmployeeByID(ctx context.Context, arg GetEmployeeByIDParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByID, arg.ID, arg.CompanyID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.EmployeeNo,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Suffix,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.BirthDate,
		&i.Gender,
		&i.CivilStatus,
		&i.Nationality,
		&i.DepartmentID,
		&i.PositionID,
		&i.CostCenterID,
		&i.ManagerID,
		&i.HireDate,
		&i.RegularizationDate,
		&i.SeparationDate,
		&i.EmploymentType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractEndDate,
	)
	return i, err
}

const getEmployeeByNo = `-- name: GetEmployeeByNo :one
SELECT id, company_id, user_id, employee_no, first_name, last_name, middle_name, suffix, display_name, email, phone, birth_date, gender, civil_status, nationality, department_id, position_id, cost_center_id, manager_id, hire_date, regularization_date, separation_date, employment_type, status, created_at, updated_at, contract_end_date FROM employees WHERE employee_no = $1 AND company_id = $2
`

type GetEmployeeByNoParams struct {
	EmployeeNo string `json:"employee_no"`
	CompanyID  int64  `json:"company_id"`
}

func (q *Queries) GetEmployeeByNo(ctx context.Context, arg GetEmployeeByNoParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByNo, arg.EmployeeNo, arg.CompanyID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.EmployeeNo,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Suffix,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.BirthDate,
		&i.Gender,
		&i.CivilStatus,
		&i.Nationality,
		&i.DepartmentID,
		&i.PositionID,
		&i.CostCenterID,
		&i.ManagerID,
		&i.HireDate,
		&i.RegularizationDate,
		&i.SeparationDate,
		&i.EmploymentType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractEndDate,
	)
	return i, err
}

const getEmployeeByUserID = `-- name: GetEmployeeByUserID :one
SELECT id, company_id, user_id, employee_no, first_name, last_name, middle_name, suffix, display_name, email, phone, birth_date, gender, civil_status, nationality, department_id, position_id, cost_center_id, manager_id, hire_date, regularization_date, separation_date, employment_type, status, created_at, updated_at, contract_end_date FROM employees WHERE user_id = $1 AND company_id = $2 LIMIT 1
`

type GetEmployeeByUserIDParams struct {
	UserID    *int64 `json:"user_id"`
	CompanyID int64  `json:"company_id"`
}

func (q *Queries) GetEmployeeByUserID(ctx context.Context, arg GetEmployeeByUserIDParams) (Employee, error) {
	row := q.db.QueryRow(ctx, getEmployeeByUserID, arg.UserID, arg.CompanyID)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.EmployeeNo,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Suffix,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.BirthDate,
		&i.Gender,
		&i.CivilStatus,
		&i.Nationality,
		&i.DepartmentID,
		&i.PositionID,
		&i.CostCenterID,
		&i.ManagerID,
		&i.HireDate,
		&i.RegularizationDate,
		&i.SeparationDate,
		&i.EmploymentType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractEndDate,
	)
	return i, err
}

const getEmployeeDocument = `-- name: GetEmployeeDocument :one
SELECT id, company_id, employee_id, doc_type, file_name, file_path, file_size, mime_type, file_hash, uploaded_by, verified_at, verified_by, notes, created_at, expiry_date, category_id, title, version, is_required, status, updated_at FROM employee_documents WHERE id = $1 AND company_id = $2
`

type GetEmployeeDocumentParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID int64     `json:"company_id"`
}

func (q *Queries) GetEmployeeDocument(ctx context.Context, arg GetEmployeeDocumentParams) (EmployeeDocument, error) {
	row := q.db.QueryRow(ctx, getEmployeeDocument, arg.ID, arg.CompanyID)
	var i EmployeeDocument
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.DocType,
		&i.FileName,
		&i.FilePath,
		&i.FileSize,
		&i.MimeType,
		&i.FileHash,
		&i.UploadedBy,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.Notes,
		&i.CreatedAt,
		&i.ExpiryDate,
		&i.CategoryID,
		&i.Title,
		&i.Version,
		&i.IsRequired,
		&i.Status,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeForCOE = `-- name: GetEmployeeForCOE :one
SELECT e.id, e.employee_no, e.first_name, e.last_name, e.middle_name,
       e.hire_date, e.employment_type, e.status,
       COALESCE(d.name, '') as department_name,
       COALESCE(p.title, '') as position_title
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
WHERE e.id = $1 AND e.company_id = $2
`

type GetEmployeeForCOEParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

type GetEmployeeForCOERow struct {
	ID             int64     `json:"id"`
	EmployeeNo     string    `json:"employee_no"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	MiddleName     *string   `json:"middle_name"`
	HireDate       time.Time `json:"hire_date"`
	EmploymentType string    `json:"employment_type"`
	Status         string    `json:"status"`
	DepartmentName string    `json:"department_name"`
	PositionTitle  string    `json:"position_title"`
}

func (q *Queries) GetEmployeeForCOE(ctx context.Context, arg GetEmployeeForCOEParams) (GetEmployeeForCOERow, error) {
	row := q.db.QueryRow(ctx, getEmployeeForCOE, arg.ID, arg.CompanyID)
	var i GetEmployeeForCOERow
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.HireDate,
		&i.EmploymentType,
		&i.Status,
		&i.DepartmentName,
		&i.PositionTitle,
	)
	return i, err
}

const getEmployeeProfile = `-- name: GetEmployeeProfile :one
SELECT ep.employee_id, ep.address_line1, ep.address_line2, ep.city, ep.province, ep.zip_code, ep.emergency_name, ep.emergency_phone, ep.emergency_relation, ep.bank_name, ep.bank_account_no, ep.bank_account_name, ep.tin, ep.sss_no, ep.philhealth_no, ep.pagibig_no, ep.blood_type, ep.religion, ep.updated_at, ep.ssn_encrypted, ep.state_of_residence, ep.w4_filing_status, ep.w4_additional_withholding, ep.w4_multiple_jobs, ep.w4_dependents_credit, ep.w4_other_income, ep.w4_deductions, ep.state_allowances FROM employee_profiles ep
JOIN employees e ON e.id = ep.employee_id
WHERE ep.employee_id = $1 AND e.company_id = $2
`

type GetEmployeeProfileParams struct {
	EmployeeID int64 `json:"employee_id"`
	CompanyID  int64 `json:"company_id"`
}

func (q *Queries) GetEmployeeProfile(ctx context.Context, arg GetEmployeeProfileParams) (EmployeeProfile, error) {
	row := q.db.QueryRow(ctx, getEmployeeProfile, arg.EmployeeID, arg.CompanyID)
	var i EmployeeProfile
	err := row.Scan(
		&i.EmployeeID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.Province,
		&i.ZipCode,
		&i.EmergencyName,
		&i.EmergencyPhone,
		&i.EmergencyRelation,
		&i.BankName,
		&i.BankAccountNo,
		&i.BankAccountName,
		&i.Tin,
		&i.SssNo,
		&i.PhilhealthNo,
		&i.PagibigNo,
		&i.BloodType,
		&i.Religion,
		&i.UpdatedAt,
		&i.SsnEncrypted,
		&i.StateOfResidence,
		&i.W4FilingStatus,
		&i.W4AdditionalWithholding,
		&i.W4MultipleJobs,
		&i.W4DependentsCredit,
		&i.W4OtherIncome,
		&i.W4Deductions,
		&i.StateAllowances,
	)
	return i, err
}

const getOrgChartData = `-- name: GetOrgChartData :many
SELECT e.id, e.first_name, e.last_name, e.display_name,
       e.manager_id,
       COALESCE(d.name, '') as department_name,
       COALESCE(p.title, '') as position_title,
       u.avatar_url
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
LEFT JOIN users u ON u.id = e.user_id
WHERE e.company_id = $1 AND e.status = 'active'
ORDER BY e.last_name, e.first_name
`

type GetOrgChartDataRow struct {
	ID             int64   `json:"id"`
	FirstName      string  `json:"first_name"`
	LastName       string  `json:"last_name"`
	DisplayName    *string `json:"display_name"`
	ManagerID      *int64  `json:"manager_id"`
	DepartmentName string  `json:"department_name"`
	PositionTitle  string  `json:"position_title"`
	AvatarUrl      *string `json:"avatar_url"`
}

func (q *Queries) GetOrgChartData(ctx context.Context, companyID int64) ([]GetOrgChartDataRow, error) {
	rows, err := q.db.Query(ctx, getOrgChartData, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOrgChartDataRow{}
	for rows.Next() {
		var i GetOrgChartDataRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.ManagerID,
			&i.DepartmentName,
			&i.PositionTitle,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkUserToEmployee = `-- name: LinkUserToEmployee :exec
UPDATE employees SET user_id = $1 WHERE id = $2 AND company_id = $3
`

type LinkUserToEmployeeParams struct {
	UserID    *int64 `json:"user_id"`
	ID        int64  `json:"id"`
	CompanyID int64  `json:"company_id"`
}

func (q *Queries) LinkUserToEmployee(ctx context.Context, arg LinkUserToEmployeeParams) error {
	_, err := q.db.Exec(ctx, linkUserToEmployee, arg.UserID, arg.ID, arg.CompanyID)
	return err
}

const listActiveEmployees = `-- name: ListActiveEmployees :many
SELECT id, company_id, user_id, employee_no, first_name, last_name, middle_name, suffix, display_name, email, phone, birth_date, gender, civil_status, nationality, department_id, position_id, cost_center_id, manager_id, hire_date, regularization_date, separation_date, employment_type, status, created_at, updated_at, contract_end_date FROM employees
WHERE company_id = $1 AND status = 'active'
ORDER BY last_name, first_name
`

func (q *Queries) ListActiveEmployees(ctx context.Context, companyID int64) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listActiveEmployees, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Suffix,
			&i.DisplayName,
			&i.Email,
			&i.Phone,
			&i.BirthDate,
			&i.Gender,
			&i.CivilStatus,
			&i.Nationality,
			&i.DepartmentID,
			&i.PositionID,
			&i.CostCenterID,
			&i.ManagerID,
			&i.HireDate,
			&i.RegularizationDate,
			&i.SeparationDate,
			&i.EmploymentType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContractEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeDirectory = `-- name: ListEmployeeDirectory :many
SELECT e.id, e.employee_no, e.first_name, e.last_name, e.display_name,
       e.email, e.phone, e.status, e.employment_type, e.manager_id,
       COALESCE(d.name, '') as department_name,
       COALESCE(p.title, '') as position_title,
       u.avatar_url
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
LEFT JOIN users u ON u.id = e.user_id
WHERE e.company_id = $1
  AND e.status = 'active'
  AND ($2::varchar IS NULL OR $2 = '' OR
    e.first_name ILIKE $2 OR e.last_name ILIKE $2 OR
    e.employee_no ILIKE $2 OR e.email ILIKE $2)
  AND ($3::bigint IS NULL OR $3 = 0 OR e.department_id = $3)
ORDER BY e.last_name, e.first_name
`

type ListEmployeeDirectoryParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Column3   int64  `json:"column_3"`
}

type ListEmployeeDirectoryRow struct {
	ID             int64   `json:"id"`
	EmployeeNo     string  `json:"employee_no"`
	FirstName      string  `json:"first_name"`
	LastName       string  `json:"last_name"`
	DisplayName    *string `json:"display_name"`
	Email          *string `json:"email"`
	Phone          *string `json:"phone"`
	Status         string  `json:"status"`
	EmploymentType string  `json:"employment_type"`
	ManagerID      *int64  `json:"manager_id"`
	DepartmentName string  `json:"department_name"`
	PositionTitle  string  `json:"position_title"`
	AvatarUrl      *string `json:"avatar_url"`
}

func (q *Queries) ListEmployeeDirectory(ctx context.Context, arg ListEmployeeDirectoryParams) ([]ListEmployeeDirectoryRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeDirectory, arg.CompanyID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeDirectoryRow{}
	for rows.Next() {
		var i ListEmployeeDirectoryRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.Email,
			&i.Phone,
			&i.Status,
			&i.EmploymentType,
			&i.ManagerID,
			&i.DepartmentName,
			&i.PositionTitle,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeDocuments = `-- name: ListEmployeeDocuments :many
SELECT id, company_id, employee_id, doc_type, file_name, file_path, file_size, mime_type, file_hash, uploaded_by, verified_at, verified_by, notes, created_at, expiry_date, category_id, title, version, is_required, status, updated_at FROM employee_documents WHERE employee_id = $1 AND company_id = $2 ORDER BY created_at DESC
`

type ListEmployeeDocumentsParams struct {
	EmployeeID int64 `json:"employee_id"`
	CompanyID  int64 `json:"company_id"`
}

func (q *Queries) ListEmployeeDocuments(ctx context.Context, arg ListEmployeeDocumentsParams) ([]EmployeeDocument, error) {
	rows, err := q.db.Query(ctx, listEmployeeDocuments, arg.EmployeeID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmployeeDocument{}
	for rows.Next() {
		var i EmployeeDocument
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.DocType,
			&i.FileName,
			&i.FilePath,
			&i.FileSize,
			&i.MimeType,
			&i.FileHash,
			&i.UploadedBy,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.Notes,
			&i.CreatedAt,
			&i.ExpiryDate,
			&i.CategoryID,
			&i.Title,
			&i.Version,
			&i.IsRequired,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeTimeline = `-- name: ListEmployeeTimeline :many
SELECT eh.id, eh.action_type, eh.effective_date, eh.remarks, eh.created_at,
       COALESCE(fd.name, '') as from_department,
       COALESCE(td.name, '') as to_department,
       COALESCE(fp.title, '') as from_position,
       COALESCE(tp.title, '') as to_position,
       COALESCE(u.email, '') as created_by_email
FROM employment_history eh
LEFT JOIN departments fd ON fd.id = eh.from_department_id
LEFT JOIN departments td ON td.id = eh.to_department_id
LEFT JOIN positions fp ON fp.id = eh.from_position_id
LEFT JOIN positions tp ON tp.id = eh.to_position_id
LEFT JOIN users u ON u.id = eh.created_by
WHERE eh.employee_id = $1 AND eh.company_id = $2
ORDER BY eh.effective_date DESC, eh.created_at DESC
LIMIT 50
`

type ListEmployeeTimelineParams struct {
	EmployeeID int64 `json:"employee_id"`
	CompanyID  int64 `json:"company_id"`
}

type ListEmployeeTimelineRow struct {
	ID             int64     `json:"id"`
	ActionType     string    `json:"action_type"`
	EffectiveDate  time.Time `json:"effective_date"`
	Remarks        *string   `json:"remarks"`
	CreatedAt      time.Time `json:"created_at"`
	FromDepartment string    `json:"from_department"`
	ToDepartment   string    `json:"to_department"`
	FromPosition   string    `json:"from_position"`
	ToPosition     string    `json:"to_position"`
	CreatedByEmail string    `json:"created_by_email"`
}

func (q *Queries) ListEmployeeTimeline(ctx context.Context, arg ListEmployeeTimelineParams) ([]ListEmployeeTimelineRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeTimeline, arg.EmployeeID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeTimelineRow{}
	for rows.Next() {
		var i ListEmployeeTimelineRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionType,
			&i.EffectiveDate,
			&i.Remarks,
			&i.CreatedAt,
			&i.FromDepartment,
			&i.ToDepartment,
			&i.FromPosition,
			&i.ToPosition,
			&i.CreatedByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, company_id, user_id, employee_no, first_name, last_name, middle_name, suffix, display_name, email, phone, birth_date, gender, civil_status, nationality, department_id, position_id, cost_center_id, manager_id, hire_date, regularization_date, separation_date, employment_type, status, created_at, updated_at, contract_end_date FROM employees
WHERE company_id = $1
  AND ($2::varchar IS NULL OR $2 = '' OR status = $2)
  AND ($3::bigint IS NULL OR $3 = 0 OR department_id = $3)
ORDER BY last_name, first_name
LIMIT $4 OFFSET $5
`

type ListEmployeesParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Column3   int64  `json:"column_3"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]Employee, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Employee{}
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Suffix,
			&i.DisplayName,
			&i.Email,
			&i.Phone,
			&i.BirthDate,
			&i.Gender,
			&i.CivilStatus,
			&i.Nationality,
			&i.DepartmentID,
			&i.PositionID,
			&i.CostCenterID,
			&i.ManagerID,
			&i.HireDate,
			&i.RegularizationDate,
			&i.SeparationDate,
			&i.EmploymentType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ContractEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesForDOLERegister = `-- name: ListEmployeesForDOLERegister :many
SELECT e.id, e.employee_no, e.first_name, e.last_name, e.middle_name,
       e.gender, e.birth_date, e.civil_status, e.nationality,
       e.hire_date, e.employment_type, e.status,
       COALESCE(d.name, '') as department_name,
       COALESCE(p.title, '') as position_title,
       COALESCE(ep.tin, '') as tin,
       COALESCE(ep.sss_no, '') as sss_no,
       COALESCE(ep.philhealth_no, '') as philhealth_no,
       COALESCE(ep.pagibig_no, '') as pagibig_no
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
LEFT JOIN employee_profiles ep ON ep.employee_id = e.id
WHERE e.company_id = $1 AND e.status IN ('active', 'probationary')
ORDER BY e.last_name, e.first_name
`

type ListEmployeesForDOLERegisterRow struct {
	ID             int64       `json:"id"`
	EmployeeNo     string      `json:"employee_no"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	MiddleName     *string     `json:"middle_name"`
	Gender         *string     `json:"gender"`
	BirthDate      pgtype.Date `json:"birth_date"`
	CivilStatus    *string     `json:"civil_status"`
	Nationality    *string     `json:"nationality"`
	HireDate       time.Time   `json:"hire_date"`
	EmploymentType string      `json:"employment_type"`
	Status         string      `json:"status"`
	DepartmentName string      `json:"department_name"`
	PositionTitle  string      `json:"position_title"`
	Tin            string      `json:"tin"`
	SssNo          string      `json:"sss_no"`
	PhilhealthNo   string      `json:"philhealth_no"`
	PagibigNo      string      `json:"pagibig_no"`
}

func (q *Queries) ListEmployeesForDOLERegister(ctx context.Context, companyID int64) ([]ListEmployeesForDOLERegisterRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesForDOLERegister, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesForDOLERegisterRow{}
	for rows.Next() {
		var i ListEmployeesForDOLERegisterRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.Gender,
			&i.BirthDate,
			&i.CivilStatus,
			&i.Nationality,
			&i.HireDate,
			&i.EmploymentType,
			&i.Status,
			&i.DepartmentName,
			&i.PositionTitle,
			&i.Tin,
			&i.SssNo,
			&i.PhilhealthNo,
			&i.PagibigNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmploymentHistory = `-- name: ListEmploymentHistory :many
SELECT id, company_id, employee_id, action_type, effective_date, from_department_id, to_department_id, from_position_id, to_position_id, remarks, created_by, created_at FROM employment_history WHERE employee_id = $1 AND company_id = $2 ORDER BY effective_date DESC
`

type ListEmploymentHistoryParams struct {
	EmployeeID int64 `json:"employee_id"`
	CompanyID  int64 `json:"company_id"`
}

func (q *Queries) ListEmploymentHistory(ctx context.Context, arg ListEmploymentHistoryParams) ([]EmploymentHistory, error) {
	rows, err := q.db.Query(ctx, listEmploymentHistory, arg.EmployeeID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmploymentHistory{}
	for rows.Next() {
		var i EmploymentHistory
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.ActionType,
			&i.EffectiveDate,
			&i.FromDepartmentID,
			&i.ToDepartmentID,
			&i.FromPositionID,
			&i.ToPositionID,
			&i.Remarks,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringDocuments = `-- name: ListExpiringDocuments :many
SELECT ed.id, ed.company_id, ed.employee_id, ed.doc_type, ed.file_name,
       ed.expiry_date, e.first_name, e.last_name, e.employee_no
FROM employee_documents ed
JOIN employees e ON e.id = ed.employee_id
WHERE ed.company_id = $1
  AND ed.expiry_date IS NOT NULL
  AND ed.expiry_date BETWEEN NOW()::date AND (NOW() + INTERVAL '60 days')::date
ORDER BY ed.expiry_date ASC
LIMIT 50
`

type ListExpiringDocumentsRow struct {
	ID         uuid.UUID   `json:"id"`
	CompanyID  int64       `json:"company_id"`
	EmployeeID int64       `json:"employee_id"`
	DocType    string      `json:"doc_type"`
	FileName   string      `json:"file_name"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
	FirstName  string      `json:"first_name"`
	LastName   string      `json:"last_name"`
	EmployeeNo string      `json:"employee_no"`
}

func (q *Queries) ListExpiringDocuments(ctx context.Context, companyID int64) ([]ListExpiringDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringDocuments, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringDocumentsRow{}
	for rows.Next() {
		var i ListExpiringDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.DocType,
			&i.FileName,
			&i.ExpiryDate,
			&i.FirstName,
			&i.LastName,
			&i.EmployeeNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regularizeEmployee = `-- name: RegularizeEmployee :one
UPDATE employees SET
    employment_type = 'regular',
    regularization_date = CURRENT_DATE,
    status = 'active',
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
  AND employment_type = 'probationary'
  AND status IN ('active', 'probationary')
RETURNING id, employee_no, first_name, last_name
`

type RegularizeEmployeeParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

type RegularizeEmployeeRow struct {
	ID         int64  `json:"id"`
	EmployeeNo string `json:"employee_no"`
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
}

func (q *Queries) RegularizeEmployee(ctx context.Context, arg RegularizeEmployeeParams) (RegularizeEmployeeRow, error) {
	row := q.db.QueryRow(ctx, regularizeEmployee, arg.ID, arg.CompanyID)
	var i RegularizeEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FirstName,
		&i.LastName,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees SET
    first_name = COALESCE($3, first_name),
    last_name = COALESCE($4, last_name),
    middle_name = $5,
    display_name = $6,
    email = $7,
    phone = $8,
    department_id = $9,
    position_id = $10,
    cost_center_id = $11,
    manager_id = $12,
    employment_type = COALESCE($13, employment_type),
    status = COALESCE($14, status),
    nationality = COALESCE($15, nationality),
    birth_date = COALESCE($16, birth_date),
    hire_date = COALESCE($17, hire_date),
    gender = COALESCE($18, gender),
    civil_status = COALESCE($19, civil_status),
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, user_id, employee_no, first_name, last_name, middle_name, suffix, display_name, email, phone, birth_date, gender, civil_status, nationality, department_id, position_id, cost_center_id, manager_id, hire_date, regularization_date, separation_date, employment_type, status, created_at, updated_at, contract_end_date
`

type UpdateEmployeeParams struct {
	ID             int64       `json:"id"`
	CompanyID      int64       `json:"company_id"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	MiddleName     *string     `json:"middle_name"`
	DisplayName    *string     `json:"display_name"`
	Email          *string     `json:"email"`
	Phone          *string     `json:"phone"`
	DepartmentID   *int64      `json:"department_id"`
	PositionID     *int64      `json:"position_id"`
	CostCenterID   *int64      `json:"cost_center_id"`
	ManagerID      *int64      `json:"manager_id"`
	EmploymentType string      `json:"employment_type"`
	Status         string      `json:"status"`
	Nationality    *string     `json:"nationality"`
	BirthDate      pgtype.Date `json:"birth_date"`
	HireDate       pgtype.Date `json:"hire_date"`
	Gender         *string     `json:"gender"`
	CivilStatus    *string     `json:"civil_status"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.ID,
		arg.CompanyID,
		arg.FirstName,
		arg.LastName,
		arg.MiddleName,
		arg.DisplayName,
		arg.Email,
		arg.Phone,
		arg.DepartmentID,
		arg.PositionID,
		arg.CostCenterID,
		arg.ManagerID,
		arg.EmploymentType,
		arg.Status,
		arg.Nationality,
		arg.BirthDate,
		arg.HireDate,
		arg.Gender,
		arg.CivilStatus,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.EmployeeNo,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Suffix,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.BirthDate,
		&i.Gender,
		&i.CivilStatus,
		&i.Nationality,
		&i.DepartmentID,
		&i.PositionID,
		&i.CostCenterID,
		&i.ManagerID,
		&i.HireDate,
		&i.RegularizationDate,
		&i.SeparationDate,
		&i.EmploymentType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractEndDate,
	)
	return i, err
}

const upsertEmployeeProfile = `-- name: UpsertEmployeeProfile :one
INSERT INTO employee_profiles (
    employee_id, address_line1, address_line2, city, province, zip_code,
    emergency_name, emergency_phone, emergency_relation,
    bank_name, bank_account_no, bank_account_name,
    tin, sss_no, philhealth_no, pagibig_no
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (employee_id) DO UPDATE SET
    address_line1 = EXCLUDED.address_line1,
    address_line2 = EXCLUDED.address_line2,
    city = EXCLUDED.city,
    province = EXCLUDED.province,
    zip_code = EXCLUDED.zip_code,
    emergency_name = EXCLUDED.emergency_name,
    emergency_phone = EXCLUDED.emergency_phone,
    emergency_relation = EXCLUDED.emergency_relation,
    bank_name = EXCLUDED.bank_name,
    bank_account_no = EXCLUDED.bank_account_no,
    bank_account_name = EXCLUDED.bank_account_name,
    tin = EXCLUDED.tin,
    sss_no = EXCLUDED.sss_no,
    philhealth_no = EXCLUDED.philhealth_no,
    pagibig_no = EXCLUDED.pagibig_no,
    updated_at = NOW()
RETURNING employee_id, address_line1, address_line2, city, province, zip_code, emergency_name, emergency_phone, emergency_relation, bank_name, bank_account_no, bank_account_name, tin, sss_no, philhealth_no, pagibig_no, blood_type, religion, updated_at, ssn_encrypted, state_of_residence, w4_filing_status, w4_additional_withholding, w4_multiple_jobs, w4_dependents_credit, w4_other_income, w4_deductions, state_allowances
`

type UpsertEmployeeProfileParams struct {
	EmployeeID        int64   `json:"employee_id"`
	AddressLine1      *string `json:"address_line1"`
	AddressLine2      *string `json:"address_line2"`
	City              *string `json:"city"`
	Province          *string `json:"province"`
	ZipCode           *string `json:"zip_code"`
	EmergencyName     *string `json:"emergency_name"`
	EmergencyPhone    *string `json:"emergency_phone"`
	EmergencyRelation *string `json:"emergency_relation"`
	BankName          *string `json:"bank_name"`
	BankAccountNo     *string `json:"bank_account_no"`
	BankAccountName   *string `json:"bank_account_name"`
	Tin               *string `json:"tin"`
	SssNo             *string `json:"sss_no"`
	PhilhealthNo      *string `json:"philhealth_no"`
	PagibigNo         *string `json:"pagibig_no"`
}

func (q *Queries) UpsertEmployeeProfile(ctx context.Context, arg UpsertEmployeeProfileParams) (EmployeeProfile, error) {
	row := q.db.QueryRow(ctx, upsertEmployeeProfile,
		arg.EmployeeID,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.City,
		arg.Province,
		arg.ZipCode,
		arg.EmergencyName,
		arg.EmergencyPhone,
		arg.EmergencyRelation,
		arg.BankName,
		arg.BankAccountNo,
		arg.BankAccountName,
		arg.Tin,
		arg.SssNo,
		arg.PhilhealthNo,
		arg.PagibigNo,
	)
	var i EmployeeProfile
	err := row.Scan(
		&i.EmployeeID,
		&i.AddressLine1,
		&i.AddressLine2,
		&i.City,
		&i.Province,
		&i.ZipCode,
		&i.EmergencyName,
		&i.EmergencyPhone,
		&i.EmergencyRelation,
		&i.BankName,
		&i.BankAccountNo,
		&i.BankAccountName,
		&i.Tin,
		&i.SssNo,
		&i.PhilhealthNo,
		&i.PagibigNo,
		&i.BloodType,
		&i.Religion,
		&i.UpdatedAt,
		&i.SsnEncrypted,
		&i.StateOfResidence,
		&i.W4FilingStatus,
		&i.W4AdditionalWithholding,
		&i.W4MultipleJobs,
		&i.W4DependentsCredit,
		&i.W4OtherIncome,
		&i.W4Deductions,
		&i.StateAllowances,
	)
	return i, err
}
