// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: holidays.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHolidaysInPeriod = `-- name: CountHolidaysInPeriod :one
SELECT COUNT(*) FROM holidays
WHERE company_id = $1
  AND holiday_date >= $2
  AND holiday_date <= $3
  AND holiday_type IN ('regular', 'special_non_working')
`

type CountHolidaysInPeriodParams struct {
	CompanyID     int64     `json:"company_id"`
	HolidayDate   time.Time `json:"holiday_date"`
	HolidayDate_2 time.Time `json:"holiday_date_2"`
}

func (q *Queries) CountHolidaysInPeriod(ctx context.Context, arg CountHolidaysInPeriodParams) (int64, error) {
	row := q.db.QueryRow(ctx, countHolidaysInPeriod, arg.CompanyID, arg.HolidayDate, arg.HolidayDate_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFinalPay = `-- name: CreateFinalPay :one
INSERT INTO final_pay (
    company_id, employee_id, separation_date, separation_reason,
    unpaid_salary, prorated_13th, unused_leave_conversion,
    separation_pay, tax_refund, other_deductions, total_final_pay,
    payload, status, computed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 'calculated', NOW())
RETURNING id, company_id, employee_id, separation_date, separation_reason, unpaid_salary, prorated_13th, unused_leave_conversion, separation_pay, tax_refund, other_deductions, total_final_pay, payload, status, computed_at, released_at, created_at
`

type CreateFinalPayParams struct {
	CompanyID             int64           `json:"company_id"`
	EmployeeID            int64           `json:"employee_id"`
	SeparationDate        time.Time       `json:"separation_date"`
	SeparationReason      string          `json:"separation_reason"`
	UnpaidSalary          pgtype.Numeric  `json:"unpaid_salary"`
	Prorated13th          pgtype.Numeric  `json:"prorated_13th"`
	UnusedLeaveConversion pgtype.Numeric  `json:"unused_leave_conversion"`
	SeparationPay         pgtype.Numeric  `json:"separation_pay"`
	TaxRefund             pgtype.Numeric  `json:"tax_refund"`
	OtherDeductions       pgtype.Numeric  `json:"other_deductions"`
	TotalFinalPay         pgtype.Numeric  `json:"total_final_pay"`
	Payload               json.RawMessage `json:"payload"`
}

func (q *Queries) CreateFinalPay(ctx context.Context, arg CreateFinalPayParams) (FinalPay, error) {
	row := q.db.QueryRow(ctx, createFinalPay,
		arg.CompanyID,
		arg.EmployeeID,
		arg.SeparationDate,
		arg.SeparationReason,
		arg.UnpaidSalary,
		arg.Prorated13th,
		arg.UnusedLeaveConversion,
		arg.SeparationPay,
		arg.TaxRefund,
		arg.OtherDeductions,
		arg.TotalFinalPay,
		arg.Payload,
	)
	var i FinalPay
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.SeparationDate,
		&i.SeparationReason,
		&i.UnpaidSalary,
		&i.Prorated13th,
		&i.UnusedLeaveConversion,
		&i.SeparationPay,
		&i.TaxRefund,
		&i.OtherDeductions,
		&i.TotalFinalPay,
		&i.Payload,
		&i.Status,
		&i.ComputedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createHoliday = `-- name: CreateHoliday :one
INSERT INTO holidays (company_id, name, holiday_date, holiday_type, year, is_nationwide)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, name, holiday_date, holiday_type, year, is_nationwide, created_at
`

type CreateHolidayParams struct {
	CompanyID    int64     `json:"company_id"`
	Name         string    `json:"name"`
	HolidayDate  time.Time `json:"holiday_date"`
	HolidayType  string    `json:"holiday_type"`
	Year         int32     `json:"year"`
	IsNationwide bool      `json:"is_nationwide"`
}

func (q *Queries) CreateHoliday(ctx context.Context, arg CreateHolidayParams) (Holiday, error) {
	row := q.db.QueryRow(ctx, createHoliday,
		arg.CompanyID,
		arg.Name,
		arg.HolidayDate,
		arg.HolidayType,
		arg.Year,
		arg.IsNationwide,
	)
	var i Holiday
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.HolidayDate,
		&i.HolidayType,
		&i.Year,
		&i.IsNationwide,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHoliday = `-- name: DeleteHoliday :exec
DELETE FROM holidays WHERE id = $1 AND company_id = $2
`

type DeleteHolidayParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) DeleteHoliday(ctx context.Context, arg DeleteHolidayParams) error {
	_, err := q.db.Exec(ctx, deleteHoliday, arg.ID, arg.CompanyID)
	return err
}

const get13thMonthPay = `-- name: Get13thMonthPay :one
SELECT id, company_id, employee_id, year, total_basic_salary, months_worked, amount, tax_exempt_amount, taxable_amount, status, computed_at, paid_at, created_at, updated_at FROM thirteenth_month_pay
WHERE company_id = $1 AND employee_id = $2 AND year = $3
`

type Get13thMonthPayParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
	Year       int32 `json:"year"`
}

func (q *Queries) Get13thMonthPay(ctx context.Context, arg Get13thMonthPayParams) (ThirteenthMonthPay, error) {
	row := q.db.QueryRow(ctx, get13thMonthPay, arg.CompanyID, arg.EmployeeID, arg.Year)
	var i ThirteenthMonthPay
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.Year,
		&i.TotalBasicSalary,
		&i.MonthsWorked,
		&i.Amount,
		&i.TaxExemptAmount,
		&i.TaxableAmount,
		&i.Status,
		&i.ComputedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFinalPay = `-- name: GetFinalPay :one
SELECT id, company_id, employee_id, separation_date, separation_reason, unpaid_salary, prorated_13th, unused_leave_conversion, separation_pay, tax_refund, other_deductions, total_final_pay, payload, status, computed_at, released_at, created_at FROM final_pay
WHERE company_id = $1 AND employee_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetFinalPayParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
}

func (q *Queries) GetFinalPay(ctx context.Context, arg GetFinalPayParams) (FinalPay, error) {
	row := q.db.QueryRow(ctx, getFinalPay, arg.CompanyID, arg.EmployeeID)
	var i FinalPay
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.SeparationDate,
		&i.SeparationReason,
		&i.UnpaidSalary,
		&i.Prorated13th,
		&i.UnusedLeaveConversion,
		&i.SeparationPay,
		&i.TaxRefund,
		&i.OtherDeductions,
		&i.TotalFinalPay,
		&i.Payload,
		&i.Status,
		&i.ComputedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const list13thMonthPay = `-- name: List13thMonthPay :many
SELECT id, company_id, employee_id, year, total_basic_salary, months_worked, amount, tax_exempt_amount, taxable_amount, status, computed_at, paid_at, created_at, updated_at FROM thirteenth_month_pay
WHERE company_id = $1 AND year = $2
ORDER BY employee_id
`

type List13thMonthPayParams struct {
	CompanyID int64 `json:"company_id"`
	Year      int32 `json:"year"`
}

func (q *Queries) List13thMonthPay(ctx context.Context, arg List13thMonthPayParams) ([]ThirteenthMonthPay, error) {
	rows, err := q.db.Query(ctx, list13thMonthPay, arg.CompanyID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ThirteenthMonthPay{}
	for rows.Next() {
		var i ThirteenthMonthPay
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.Year,
			&i.TotalBasicSalary,
			&i.MonthsWorked,
			&i.Amount,
			&i.TaxExemptAmount,
			&i.TaxableAmount,
			&i.Status,
			&i.ComputedAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinalPays = `-- name: ListFinalPays :many
SELECT fp.id, fp.company_id, fp.employee_id, fp.separation_date, fp.separation_reason, fp.unpaid_salary, fp.prorated_13th, fp.unused_leave_conversion, fp.separation_pay, fp.tax_refund, fp.other_deductions, fp.total_final_pay, fp.payload, fp.status, fp.computed_at, fp.released_at, fp.created_at, e.employee_no, e.first_name, e.last_name
FROM final_pay fp
JOIN employees e ON e.id = fp.employee_id
WHERE fp.company_id = $1
ORDER BY fp.created_at DESC
LIMIT $2 OFFSET $3
`

type ListFinalPaysParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListFinalPaysRow struct {
	ID                    int64              `json:"id"`
	CompanyID             int64              `json:"company_id"`
	EmployeeID            int64              `json:"employee_id"`
	SeparationDate        time.Time          `json:"separation_date"`
	SeparationReason      string             `json:"separation_reason"`
	UnpaidSalary          pgtype.Numeric     `json:"unpaid_salary"`
	Prorated13th          pgtype.Numeric     `json:"prorated_13th"`
	UnusedLeaveConversion pgtype.Numeric     `json:"unused_leave_conversion"`
	SeparationPay         pgtype.Numeric     `json:"separation_pay"`
	TaxRefund             pgtype.Numeric     `json:"tax_refund"`
	OtherDeductions       pgtype.Numeric     `json:"other_deductions"`
	TotalFinalPay         pgtype.Numeric     `json:"total_final_pay"`
	Payload               json.RawMessage    `json:"payload"`
	Status                string             `json:"status"`
	ComputedAt            pgtype.Timestamptz `json:"computed_at"`
	ReleasedAt            pgtype.Timestamptz `json:"released_at"`
	CreatedAt             time.Time          `json:"created_at"`
	EmployeeNo            string             `json:"employee_no"`
	FirstName             string             `json:"first_name"`
	LastName              string             `json:"last_name"`
}

func (q *Queries) ListFinalPays(ctx context.Context, arg ListFinalPaysParams) ([]ListFinalPaysRow, error) {
	rows, err := q.db.Query(ctx, listFinalPays, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFinalPaysRow{}
	for rows.Next() {
		var i ListFinalPaysRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.SeparationDate,
			&i.SeparationReason,
			&i.UnpaidSalary,
			&i.Prorated13th,
			&i.UnusedLeaveConversion,
			&i.SeparationPay,
			&i.TaxRefund,
			&i.OtherDeductions,
			&i.TotalFinalPay,
			&i.Payload,
			&i.Status,
			&i.ComputedAt,
			&i.ReleasedAt,
			&i.CreatedAt,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHolidays = `-- name: ListHolidays :many
SELECT id, company_id, name, holiday_date, holiday_type, year, is_nationwide, created_at FROM holidays
WHERE company_id = $1 AND year = $2
ORDER BY holiday_date ASC
`

type ListHolidaysParams struct {
	CompanyID int64 `json:"company_id"`
	Year      int32 `json:"year"`
}

func (q *Queries) ListHolidays(ctx context.Context, arg ListHolidaysParams) ([]Holiday, error) {
	rows, err := q.db.Query(ctx, listHolidays, arg.CompanyID, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Holiday{}
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.HolidayDate,
			&i.HolidayType,
			&i.Year,
			&i.IsNationwide,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHolidaysInPeriod = `-- name: ListHolidaysInPeriod :many
SELECT id, company_id, name, holiday_date, holiday_type, year, is_nationwide, created_at FROM holidays
WHERE company_id = $1
  AND holiday_date >= $2
  AND holiday_date <= $3
ORDER BY holiday_date ASC
`

type ListHolidaysInPeriodParams struct {
	CompanyID     int64     `json:"company_id"`
	HolidayDate   time.Time `json:"holiday_date"`
	HolidayDate_2 time.Time `json:"holiday_date_2"`
}

func (q *Queries) ListHolidaysInPeriod(ctx context.Context, arg ListHolidaysInPeriodParams) ([]Holiday, error) {
	rows, err := q.db.Query(ctx, listHolidaysInPeriod, arg.CompanyID, arg.HolidayDate, arg.HolidayDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Holiday{}
	for rows.Next() {
		var i Holiday
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.HolidayDate,
			&i.HolidayType,
			&i.Year,
			&i.IsNationwide,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update13thMonthStatus = `-- name: Update13thMonthStatus :exec
UPDATE thirteenth_month_pay SET
    status = $3,
    paid_at = CASE WHEN $3 = 'paid' THEN NOW() ELSE paid_at END,
    updated_at = NOW()
WHERE company_id = $1 AND year = $2
`

type Update13thMonthStatusParams struct {
	CompanyID int64  `json:"company_id"`
	Year      int32  `json:"year"`
	Status    string `json:"status"`
}

func (q *Queries) Update13thMonthStatus(ctx context.Context, arg Update13thMonthStatusParams) error {
	_, err := q.db.Exec(ctx, update13thMonthStatus, arg.CompanyID, arg.Year, arg.Status)
	return err
}

const updateFinalPayStatus = `-- name: UpdateFinalPayStatus :one
UPDATE final_pay SET
    status = $3,
    released_at = CASE WHEN $3 = 'released' THEN NOW() ELSE released_at END
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, employee_id, separation_date, separation_reason, unpaid_salary, prorated_13th, unused_leave_conversion, separation_pay, tax_refund, other_deductions, total_final_pay, payload, status, computed_at, released_at, created_at
`

type UpdateFinalPayStatusParams struct {
	ID        int64  `json:"id"`
	CompanyID int64  `json:"company_id"`
	Status    string `json:"status"`
}

func (q *Queries) UpdateFinalPayStatus(ctx context.Context, arg UpdateFinalPayStatusParams) (FinalPay, error) {
	row := q.db.QueryRow(ctx, updateFinalPayStatus, arg.ID, arg.CompanyID, arg.Status)
	var i FinalPay
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.SeparationDate,
		&i.SeparationReason,
		&i.UnpaidSalary,
		&i.Prorated13th,
		&i.UnusedLeaveConversion,
		&i.SeparationPay,
		&i.TaxRefund,
		&i.OtherDeductions,
		&i.TotalFinalPay,
		&i.Payload,
		&i.Status,
		&i.ComputedAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsert13thMonthPay = `-- name: Upsert13thMonthPay :one
INSERT INTO thirteenth_month_pay (
    company_id, employee_id, year, total_basic_salary, months_worked,
    amount, tax_exempt_amount, taxable_amount, status, computed_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'calculated', NOW())
ON CONFLICT (company_id, employee_id, year) DO UPDATE SET
    total_basic_salary = EXCLUDED.total_basic_salary,
    months_worked = EXCLUDED.months_worked,
    amount = EXCLUDED.amount,
    taxable_amount = EXCLUDED.taxable_amount,
    status = 'calculated',
    computed_at = NOW(),
    updated_at = NOW()
RETURNING id, company_id, employee_id, year, total_basic_salary, months_worked, amount, tax_exempt_amount, taxable_amount, status, computed_at, paid_at, created_at, updated_at
`

type Upsert13thMonthPayParams struct {
	CompanyID        int64          `json:"company_id"`
	EmployeeID       int64          `json:"employee_id"`
	Year             int32          `json:"year"`
	TotalBasicSalary pgtype.Numeric `json:"total_basic_salary"`
	MonthsWorked     pgtype.Numeric `json:"months_worked"`
	Amount           pgtype.Numeric `json:"amount"`
	TaxExemptAmount  pgtype.Numeric `json:"tax_exempt_amount"`
	TaxableAmount    pgtype.Numeric `json:"taxable_amount"`
}

func (q *Queries) Upsert13thMonthPay(ctx context.Context, arg Upsert13thMonthPayParams) (ThirteenthMonthPay, error) {
	row := q.db.QueryRow(ctx, upsert13thMonthPay,
		arg.CompanyID,
		arg.EmployeeID,
		arg.Year,
		arg.TotalBasicSalary,
		arg.MonthsWorked,
		arg.Amount,
		arg.TaxExemptAmount,
		arg.TaxableAmount,
	)
	var i ThirteenthMonthPay
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.Year,
		&i.TotalBasicSalary,
		&i.MonthsWorked,
		&i.Amount,
		&i.TaxExemptAmount,
		&i.TaxableAmount,
		&i.Status,
		&i.ComputedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
