// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hr_request.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countHRRequestsByStatus = `-- name: CountHRRequestsByStatus :many
SELECT status, COUNT(*) as count
FROM hr_requests
WHERE company_id = $1
GROUP BY status
`

type CountHRRequestsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountHRRequestsByStatus(ctx context.Context, companyID int64) ([]CountHRRequestsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countHRRequestsByStatus, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountHRRequestsByStatusRow{}
	for rows.Next() {
		var i CountHRRequestsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOpenHRRequests = `-- name: CountOpenHRRequests :one
SELECT COUNT(*) as count FROM hr_requests
WHERE company_id = $1 AND status IN ('open', 'in_progress')
`

func (q *Queries) CountOpenHRRequests(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenHRRequests, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHRRequest = `-- name: CreateHRRequest :one
INSERT INTO hr_requests (company_id, employee_id, request_type, subject, description, priority)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, employee_id, request_type, subject, description, priority, status, assigned_to, resolution_note, created_at, updated_at, resolved_at
`

type CreateHRRequestParams struct {
	CompanyID   int64   `json:"company_id"`
	EmployeeID  int64   `json:"employee_id"`
	RequestType string  `json:"request_type"`
	Subject     string  `json:"subject"`
	Description *string `json:"description"`
	Priority    string  `json:"priority"`
}

func (q *Queries) CreateHRRequest(ctx context.Context, arg CreateHRRequestParams) (HrRequest, error) {
	row := q.db.QueryRow(ctx, createHRRequest,
		arg.CompanyID,
		arg.EmployeeID,
		arg.RequestType,
		arg.Subject,
		arg.Description,
		arg.Priority,
	)
	var i HrRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.RequestType,
		&i.Subject,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedTo,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getHRRequest = `-- name: GetHRRequest :one
SELECT r.id, r.company_id, r.employee_id, r.request_type, r.subject, r.description, r.priority, r.status, r.assigned_to, r.resolution_note, r.created_at, r.updated_at, r.resolved_at,
    e.first_name, e.last_name, e.employee_no
FROM hr_requests r
JOIN employees e ON e.id = r.employee_id
WHERE r.id = $1 AND r.company_id = $2
`

type GetHRRequestParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

type GetHRRequestRow struct {
	ID             int64              `json:"id"`
	CompanyID      int64              `json:"company_id"`
	EmployeeID     int64              `json:"employee_id"`
	RequestType    string             `json:"request_type"`
	Subject        string             `json:"subject"`
	Description    *string            `json:"description"`
	Priority       string             `json:"priority"`
	Status         string             `json:"status"`
	AssignedTo     *int64             `json:"assigned_to"`
	ResolutionNote *string            `json:"resolution_note"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	EmployeeNo     string             `json:"employee_no"`
}

func (q *Queries) GetHRRequest(ctx context.Context, arg GetHRRequestParams) (GetHRRequestRow, error) {
	row := q.db.QueryRow(ctx, getHRRequest, arg.ID, arg.CompanyID)
	var i GetHRRequestRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.RequestType,
		&i.Subject,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedTo,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
		&i.FirstName,
		&i.LastName,
		&i.EmployeeNo,
	)
	return i, err
}

const listHRRequests = `-- name: ListHRRequests :many
SELECT r.id, r.company_id, r.employee_id, r.request_type, r.subject, r.description, r.priority, r.status, r.assigned_to, r.resolution_note, r.created_at, r.updated_at, r.resolved_at,
    e.first_name, e.last_name, e.employee_no,
    d.name as department
FROM hr_requests r
JOIN employees e ON e.id = r.employee_id
LEFT JOIN departments d ON d.id = e.department_id
WHERE r.company_id = $1
    AND ($2 = '' OR r.status = $2)
    AND ($3 = '' OR r.request_type = $3)
ORDER BY
    CASE r.priority
        WHEN 'urgent' THEN 1
        WHEN 'high' THEN 2
        WHEN 'normal' THEN 3
        WHEN 'low' THEN 4
    END,
    r.created_at DESC
LIMIT $4 OFFSET $5
`

type ListHRRequestsParams struct {
	CompanyID int64       `json:"company_id"`
	Column2   interface{} `json:"column_2"`
	Column3   interface{} `json:"column_3"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListHRRequestsRow struct {
	ID             int64              `json:"id"`
	CompanyID      int64              `json:"company_id"`
	EmployeeID     int64              `json:"employee_id"`
	RequestType    string             `json:"request_type"`
	Subject        string             `json:"subject"`
	Description    *string            `json:"description"`
	Priority       string             `json:"priority"`
	Status         string             `json:"status"`
	AssignedTo     *int64             `json:"assigned_to"`
	ResolutionNote *string            `json:"resolution_note"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	FirstName      string             `json:"first_name"`
	LastName       string             `json:"last_name"`
	EmployeeNo     string             `json:"employee_no"`
	Department     *string            `json:"department"`
}

func (q *Queries) ListHRRequests(ctx context.Context, arg ListHRRequestsParams) ([]ListHRRequestsRow, error) {
	rows, err := q.db.Query(ctx, listHRRequests,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHRRequestsRow{}
	for rows.Next() {
		var i ListHRRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.RequestType,
			&i.Subject,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.AssignedTo,
			&i.ResolutionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
			&i.FirstName,
			&i.LastName,
			&i.EmployeeNo,
			&i.Department,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHRRequestsByEmployee = `-- name: ListHRRequestsByEmployee :many
SELECT id, company_id, employee_id, request_type, subject, description, priority, status, assigned_to, resolution_note, created_at, updated_at, resolved_at FROM hr_requests
WHERE company_id = $1 AND employee_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListHRRequestsByEmployeeParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListHRRequestsByEmployee(ctx context.Context, arg ListHRRequestsByEmployeeParams) ([]HrRequest, error) {
	rows, err := q.db.Query(ctx, listHRRequestsByEmployee,
		arg.CompanyID,
		arg.EmployeeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HrRequest{}
	for rows.Next() {
		var i HrRequest
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.RequestType,
			&i.Subject,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.AssignedTo,
			&i.ResolutionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHRRequestStatus = `-- name: UpdateHRRequestStatus :one
UPDATE hr_requests SET
    status = $3,
    assigned_to = $4,
    resolution_note = $5,
    updated_at = NOW(),
    resolved_at = CASE WHEN $3 IN ('resolved', 'closed') THEN NOW() ELSE resolved_at END
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, employee_id, request_type, subject, description, priority, status, assigned_to, resolution_note, created_at, updated_at, resolved_at
`

type UpdateHRRequestStatusParams struct {
	ID             int64   `json:"id"`
	CompanyID      int64   `json:"company_id"`
	Status         string  `json:"status"`
	AssignedTo     *int64  `json:"assigned_to"`
	ResolutionNote *string `json:"resolution_note"`
}

func (q *Queries) UpdateHRRequestStatus(ctx context.Context, arg UpdateHRRequestStatusParams) (HrRequest, error) {
	row := q.db.QueryRow(ctx, updateHRRequestStatus,
		arg.ID,
		arg.CompanyID,
		arg.Status,
		arg.AssignedTo,
		arg.ResolutionNote,
	)
	var i HrRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.RequestType,
		&i.Subject,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.AssignedTo,
		&i.ResolutionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
