// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: knowledge.sql

package store

import (
	"context"
	"time"
)

const createKnowledgeArticle = `-- name: CreateKnowledgeArticle :one
INSERT INTO knowledge_articles (company_id, category, topic, title, content, tags, source)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, category, topic, title, content, tags, source, is_active, search_vector, created_at, updated_at
`

type CreateKnowledgeArticleParams struct {
	CompanyID *int64   `json:"company_id"`
	Category  string   `json:"category"`
	Topic     string   `json:"topic"`
	Title     string   `json:"title"`
	Content   string   `json:"content"`
	Tags      []string `json:"tags"`
	Source    *string  `json:"source"`
}

func (q *Queries) CreateKnowledgeArticle(ctx context.Context, arg CreateKnowledgeArticleParams) (KnowledgeArticle, error) {
	row := q.db.QueryRow(ctx, createKnowledgeArticle,
		arg.CompanyID,
		arg.Category,
		arg.Topic,
		arg.Title,
		arg.Content,
		arg.Tags,
		arg.Source,
	)
	var i KnowledgeArticle
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Category,
		&i.Topic,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.Source,
		&i.IsActive,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKnowledgeArticle = `-- name: DeleteKnowledgeArticle :exec
DELETE FROM knowledge_articles WHERE id = $1
`

func (q *Queries) DeleteKnowledgeArticle(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteKnowledgeArticle, id)
	return err
}

const getKnowledgeArticle = `-- name: GetKnowledgeArticle :one
SELECT id, company_id, category, topic, title, content, tags, source, is_active, search_vector, created_at, updated_at FROM knowledge_articles WHERE id = $1
`

func (q *Queries) GetKnowledgeArticle(ctx context.Context, id int64) (KnowledgeArticle, error) {
	row := q.db.QueryRow(ctx, getKnowledgeArticle, id)
	var i KnowledgeArticle
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Category,
		&i.Topic,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.Source,
		&i.IsActive,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listKnowledgeArticles = `-- name: ListKnowledgeArticles :many
SELECT id, company_id, category, topic, title, content, tags, source, is_active, search_vector, created_at, updated_at FROM knowledge_articles
WHERE (company_id IS NULL OR company_id = $1)
  AND ($2::varchar = '' OR category = $2)
ORDER BY category, topic
LIMIT $3 OFFSET $4
`

type ListKnowledgeArticlesParams struct {
	CompanyID *int64 `json:"company_id"`
	Column2   string `json:"column_2"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListKnowledgeArticles(ctx context.Context, arg ListKnowledgeArticlesParams) ([]KnowledgeArticle, error) {
	rows, err := q.db.Query(ctx, listKnowledgeArticles,
		arg.CompanyID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KnowledgeArticle{}
	for rows.Next() {
		var i KnowledgeArticle
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Category,
			&i.Topic,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.Source,
			&i.IsActive,
			&i.SearchVector,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeCategories = `-- name: ListKnowledgeCategories :many
SELECT DISTINCT category FROM knowledge_articles
WHERE is_active = true AND (company_id IS NULL OR company_id = $1)
ORDER BY category
`

func (q *Queries) ListKnowledgeCategories(ctx context.Context, companyID *int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listKnowledgeCategories, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKnowledgeArticles = `-- name: SearchKnowledgeArticles :many
SELECT id, company_id, category, topic, title, content, tags, source, is_active, created_at, updated_at
FROM knowledge_articles
WHERE is_active = true
  AND (company_id IS NULL OR company_id = $1)
  AND search_vector @@ plainto_tsquery('english', $2)
ORDER BY ts_rank(search_vector, plainto_tsquery('english', $2)) DESC
LIMIT $3
`

type SearchKnowledgeArticlesParams struct {
	CompanyID      *int64 `json:"company_id"`
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
}

type SearchKnowledgeArticlesRow struct {
	ID        int64     `json:"id"`
	CompanyID *int64    `json:"company_id"`
	Category  string    `json:"category"`
	Topic     string    `json:"topic"`
	Title     string    `json:"title"`
	Content   string    `json:"content"`
	Tags      []string  `json:"tags"`
	Source    *string   `json:"source"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) SearchKnowledgeArticles(ctx context.Context, arg SearchKnowledgeArticlesParams) ([]SearchKnowledgeArticlesRow, error) {
	rows, err := q.db.Query(ctx, searchKnowledgeArticles, arg.CompanyID, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchKnowledgeArticlesRow{}
	for rows.Next() {
		var i SearchKnowledgeArticlesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Category,
			&i.Topic,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.Source,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKnowledgeArticle = `-- name: UpdateKnowledgeArticle :one
UPDATE knowledge_articles SET
    category = COALESCE(NULLIF($2, ''), category),
    topic = COALESCE(NULLIF($3, ''), topic),
    title = COALESCE(NULLIF($4, ''), title),
    content = COALESCE(NULLIF($5, ''), content),
    tags = $6,
    source = $7
WHERE id = $1
RETURNING id, company_id, category, topic, title, content, tags, source, is_active, search_vector, created_at, updated_at
`

type UpdateKnowledgeArticleParams struct {
	ID      int64       `json:"id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
	Column4 interface{} `json:"column_4"`
	Column5 interface{} `json:"column_5"`
	Tags    []string    `json:"tags"`
	Source  *string     `json:"source"`
}

func (q *Queries) UpdateKnowledgeArticle(ctx context.Context, arg UpdateKnowledgeArticleParams) (KnowledgeArticle, error) {
	row := q.db.QueryRow(ctx, updateKnowledgeArticle,
		arg.ID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Tags,
		arg.Source,
	)
	var i KnowledgeArticle
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Category,
		&i.Topic,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.Source,
		&i.IsActive,
		&i.SearchVector,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
