// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nps.sql

package store

import (
	"context"
	"time"
)

const getLastNPSFeedback = `-- name: GetLastNPSFeedback :one
SELECT created_at FROM nps_feedback
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT 1
`

// Returns the most recent NPS submission by a user (to check cooldown).
func (q *Queries) GetLastNPSFeedback(ctx context.Context, userID int64) (time.Time, error) {
	row := q.db.QueryRow(ctx, getLastNPSFeedback, userID)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const getNPSSummary = `-- name: GetNPSSummary :one
SELECT COUNT(*)::int AS total_responses,
       COALESCE(AVG(score), 0)::float AS avg_score,
       COUNT(*) FILTER (WHERE score >= 9)::int AS promoters,
       COUNT(*) FILTER (WHERE score >= 7 AND score <= 8)::int AS passives,
       COUNT(*) FILTER (WHERE score <= 6)::int AS detractors
FROM nps_feedback
WHERE company_id = $1
`

type GetNPSSummaryRow struct {
	TotalResponses int32   `json:"total_responses"`
	AvgScore       float64 `json:"avg_score"`
	Promoters      int32   `json:"promoters"`
	Passives       int32   `json:"passives"`
	Detractors     int32   `json:"detractors"`
}

// Aggregate NPS stats for a company.
func (q *Queries) GetNPSSummary(ctx context.Context, companyID int64) (GetNPSSummaryRow, error) {
	row := q.db.QueryRow(ctx, getNPSSummary, companyID)
	var i GetNPSSummaryRow
	err := row.Scan(
		&i.TotalResponses,
		&i.AvgScore,
		&i.Promoters,
		&i.Passives,
		&i.Detractors,
	)
	return i, err
}

const insertNPSFeedback = `-- name: InsertNPSFeedback :one
INSERT INTO nps_feedback (company_id, user_id, score, comment)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type InsertNPSFeedbackParams struct {
	CompanyID int64  `json:"company_id"`
	UserID    int64  `json:"user_id"`
	Score     int16  `json:"score"`
	Comment   string `json:"comment"`
}

type InsertNPSFeedbackRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) InsertNPSFeedback(ctx context.Context, arg InsertNPSFeedbackParams) (InsertNPSFeedbackRow, error) {
	row := q.db.QueryRow(ctx, insertNPSFeedback,
		arg.CompanyID,
		arg.UserID,
		arg.Score,
		arg.Comment,
	)
	var i InsertNPSFeedbackRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const listNPSFeedback = `-- name: ListNPSFeedback :many
SELECT nf.id, nf.score, nf.comment, nf.created_at,
       u.first_name, u.last_name, u.email
FROM nps_feedback nf
JOIN users u ON u.id = nf.user_id
WHERE nf.company_id = $1
ORDER BY nf.created_at DESC
LIMIT $2 OFFSET $3
`

type ListNPSFeedbackParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListNPSFeedbackRow struct {
	ID        int64     `json:"id"`
	Score     int16     `json:"score"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
}

// Admin view: list all NPS feedback for a company.
func (q *Queries) ListNPSFeedback(ctx context.Context, arg ListNPSFeedbackParams) ([]ListNPSFeedbackRow, error) {
	rows, err := q.db.Query(ctx, listNPSFeedback, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNPSFeedbackRow{}
	for rows.Next() {
		var i ListNPSFeedbackRow
		if err := rows.Scan(
			&i.ID,
			&i.Score,
			&i.Comment,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
