// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: onboarding_checklist.sql

package store

import (
	"context"
	"encoding/json"
)

const checkCompanyInfoComplete = `-- name: CheckCompanyInfoComplete :one
SELECT (legal_name IS NOT NULL AND tin IS NOT NULL)::boolean AS complete
FROM companies WHERE id = $1
`

func (q *Queries) CheckCompanyInfoComplete(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, checkCompanyInfoComplete, id)
	var complete bool
	err := row.Scan(&complete)
	return complete, err
}

const completeOnboardingChecklist = `-- name: CompleteOnboardingChecklist :exec
UPDATE onboarding_progress
SET completed_at = NOW(), updated_at = NOW()
WHERE company_id = $1 AND user_id = $2 AND persona = $3
`

type CompleteOnboardingChecklistParams struct {
	CompanyID int64  `json:"company_id"`
	UserID    int64  `json:"user_id"`
	Persona   string `json:"persona"`
}

func (q *Queries) CompleteOnboardingChecklist(ctx context.Context, arg CompleteOnboardingChecklistParams) error {
	_, err := q.db.Exec(ctx, completeOnboardingChecklist, arg.CompanyID, arg.UserID, arg.Persona)
	return err
}

const countCompletedPayrollRuns = `-- name: CountCompletedPayrollRuns :one
SELECT COUNT(*) FROM payroll_runs WHERE company_id = $1 AND status = 'completed'
`

func (q *Queries) CountCompletedPayrollRuns(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedPayrollRuns, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDepartmentsByCompany = `-- name: CountDepartmentsByCompany :one
SELECT COUNT(*) FROM departments WHERE company_id = $1
`

func (q *Queries) CountDepartmentsByCompany(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartmentsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEmployeesByCompany = `-- name: CountEmployeesByCompany :one
SELECT COUNT(*) FROM employees WHERE company_id = $1
`

func (q *Queries) CountEmployeesByCompany(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployeesByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNonStatutoryLeaveTypes = `-- name: CountNonStatutoryLeaveTypes :one
SELECT COUNT(*) FROM leave_types WHERE company_id = $1 AND is_statutory = false
`

func (q *Queries) CountNonStatutoryLeaveTypes(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countNonStatutoryLeaveTypes, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPositionsByCompany = `-- name: CountPositionsByCompany :one
SELECT COUNT(*) FROM positions WHERE company_id = $1
`

func (q *Queries) CountPositionsByCompany(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPositionsByCompany, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSalaryStructures = `-- name: CountSalaryStructures :one
SELECT COUNT(*) FROM salary_structures WHERE company_id = $1
`

func (q *Queries) CountSalaryStructures(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countSalaryStructures, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScheduleTemplates = `-- name: CountScheduleTemplates :one
SELECT COUNT(*) FROM schedule_templates WHERE company_id = $1
`

func (q *Queries) CountScheduleTemplates(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countScheduleTemplates, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dismissOnboardingChecklist = `-- name: DismissOnboardingChecklist :exec
INSERT INTO onboarding_progress (company_id, user_id, persona, steps, dismissed)
VALUES ($1, $2, $3, '{}', TRUE)
ON CONFLICT (company_id, user_id, persona)
DO UPDATE SET dismissed = TRUE, updated_at = NOW()
`

type DismissOnboardingChecklistParams struct {
	CompanyID int64  `json:"company_id"`
	UserID    int64  `json:"user_id"`
	Persona   string `json:"persona"`
}

func (q *Queries) DismissOnboardingChecklist(ctx context.Context, arg DismissOnboardingChecklistParams) error {
	_, err := q.db.Exec(ctx, dismissOnboardingChecklist, arg.CompanyID, arg.UserID, arg.Persona)
	return err
}

const getOnboardingChecklist = `-- name: GetOnboardingChecklist :one
SELECT id, company_id, user_id, persona, steps, dismissed, completed_at, created_at, updated_at FROM onboarding_progress
WHERE company_id = $1 AND user_id = $2 AND persona = $3
`

type GetOnboardingChecklistParams struct {
	CompanyID int64  `json:"company_id"`
	UserID    int64  `json:"user_id"`
	Persona   string `json:"persona"`
}

func (q *Queries) GetOnboardingChecklist(ctx context.Context, arg GetOnboardingChecklistParams) (OnboardingProgress, error) {
	row := q.db.QueryRow(ctx, getOnboardingChecklist, arg.CompanyID, arg.UserID, arg.Persona)
	var i OnboardingProgress
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Persona,
		&i.Steps,
		&i.Dismissed,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOnboardingChecklist = `-- name: UpsertOnboardingChecklist :one
INSERT INTO onboarding_progress (company_id, user_id, persona, steps)
VALUES ($1, $2, $3, $4)
ON CONFLICT (company_id, user_id, persona)
DO UPDATE SET steps = $4, updated_at = NOW()
RETURNING id, company_id, user_id, persona, steps, dismissed, completed_at, created_at, updated_at
`

type UpsertOnboardingChecklistParams struct {
	CompanyID int64           `json:"company_id"`
	UserID    int64           `json:"user_id"`
	Persona   string          `json:"persona"`
	Steps     json.RawMessage `json:"steps"`
}

func (q *Queries) UpsertOnboardingChecklist(ctx context.Context, arg UpsertOnboardingChecklistParams) (OnboardingProgress, error) {
	row := q.db.QueryRow(ctx, upsertOnboardingChecklist,
		arg.CompanyID,
		arg.UserID,
		arg.Persona,
		arg.Steps,
	)
	var i OnboardingProgress
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.Persona,
		&i.Steps,
		&i.Dismissed,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
