// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payroll_auto.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestRunForCycle = `-- name: GetLatestRunForCycle :one
SELECT id, company_id, cycle_id, run_type, run_number, total_employees, total_gross, total_deductions, total_net, status, error_message, initiated_by, completed_at, created_at FROM payroll_runs
WHERE cycle_id = $1 AND company_id = $2
ORDER BY id DESC
LIMIT 1
`

type GetLatestRunForCycleParams struct {
	CycleID   int64 `json:"cycle_id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetLatestRunForCycle(ctx context.Context, arg GetLatestRunForCycleParams) (PayrollRun, error) {
	row := q.db.QueryRow(ctx, getLatestRunForCycle, arg.CycleID, arg.CompanyID)
	var i PayrollRun
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CycleID,
		&i.RunType,
		&i.RunNumber,
		&i.TotalEmployees,
		&i.TotalGross,
		&i.TotalDeductions,
		&i.TotalNet,
		&i.Status,
		&i.ErrorMessage,
		&i.InitiatedBy,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPayrollAutoConfig = `-- name: GetPayrollAutoConfig :one
SELECT id, company_id, auto_run_enabled, days_before_pay, auto_approve_enabled, max_auto_approve_amount, notify_on_auto, created_at, updated_at FROM payroll_auto_config WHERE company_id = $1
`

func (q *Queries) GetPayrollAutoConfig(ctx context.Context, companyID int64) (PayrollAutoConfig, error) {
	row := q.db.QueryRow(ctx, getPayrollAutoConfig, companyID)
	var i PayrollAutoConfig
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AutoRunEnabled,
		&i.DaysBeforePay,
		&i.AutoApproveEnabled,
		&i.MaxAutoApproveAmount,
		&i.NotifyOnAuto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPayrollAutoLog = `-- name: InsertPayrollAutoLog :one
INSERT INTO payroll_auto_log (company_id, cycle_id, run_id, action, detail)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, company_id, cycle_id, run_id, action, detail, created_at
`

type InsertPayrollAutoLogParams struct {
	CompanyID int64   `json:"company_id"`
	CycleID   int64   `json:"cycle_id"`
	RunID     *int64  `json:"run_id"`
	Action    string  `json:"action"`
	Detail    *string `json:"detail"`
}

func (q *Queries) InsertPayrollAutoLog(ctx context.Context, arg InsertPayrollAutoLogParams) (PayrollAutoLog, error) {
	row := q.db.QueryRow(ctx, insertPayrollAutoLog,
		arg.CompanyID,
		arg.CycleID,
		arg.RunID,
		arg.Action,
		arg.Detail,
	)
	var i PayrollAutoLog
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.CycleID,
		&i.RunID,
		&i.Action,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const listCompaniesWithAutoRun = `-- name: ListCompaniesWithAutoRun :many
SELECT pac.id, pac.company_id, pac.auto_run_enabled, pac.days_before_pay, pac.auto_approve_enabled, pac.max_auto_approve_amount, pac.notify_on_auto, pac.created_at, pac.updated_at, c.name AS company_name
FROM payroll_auto_config pac
JOIN companies c ON c.id = pac.company_id
WHERE pac.auto_run_enabled = true
`

type ListCompaniesWithAutoRunRow struct {
	ID                   int64          `json:"id"`
	CompanyID            int64          `json:"company_id"`
	AutoRunEnabled       bool           `json:"auto_run_enabled"`
	DaysBeforePay        int32          `json:"days_before_pay"`
	AutoApproveEnabled   bool           `json:"auto_approve_enabled"`
	MaxAutoApproveAmount pgtype.Numeric `json:"max_auto_approve_amount"`
	NotifyOnAuto         bool           `json:"notify_on_auto"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	CompanyName          string         `json:"company_name"`
}

func (q *Queries) ListCompaniesWithAutoRun(ctx context.Context) ([]ListCompaniesWithAutoRunRow, error) {
	rows, err := q.db.Query(ctx, listCompaniesWithAutoRun)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesWithAutoRunRow{}
	for rows.Next() {
		var i ListCompaniesWithAutoRunRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.AutoRunEnabled,
			&i.DaysBeforePay,
			&i.AutoApproveEnabled,
			&i.MaxAutoApproveAmount,
			&i.NotifyOnAuto,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftCyclesForAutoRun = `-- name: ListDraftCyclesForAutoRun :many
SELECT pc.id, pc.company_id, pc.name, pc.period_start, pc.period_end, pc.pay_date, pc.cycle_type, pc.status, pc.created_by, pc.approved_by, pc.approved_at, pc.created_at, pc.updated_at, pc.is_locked, pc.locked_at, pc.locked_by
FROM payroll_cycles pc
WHERE pc.company_id = $1
  AND pc.status = 'draft'
  AND pc.pay_date - $2::int <= CURRENT_DATE
  AND pc.pay_date >= CURRENT_DATE
`

type ListDraftCyclesForAutoRunParams struct {
	CompanyID int64 `json:"company_id"`
	Column2   int32 `json:"column_2"`
}

func (q *Queries) ListDraftCyclesForAutoRun(ctx context.Context, arg ListDraftCyclesForAutoRunParams) ([]PayrollCycle, error) {
	rows, err := q.db.Query(ctx, listDraftCyclesForAutoRun, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayrollCycle{}
	for rows.Next() {
		var i PayrollCycle
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.PayDate,
			&i.CycleType,
			&i.Status,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsLocked,
			&i.LockedAt,
			&i.LockedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollAutoLogs = `-- name: ListPayrollAutoLogs :many
SELECT id, company_id, cycle_id, run_id, action, detail, created_at FROM payroll_auto_log
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPayrollAutoLogsParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListPayrollAutoLogs(ctx context.Context, arg ListPayrollAutoLogsParams) ([]PayrollAutoLog, error) {
	rows, err := q.db.Query(ctx, listPayrollAutoLogs, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PayrollAutoLog{}
	for rows.Next() {
		var i PayrollAutoLog
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.CycleID,
			&i.RunID,
			&i.Action,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPayrollAutoConfig = `-- name: UpsertPayrollAutoConfig :one
INSERT INTO payroll_auto_config (company_id, auto_run_enabled, days_before_pay, auto_approve_enabled, max_auto_approve_amount, notify_on_auto)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (company_id) DO UPDATE SET
    auto_run_enabled = EXCLUDED.auto_run_enabled,
    days_before_pay = EXCLUDED.days_before_pay,
    auto_approve_enabled = EXCLUDED.auto_approve_enabled,
    max_auto_approve_amount = EXCLUDED.max_auto_approve_amount,
    notify_on_auto = EXCLUDED.notify_on_auto,
    updated_at = NOW()
RETURNING id, company_id, auto_run_enabled, days_before_pay, auto_approve_enabled, max_auto_approve_amount, notify_on_auto, created_at, updated_at
`

type UpsertPayrollAutoConfigParams struct {
	CompanyID            int64          `json:"company_id"`
	AutoRunEnabled       bool           `json:"auto_run_enabled"`
	DaysBeforePay        int32          `json:"days_before_pay"`
	AutoApproveEnabled   bool           `json:"auto_approve_enabled"`
	MaxAutoApproveAmount pgtype.Numeric `json:"max_auto_approve_amount"`
	NotifyOnAuto         bool           `json:"notify_on_auto"`
}

func (q *Queries) UpsertPayrollAutoConfig(ctx context.Context, arg UpsertPayrollAutoConfigParams) (PayrollAutoConfig, error) {
	row := q.db.QueryRow(ctx, upsertPayrollAutoConfig,
		arg.CompanyID,
		arg.AutoRunEnabled,
		arg.DaysBeforePay,
		arg.AutoApproveEnabled,
		arg.MaxAutoApproveAmount,
		arg.NotifyOnAuto,
	)
	var i PayrollAutoConfig
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.AutoRunEnabled,
		&i.DaysBeforePay,
		&i.AutoApproveEnabled,
		&i.MaxAutoApproveAmount,
		&i.NotifyOnAuto,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
