// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: performance.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (company_id, employee_id, review_cycle_id, title, description, category, weight, target_value, due_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, employee_id, review_cycle_id, title, description, category, weight, target_value, actual_value, status, due_date, completed_at, self_rating, manager_rating, created_at, updated_at
`

type CreateGoalParams struct {
	CompanyID     int64          `json:"company_id"`
	EmployeeID    int64          `json:"employee_id"`
	ReviewCycleID *int64         `json:"review_cycle_id"`
	Title         string         `json:"title"`
	Description   *string        `json:"description"`
	Category      string         `json:"category"`
	Weight        pgtype.Numeric `json:"weight"`
	TargetValue   *string        `json:"target_value"`
	DueDate       pgtype.Date    `json:"due_date"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.CompanyID,
		arg.EmployeeID,
		arg.ReviewCycleID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Weight,
		arg.TargetValue,
		arg.DueDate,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ReviewCycleID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Weight,
		&i.TargetValue,
		&i.ActualValue,
		&i.Status,
		&i.DueDate,
		&i.CompletedAt,
		&i.SelfRating,
		&i.ManagerRating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPerformanceReview = `-- name: CreatePerformanceReview :one
INSERT INTO performance_reviews (company_id, review_cycle_id, employee_id, reviewer_id)
VALUES ($1, $2, $3, $4)
RETURNING id, company_id, review_cycle_id, employee_id, reviewer_id, status, self_rating, self_comments, self_submitted_at, manager_rating, manager_comments, manager_submitted_at, final_rating, final_comments, strengths, improvements, created_at, updated_at
`

type CreatePerformanceReviewParams struct {
	CompanyID     int64  `json:"company_id"`
	ReviewCycleID int64  `json:"review_cycle_id"`
	EmployeeID    int64  `json:"employee_id"`
	ReviewerID    *int64 `json:"reviewer_id"`
}

func (q *Queries) CreatePerformanceReview(ctx context.Context, arg CreatePerformanceReviewParams) (PerformanceReview, error) {
	row := q.db.QueryRow(ctx, createPerformanceReview,
		arg.CompanyID,
		arg.ReviewCycleID,
		arg.EmployeeID,
		arg.ReviewerID,
	)
	var i PerformanceReview
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ReviewCycleID,
		&i.EmployeeID,
		&i.ReviewerID,
		&i.Status,
		&i.SelfRating,
		&i.SelfComments,
		&i.SelfSubmittedAt,
		&i.ManagerRating,
		&i.ManagerComments,
		&i.ManagerSubmittedAt,
		&i.FinalRating,
		&i.FinalComments,
		&i.Strengths,
		&i.Improvements,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReviewCycle = `-- name: CreateReviewCycle :one
INSERT INTO review_cycles (company_id, name, cycle_type, period_start, period_end, review_deadline, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, name, cycle_type, period_start, period_end, review_deadline, status, created_by, created_at, updated_at
`

type CreateReviewCycleParams struct {
	CompanyID      int64       `json:"company_id"`
	Name           string      `json:"name"`
	CycleType      string      `json:"cycle_type"`
	PeriodStart    time.Time   `json:"period_start"`
	PeriodEnd      time.Time   `json:"period_end"`
	ReviewDeadline pgtype.Date `json:"review_deadline"`
	CreatedBy      *int64      `json:"created_by"`
}

func (q *Queries) CreateReviewCycle(ctx context.Context, arg CreateReviewCycleParams) (ReviewCycle, error) {
	row := q.db.QueryRow(ctx, createReviewCycle,
		arg.CompanyID,
		arg.Name,
		arg.CycleType,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.ReviewDeadline,
		arg.CreatedBy,
	)
	var i ReviewCycle
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.CycleType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.ReviewDeadline,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPerformanceReview = `-- name: GetPerformanceReview :one
SELECT id, company_id, review_cycle_id, employee_id, reviewer_id, status, self_rating, self_comments, self_submitted_at, manager_rating, manager_comments, manager_submitted_at, final_rating, final_comments, strengths, improvements, created_at, updated_at FROM performance_reviews WHERE id = $1 AND company_id = $2
`

type GetPerformanceReviewParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetPerformanceReview(ctx context.Context, arg GetPerformanceReviewParams) (PerformanceReview, error) {
	row := q.db.QueryRow(ctx, getPerformanceReview, arg.ID, arg.CompanyID)
	var i PerformanceReview
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ReviewCycleID,
		&i.EmployeeID,
		&i.ReviewerID,
		&i.Status,
		&i.SelfRating,
		&i.SelfComments,
		&i.SelfSubmittedAt,
		&i.ManagerRating,
		&i.ManagerComments,
		&i.ManagerSubmittedAt,
		&i.FinalRating,
		&i.FinalComments,
		&i.Strengths,
		&i.Improvements,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewByEmployee = `-- name: GetReviewByEmployee :one
SELECT id, company_id, review_cycle_id, employee_id, reviewer_id, status, self_rating, self_comments, self_submitted_at, manager_rating, manager_comments, manager_submitted_at, final_rating, final_comments, strengths, improvements, created_at, updated_at FROM performance_reviews
WHERE company_id = $1 AND review_cycle_id = $2 AND employee_id = $3
`

type GetReviewByEmployeeParams struct {
	CompanyID     int64 `json:"company_id"`
	ReviewCycleID int64 `json:"review_cycle_id"`
	EmployeeID    int64 `json:"employee_id"`
}

func (q *Queries) GetReviewByEmployee(ctx context.Context, arg GetReviewByEmployeeParams) (PerformanceReview, error) {
	row := q.db.QueryRow(ctx, getReviewByEmployee, arg.CompanyID, arg.ReviewCycleID, arg.EmployeeID)
	var i PerformanceReview
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ReviewCycleID,
		&i.EmployeeID,
		&i.ReviewerID,
		&i.Status,
		&i.SelfRating,
		&i.SelfComments,
		&i.SelfSubmittedAt,
		&i.ManagerRating,
		&i.ManagerComments,
		&i.ManagerSubmittedAt,
		&i.FinalRating,
		&i.FinalComments,
		&i.Strengths,
		&i.Improvements,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewCycle = `-- name: GetReviewCycle :one
SELECT id, company_id, name, cycle_type, period_start, period_end, review_deadline, status, created_by, created_at, updated_at FROM review_cycles WHERE id = $1 AND company_id = $2
`

type GetReviewCycleParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetReviewCycle(ctx context.Context, arg GetReviewCycleParams) (ReviewCycle, error) {
	row := q.db.QueryRow(ctx, getReviewCycle, arg.ID, arg.CompanyID)
	var i ReviewCycle
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.CycleType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.ReviewDeadline,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewStats = `-- name: GetReviewStats :many
SELECT
    CASE
        WHEN final_rating = 5 THEN 'Outstanding'
        WHEN final_rating = 4 THEN 'Exceeds'
        WHEN final_rating = 3 THEN 'Meets'
        WHEN final_rating = 2 THEN 'Below'
        WHEN final_rating = 1 THEN 'Unsatisfactory'
        ELSE 'Pending'
    END as rating_label,
    COUNT(*) as count
FROM performance_reviews
WHERE company_id = $1 AND review_cycle_id = $2
GROUP BY final_rating
ORDER BY final_rating DESC NULLS LAST
`

type GetReviewStatsParams struct {
	CompanyID     int64 `json:"company_id"`
	ReviewCycleID int64 `json:"review_cycle_id"`
}

type GetReviewStatsRow struct {
	RatingLabel string `json:"rating_label"`
	Count       int64  `json:"count"`
}

func (q *Queries) GetReviewStats(ctx context.Context, arg GetReviewStatsParams) ([]GetReviewStatsRow, error) {
	rows, err := q.db.Query(ctx, getReviewStats, arg.CompanyID, arg.ReviewCycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReviewStatsRow{}
	for rows.Next() {
		var i GetReviewStatsRow
		if err := rows.Scan(&i.RatingLabel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const initiateReviews = `-- name: InitiateReviews :exec
INSERT INTO performance_reviews (company_id, review_cycle_id, employee_id, reviewer_id)
SELECT $1, $2, e.id, e.manager_id
FROM employees e
WHERE e.company_id = $1 AND e.status = 'active'
ON CONFLICT (review_cycle_id, employee_id) DO NOTHING
`

type InitiateReviewsParams struct {
	CompanyID     int64 `json:"company_id"`
	ReviewCycleID int64 `json:"review_cycle_id"`
}

func (q *Queries) InitiateReviews(ctx context.Context, arg InitiateReviewsParams) error {
	_, err := q.db.Exec(ctx, initiateReviews, arg.CompanyID, arg.ReviewCycleID)
	return err
}

const listGoals = `-- name: ListGoals :many
SELECT id, company_id, employee_id, review_cycle_id, title, description, category, weight, target_value, actual_value, status, due_date, completed_at, self_rating, manager_rating, created_at, updated_at FROM goals
WHERE company_id = $1 AND employee_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListGoalsParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
	Limit      int32 `json:"limit"`
	Offset     int32 `json:"offset"`
}

func (q *Queries) ListGoals(ctx context.Context, arg ListGoalsParams) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoals,
		arg.CompanyID,
		arg.EmployeeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Goal{}
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.ReviewCycleID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Weight,
			&i.TargetValue,
			&i.ActualValue,
			&i.Status,
			&i.DueDate,
			&i.CompletedAt,
			&i.SelfRating,
			&i.ManagerRating,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByCycle = `-- name: ListGoalsByCycle :many
SELECT g.id, g.company_id, g.employee_id, g.review_cycle_id, g.title, g.description, g.category, g.weight, g.target_value, g.actual_value, g.status, g.due_date, g.completed_at, g.self_rating, g.manager_rating, g.created_at, g.updated_at, e.first_name, e.last_name, e.employee_no
FROM goals g
JOIN employees e ON e.id = g.employee_id
WHERE g.company_id = $1 AND g.review_cycle_id = $2
ORDER BY e.last_name, e.first_name, g.created_at
`

type ListGoalsByCycleParams struct {
	CompanyID     int64  `json:"company_id"`
	ReviewCycleID *int64 `json:"review_cycle_id"`
}

type ListGoalsByCycleRow struct {
	ID            int64              `json:"id"`
	CompanyID     int64              `json:"company_id"`
	EmployeeID    int64              `json:"employee_id"`
	ReviewCycleID *int64             `json:"review_cycle_id"`
	Title         string             `json:"title"`
	Description   *string            `json:"description"`
	Category      string             `json:"category"`
	Weight        pgtype.Numeric     `json:"weight"`
	TargetValue   *string            `json:"target_value"`
	ActualValue   *string            `json:"actual_value"`
	Status        string             `json:"status"`
	DueDate       pgtype.Date        `json:"due_date"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	SelfRating    *int32             `json:"self_rating"`
	ManagerRating *int32             `json:"manager_rating"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	EmployeeNo    string             `json:"employee_no"`
}

func (q *Queries) ListGoalsByCycle(ctx context.Context, arg ListGoalsByCycleParams) ([]ListGoalsByCycleRow, error) {
	rows, err := q.db.Query(ctx, listGoalsByCycle, arg.CompanyID, arg.ReviewCycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGoalsByCycleRow{}
	for rows.Next() {
		var i ListGoalsByCycleRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.ReviewCycleID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Weight,
			&i.TargetValue,
			&i.ActualValue,
			&i.Status,
			&i.DueDate,
			&i.CompletedAt,
			&i.SelfRating,
			&i.ManagerRating,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.EmployeeNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyReviews = `-- name: ListMyReviews :many
SELECT pr.id, pr.company_id, pr.review_cycle_id, pr.employee_id, pr.reviewer_id, pr.status, pr.self_rating, pr.self_comments, pr.self_submitted_at, pr.manager_rating, pr.manager_comments, pr.manager_submitted_at, pr.final_rating, pr.final_comments, pr.strengths, pr.improvements, pr.created_at, pr.updated_at, rc.name as cycle_name, rc.cycle_type, rc.period_start, rc.period_end
FROM performance_reviews pr
JOIN review_cycles rc ON rc.id = pr.review_cycle_id
WHERE pr.employee_id = $1
ORDER BY rc.period_start DESC
`

type ListMyReviewsRow struct {
	ID                 int64              `json:"id"`
	CompanyID          int64              `json:"company_id"`
	ReviewCycleID      int64              `json:"review_cycle_id"`
	EmployeeID         int64              `json:"employee_id"`
	ReviewerID         *int64             `json:"reviewer_id"`
	Status             string             `json:"status"`
	SelfRating         *int32             `json:"self_rating"`
	SelfComments       *string            `json:"self_comments"`
	SelfSubmittedAt    pgtype.Timestamptz `json:"self_submitted_at"`
	ManagerRating      *int32             `json:"manager_rating"`
	ManagerComments    *string            `json:"manager_comments"`
	ManagerSubmittedAt pgtype.Timestamptz `json:"manager_submitted_at"`
	FinalRating        *int32             `json:"final_rating"`
	FinalComments      *string            `json:"final_comments"`
	Strengths          *string            `json:"strengths"`
	Improvements       *string            `json:"improvements"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	CycleName          string             `json:"cycle_name"`
	CycleType          string             `json:"cycle_type"`
	PeriodStart        time.Time          `json:"period_start"`
	PeriodEnd          time.Time          `json:"period_end"`
}

func (q *Queries) ListMyReviews(ctx context.Context, employeeID int64) ([]ListMyReviewsRow, error) {
	rows, err := q.db.Query(ctx, listMyReviews, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyReviewsRow{}
	for rows.Next() {
		var i ListMyReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ReviewCycleID,
			&i.EmployeeID,
			&i.ReviewerID,
			&i.Status,
			&i.SelfRating,
			&i.SelfComments,
			&i.SelfSubmittedAt,
			&i.ManagerRating,
			&i.ManagerComments,
			&i.ManagerSubmittedAt,
			&i.FinalRating,
			&i.FinalComments,
			&i.Strengths,
			&i.Improvements,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CycleName,
			&i.CycleType,
			&i.PeriodStart,
			&i.PeriodEnd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewCycles = `-- name: ListReviewCycles :many
SELECT id, company_id, name, cycle_type, period_start, period_end, review_deadline, status, created_by, created_at, updated_at FROM review_cycles
WHERE company_id = $1
ORDER BY period_start DESC
LIMIT $2 OFFSET $3
`

type ListReviewCyclesParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListReviewCycles(ctx context.Context, arg ListReviewCyclesParams) ([]ReviewCycle, error) {
	rows, err := q.db.Query(ctx, listReviewCycles, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReviewCycle{}
	for rows.Next() {
		var i ReviewCycle
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.CycleType,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.ReviewDeadline,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByCycle = `-- name: ListReviewsByCycle :many
SELECT pr.id, pr.company_id, pr.review_cycle_id, pr.employee_id, pr.reviewer_id, pr.status, pr.self_rating, pr.self_comments, pr.self_submitted_at, pr.manager_rating, pr.manager_comments, pr.manager_submitted_at, pr.final_rating, pr.final_comments, pr.strengths, pr.improvements, pr.created_at, pr.updated_at, e.first_name, e.last_name, e.employee_no,
    rev.first_name as reviewer_first_name, rev.last_name as reviewer_last_name
FROM performance_reviews pr
JOIN employees e ON e.id = pr.employee_id
LEFT JOIN employees rev ON rev.id = pr.reviewer_id
WHERE pr.company_id = $1 AND pr.review_cycle_id = $2
ORDER BY e.last_name, e.first_name
`

type ListReviewsByCycleParams struct {
	CompanyID     int64 `json:"company_id"`
	ReviewCycleID int64 `json:"review_cycle_id"`
}

type ListReviewsByCycleRow struct {
	ID                 int64              `json:"id"`
	CompanyID          int64              `json:"company_id"`
	ReviewCycleID      int64              `json:"review_cycle_id"`
	EmployeeID         int64              `json:"employee_id"`
	ReviewerID         *int64             `json:"reviewer_id"`
	Status             string             `json:"status"`
	SelfRating         *int32             `json:"self_rating"`
	SelfComments       *string            `json:"self_comments"`
	SelfSubmittedAt    pgtype.Timestamptz `json:"self_submitted_at"`
	ManagerRating      *int32             `json:"manager_rating"`
	ManagerComments    *string            `json:"manager_comments"`
	ManagerSubmittedAt pgtype.Timestamptz `json:"manager_submitted_at"`
	FinalRating        *int32             `json:"final_rating"`
	FinalComments      *string            `json:"final_comments"`
	Strengths          *string            `json:"strengths"`
	Improvements       *string            `json:"improvements"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          time.Time          `json:"updated_at"`
	FirstName          string             `json:"first_name"`
	LastName           string             `json:"last_name"`
	EmployeeNo         string             `json:"employee_no"`
	ReviewerFirstName  *string            `json:"reviewer_first_name"`
	ReviewerLastName   *string            `json:"reviewer_last_name"`
}

func (q *Queries) ListReviewsByCycle(ctx context.Context, arg ListReviewsByCycleParams) ([]ListReviewsByCycleRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByCycle, arg.CompanyID, arg.ReviewCycleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByCycleRow{}
	for rows.Next() {
		var i ListReviewsByCycleRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.ReviewCycleID,
			&i.EmployeeID,
			&i.ReviewerID,
			&i.Status,
			&i.SelfRating,
			&i.SelfComments,
			&i.SelfSubmittedAt,
			&i.ManagerRating,
			&i.ManagerComments,
			&i.ManagerSubmittedAt,
			&i.FinalRating,
			&i.FinalComments,
			&i.Strengths,
			&i.Improvements,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.EmployeeNo,
			&i.ReviewerFirstName,
			&i.ReviewerLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitManagerReview = `-- name: SubmitManagerReview :one
UPDATE performance_reviews SET
    manager_rating = $3,
    manager_comments = $4,
    strengths = $5,
    improvements = $6,
    final_rating = $7,
    final_comments = $8,
    manager_submitted_at = NOW(),
    status = 'completed',
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, review_cycle_id, employee_id, reviewer_id, status, self_rating, self_comments, self_submitted_at, manager_rating, manager_comments, manager_submitted_at, final_rating, final_comments, strengths, improvements, created_at, updated_at
`

type SubmitManagerReviewParams struct {
	ID              int64   `json:"id"`
	CompanyID       int64   `json:"company_id"`
	ManagerRating   *int32  `json:"manager_rating"`
	ManagerComments *string `json:"manager_comments"`
	Strengths       *string `json:"strengths"`
	Improvements    *string `json:"improvements"`
	FinalRating     *int32  `json:"final_rating"`
	FinalComments   *string `json:"final_comments"`
}

func (q *Queries) SubmitManagerReview(ctx context.Context, arg SubmitManagerReviewParams) (PerformanceReview, error) {
	row := q.db.QueryRow(ctx, submitManagerReview,
		arg.ID,
		arg.CompanyID,
		arg.ManagerRating,
		arg.ManagerComments,
		arg.Strengths,
		arg.Improvements,
		arg.FinalRating,
		arg.FinalComments,
	)
	var i PerformanceReview
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ReviewCycleID,
		&i.EmployeeID,
		&i.ReviewerID,
		&i.Status,
		&i.SelfRating,
		&i.SelfComments,
		&i.SelfSubmittedAt,
		&i.ManagerRating,
		&i.ManagerComments,
		&i.ManagerSubmittedAt,
		&i.FinalRating,
		&i.FinalComments,
		&i.Strengths,
		&i.Improvements,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitSelfReview = `-- name: SubmitSelfReview :one
UPDATE performance_reviews SET
    self_rating = $3,
    self_comments = $4,
    self_submitted_at = NOW(),
    status = 'manager_review',
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, review_cycle_id, employee_id, reviewer_id, status, self_rating, self_comments, self_submitted_at, manager_rating, manager_comments, manager_submitted_at, final_rating, final_comments, strengths, improvements, created_at, updated_at
`

type SubmitSelfReviewParams struct {
	ID           int64   `json:"id"`
	CompanyID    int64   `json:"company_id"`
	SelfRating   *int32  `json:"self_rating"`
	SelfComments *string `json:"self_comments"`
}

func (q *Queries) SubmitSelfReview(ctx context.Context, arg SubmitSelfReviewParams) (PerformanceReview, error) {
	row := q.db.QueryRow(ctx, submitSelfReview,
		arg.ID,
		arg.CompanyID,
		arg.SelfRating,
		arg.SelfComments,
	)
	var i PerformanceReview
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.ReviewCycleID,
		&i.EmployeeID,
		&i.ReviewerID,
		&i.Status,
		&i.SelfRating,
		&i.SelfComments,
		&i.SelfSubmittedAt,
		&i.ManagerRating,
		&i.ManagerComments,
		&i.ManagerSubmittedAt,
		&i.FinalRating,
		&i.FinalComments,
		&i.Strengths,
		&i.Improvements,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals SET
    title = COALESCE(NULLIF($3, ''), title),
    description = COALESCE($4, description),
    status = COALESCE(NULLIF($5, ''), status),
    actual_value = COALESCE($6, actual_value),
    self_rating = COALESCE($7, self_rating),
    manager_rating = COALESCE($8, manager_rating),
    completed_at = CASE WHEN $5 = 'completed' THEN NOW() ELSE completed_at END,
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, employee_id, review_cycle_id, title, description, category, weight, target_value, actual_value, status, due_date, completed_at, self_rating, manager_rating, created_at, updated_at
`

type UpdateGoalParams struct {
	ID            int64       `json:"id"`
	CompanyID     int64       `json:"company_id"`
	Column3       interface{} `json:"column_3"`
	Description   *string     `json:"description"`
	Column5       interface{} `json:"column_5"`
	ActualValue   *string     `json:"actual_value"`
	SelfRating    *int32      `json:"self_rating"`
	ManagerRating *int32      `json:"manager_rating"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.CompanyID,
		arg.Column3,
		arg.Description,
		arg.Column5,
		arg.ActualValue,
		arg.SelfRating,
		arg.ManagerRating,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.ReviewCycleID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Weight,
		&i.TargetValue,
		&i.ActualValue,
		&i.Status,
		&i.DueDate,
		&i.CompletedAt,
		&i.SelfRating,
		&i.ManagerRating,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateReviewCycleStatus = `-- name: UpdateReviewCycleStatus :one
UPDATE review_cycles SET status = $3, updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, cycle_type, period_start, period_end, review_deadline, status, created_by, created_at, updated_at
`

type UpdateReviewCycleStatusParams struct {
	ID        int64  `json:"id"`
	CompanyID int64  `json:"company_id"`
	Status    string `json:"status"`
}

func (q *Queries) UpdateReviewCycleStatus(ctx context.Context, arg UpdateReviewCycleStatusParams) (ReviewCycle, error) {
	row := q.db.QueryRow(ctx, updateReviewCycleStatus, arg.ID, arg.CompanyID, arg.Status)
	var i ReviewCycle
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.CycleType,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.ReviewDeadline,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
