// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pulse_survey.sql

package store

import (
	"context"
	"time"
)

const closePulseRound = `-- name: ClosePulseRound :exec
UPDATE pulse_rounds SET status = 'closed', closed_at = NOW()
WHERE id = $1
`

func (q *Queries) ClosePulseRound(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, closePulseRound, id)
	return err
}

const countActiveEmployees = `-- name: CountActiveEmployees :one
SELECT COUNT(*) as count FROM employees
WHERE company_id = $1 AND status = 'active'
`

func (q *Queries) CountActiveEmployees(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveEmployees, companyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPulseQuestion = `-- name: CreatePulseQuestion :one
INSERT INTO pulse_questions (survey_id, question, question_type, sort_order, is_required)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, survey_id, question, question_type, sort_order, is_required
`

type CreatePulseQuestionParams struct {
	SurveyID     int64  `json:"survey_id"`
	Question     string `json:"question"`
	QuestionType string `json:"question_type"`
	SortOrder    int32  `json:"sort_order"`
	IsRequired   bool   `json:"is_required"`
}

func (q *Queries) CreatePulseQuestion(ctx context.Context, arg CreatePulseQuestionParams) (PulseQuestion, error) {
	row := q.db.QueryRow(ctx, createPulseQuestion,
		arg.SurveyID,
		arg.Question,
		arg.QuestionType,
		arg.SortOrder,
		arg.IsRequired,
	)
	var i PulseQuestion
	err := row.Scan(
		&i.ID,
		&i.SurveyID,
		&i.Question,
		&i.QuestionType,
		&i.SortOrder,
		&i.IsRequired,
	)
	return i, err
}

const createPulseRound = `-- name: CreatePulseRound :one
INSERT INTO pulse_rounds (survey_id, company_id, round_date, total_sent)
VALUES ($1, $2, $3, $4)
RETURNING id, survey_id, company_id, round_date, status, total_sent, total_responded, closed_at, created_at
`

type CreatePulseRoundParams struct {
	SurveyID  int64     `json:"survey_id"`
	CompanyID int64     `json:"company_id"`
	RoundDate time.Time `json:"round_date"`
	TotalSent int32     `json:"total_sent"`
}

func (q *Queries) CreatePulseRound(ctx context.Context, arg CreatePulseRoundParams) (PulseRound, error) {
	row := q.db.QueryRow(ctx, createPulseRound,
		arg.SurveyID,
		arg.CompanyID,
		arg.RoundDate,
		arg.TotalSent,
	)
	var i PulseRound
	err := row.Scan(
		&i.ID,
		&i.SurveyID,
		&i.CompanyID,
		&i.RoundDate,
		&i.Status,
		&i.TotalSent,
		&i.TotalResponded,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createPulseSurvey = `-- name: CreatePulseSurvey :one
INSERT INTO pulse_surveys (company_id, title, description, frequency, is_anonymous, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, title, description, frequency, is_anonymous, is_active, created_by, created_at, updated_at
`

type CreatePulseSurveyParams struct {
	CompanyID   int64   `json:"company_id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Frequency   string  `json:"frequency"`
	IsAnonymous bool    `json:"is_anonymous"`
	CreatedBy   int64   `json:"created_by"`
}

func (q *Queries) CreatePulseSurvey(ctx context.Context, arg CreatePulseSurveyParams) (PulseSurvey, error) {
	row := q.db.QueryRow(ctx, createPulseSurvey,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.Frequency,
		arg.IsAnonymous,
		arg.CreatedBy,
	)
	var i PulseSurvey
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Frequency,
		&i.IsAnonymous,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivatePulseSurvey = `-- name: DeactivatePulseSurvey :exec
UPDATE pulse_surveys SET is_active = false, updated_at = NOW()
WHERE id = $1 AND company_id = $2
`

type DeactivatePulseSurveyParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) DeactivatePulseSurvey(ctx context.Context, arg DeactivatePulseSurveyParams) error {
	_, err := q.db.Exec(ctx, deactivatePulseSurvey, arg.ID, arg.CompanyID)
	return err
}

const deletePulseQuestions = `-- name: DeletePulseQuestions :exec
DELETE FROM pulse_questions WHERE survey_id = $1
`

func (q *Queries) DeletePulseQuestions(ctx context.Context, surveyID int64) error {
	_, err := q.db.Exec(ctx, deletePulseQuestions, surveyID)
	return err
}

const getOpenRound = `-- name: GetOpenRound :one
SELECT id, survey_id, company_id, round_date, status, total_sent, total_responded, closed_at, created_at FROM pulse_rounds
WHERE survey_id = $1 AND company_id = $2 AND status = 'open'
ORDER BY round_date DESC LIMIT 1
`

type GetOpenRoundParams struct {
	SurveyID  int64 `json:"survey_id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetOpenRound(ctx context.Context, arg GetOpenRoundParams) (PulseRound, error) {
	row := q.db.QueryRow(ctx, getOpenRound, arg.SurveyID, arg.CompanyID)
	var i PulseRound
	err := row.Scan(
		&i.ID,
		&i.SurveyID,
		&i.CompanyID,
		&i.RoundDate,
		&i.Status,
		&i.TotalSent,
		&i.TotalResponded,
		&i.ClosedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPulseSurvey = `-- name: GetPulseSurvey :one
SELECT id, company_id, title, description, frequency, is_anonymous, is_active, created_by, created_at, updated_at FROM pulse_surveys WHERE id = $1 AND company_id = $2
`

type GetPulseSurveyParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetPulseSurvey(ctx context.Context, arg GetPulseSurveyParams) (PulseSurvey, error) {
	row := q.db.QueryRow(ctx, getPulseSurvey, arg.ID, arg.CompanyID)
	var i PulseSurvey
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Frequency,
		&i.IsAnonymous,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasEmployeeRespondedToRound = `-- name: HasEmployeeRespondedToRound :one
SELECT EXISTS(
    SELECT 1 FROM pulse_responses
    WHERE round_id = $1 AND employee_id = $2
) as responded
`

type HasEmployeeRespondedToRoundParams struct {
	RoundID    int64 `json:"round_id"`
	EmployeeID int64 `json:"employee_id"`
}

func (q *Queries) HasEmployeeRespondedToRound(ctx context.Context, arg HasEmployeeRespondedToRoundParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasEmployeeRespondedToRound, arg.RoundID, arg.EmployeeID)
	var responded bool
	err := row.Scan(&responded)
	return responded, err
}

const incrementRoundResponded = `-- name: IncrementRoundResponded :exec
UPDATE pulse_rounds SET total_responded = total_responded + 1
WHERE id = $1
`

func (q *Queries) IncrementRoundResponded(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementRoundResponded, id)
	return err
}

const listActiveSurveysForDistribution = `-- name: ListActiveSurveysForDistribution :many
SELECT ps.id, ps.company_id, ps.title, ps.description, ps.frequency, ps.is_anonymous, ps.is_active, ps.created_by, ps.created_at, ps.updated_at FROM pulse_surveys ps
WHERE ps.company_id = $1
  AND ps.is_active = true
  AND NOT EXISTS (
    SELECT 1 FROM pulse_rounds pr
    WHERE pr.survey_id = ps.id
      AND pr.status = 'open'
      AND pr.round_date >= CURRENT_DATE - INTERVAL '1 day'
  )
`

func (q *Queries) ListActiveSurveysForDistribution(ctx context.Context, companyID int64) ([]PulseSurvey, error) {
	rows, err := q.db.Query(ctx, listActiveSurveysForDistribution, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PulseSurvey{}
	for rows.Next() {
		var i PulseSurvey
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Frequency,
			&i.IsAnonymous,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPulseQuestions = `-- name: ListPulseQuestions :many
SELECT id, survey_id, question, question_type, sort_order, is_required FROM pulse_questions
WHERE survey_id = $1
ORDER BY sort_order
`

func (q *Queries) ListPulseQuestions(ctx context.Context, surveyID int64) ([]PulseQuestion, error) {
	rows, err := q.db.Query(ctx, listPulseQuestions, surveyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PulseQuestion{}
	for rows.Next() {
		var i PulseQuestion
		if err := rows.Scan(
			&i.ID,
			&i.SurveyID,
			&i.Question,
			&i.QuestionType,
			&i.SortOrder,
			&i.IsRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPulseRounds = `-- name: ListPulseRounds :many
SELECT id, survey_id, company_id, round_date, status, total_sent, total_responded, closed_at, created_at FROM pulse_rounds
WHERE survey_id = $1
ORDER BY round_date DESC
LIMIT $2 OFFSET $3
`

type ListPulseRoundsParams struct {
	SurveyID int64 `json:"survey_id"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListPulseRounds(ctx context.Context, arg ListPulseRoundsParams) ([]PulseRound, error) {
	rows, err := q.db.Query(ctx, listPulseRounds, arg.SurveyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PulseRound{}
	for rows.Next() {
		var i PulseRound
		if err := rows.Scan(
			&i.ID,
			&i.SurveyID,
			&i.CompanyID,
			&i.RoundDate,
			&i.Status,
			&i.TotalSent,
			&i.TotalResponded,
			&i.ClosedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPulseSurveys = `-- name: ListPulseSurveys :many
SELECT id, company_id, title, description, frequency, is_anonymous, is_active, created_by, created_at, updated_at FROM pulse_surveys
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPulseSurveysParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListPulseSurveys(ctx context.Context, arg ListPulseSurveysParams) ([]PulseSurvey, error) {
	rows, err := q.db.Query(ctx, listPulseSurveys, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PulseSurvey{}
	for rows.Next() {
		var i PulseSurvey
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Frequency,
			&i.IsAnonymous,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePulseSurvey = `-- name: UpdatePulseSurvey :one
UPDATE pulse_surveys SET
    title = $3,
    description = $4,
    frequency = $5,
    is_anonymous = $6,
    is_active = $7,
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, title, description, frequency, is_anonymous, is_active, created_by, created_at, updated_at
`

type UpdatePulseSurveyParams struct {
	ID          int64   `json:"id"`
	CompanyID   int64   `json:"company_id"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Frequency   string  `json:"frequency"`
	IsAnonymous bool    `json:"is_anonymous"`
	IsActive    bool    `json:"is_active"`
}

func (q *Queries) UpdatePulseSurvey(ctx context.Context, arg UpdatePulseSurveyParams) (PulseSurvey, error) {
	row := q.db.QueryRow(ctx, updatePulseSurvey,
		arg.ID,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.Frequency,
		arg.IsAnonymous,
		arg.IsActive,
	)
	var i PulseSurvey
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Frequency,
		&i.IsAnonymous,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPulseResponse = `-- name: UpsertPulseResponse :exec
INSERT INTO pulse_responses (round_id, question_id, employee_id, company_id, rating, answer_text)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (round_id, question_id, employee_id)
DO UPDATE SET rating = $5, answer_text = $6, submitted_at = NOW()
`

type UpsertPulseResponseParams struct {
	RoundID    int64   `json:"round_id"`
	QuestionID int64   `json:"question_id"`
	EmployeeID int64   `json:"employee_id"`
	CompanyID  int64   `json:"company_id"`
	Rating     *int32  `json:"rating"`
	AnswerText *string `json:"answer_text"`
}

func (q *Queries) UpsertPulseResponse(ctx context.Context, arg UpsertPulseResponseParams) error {
	_, err := q.db.Exec(ctx, upsertPulseResponse,
		arg.RoundID,
		arg.QuestionID,
		arg.EmployeeID,
		arg.CompanyID,
		arg.Rating,
		arg.AnswerText,
	)
	return err
}
