// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recognition.sql

package store

import (
	"context"
	"time"
)

const countRecognitionsReceived = `-- name: CountRecognitionsReceived :one
SELECT COUNT(*) as count FROM recognitions
WHERE to_employee_id = $1 AND company_id = $2
`

type CountRecognitionsReceivedParams struct {
	ToEmployeeID int64 `json:"to_employee_id"`
	CompanyID    int64 `json:"company_id"`
}

func (q *Queries) CountRecognitionsReceived(ctx context.Context, arg CountRecognitionsReceivedParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecognitionsReceived, arg.ToEmployeeID, arg.CompanyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecognition = `-- name: CreateRecognition :one
INSERT INTO recognitions (company_id, from_employee_id, to_employee_id, category, message, is_public, points)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, from_employee_id, to_employee_id, category, message, is_public, points, created_at
`

type CreateRecognitionParams struct {
	CompanyID      int64  `json:"company_id"`
	FromEmployeeID int64  `json:"from_employee_id"`
	ToEmployeeID   int64  `json:"to_employee_id"`
	Category       string `json:"category"`
	Message        string `json:"message"`
	IsPublic       bool   `json:"is_public"`
	Points         int32  `json:"points"`
}

func (q *Queries) CreateRecognition(ctx context.Context, arg CreateRecognitionParams) (Recognition, error) {
	row := q.db.QueryRow(ctx, createRecognition,
		arg.CompanyID,
		arg.FromEmployeeID,
		arg.ToEmployeeID,
		arg.Category,
		arg.Message,
		arg.IsPublic,
		arg.Points,
	)
	var i Recognition
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FromEmployeeID,
		&i.ToEmployeeID,
		&i.Category,
		&i.Message,
		&i.IsPublic,
		&i.Points,
		&i.CreatedAt,
	)
	return i, err
}

const getCategoryBreakdown = `-- name: GetCategoryBreakdown :many
SELECT category, COUNT(*) as count
FROM recognitions
WHERE company_id = $1 AND created_at >= $2
GROUP BY category
ORDER BY count DESC
`

type GetCategoryBreakdownParams struct {
	CompanyID int64     `json:"company_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetCategoryBreakdownRow struct {
	Category string `json:"category"`
	Count    int64  `json:"count"`
}

func (q *Queries) GetCategoryBreakdown(ctx context.Context, arg GetCategoryBreakdownParams) ([]GetCategoryBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getCategoryBreakdown, arg.CompanyID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCategoryBreakdownRow{}
	for rows.Next() {
		var i GetCategoryBreakdownRow
		if err := rows.Scan(&i.Category, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecognitionStats = `-- name: GetRecognitionStats :one
SELECT
    COUNT(*) as total_recognitions,
    COUNT(DISTINCT from_employee_id) as unique_givers,
    COUNT(DISTINCT to_employee_id) as unique_receivers
FROM recognitions
WHERE company_id = $1 AND created_at >= $2
`

type GetRecognitionStatsParams struct {
	CompanyID int64     `json:"company_id"`
	CreatedAt time.Time `json:"created_at"`
}

type GetRecognitionStatsRow struct {
	TotalRecognitions int64 `json:"total_recognitions"`
	UniqueGivers      int64 `json:"unique_givers"`
	UniqueReceivers   int64 `json:"unique_receivers"`
}

func (q *Queries) GetRecognitionStats(ctx context.Context, arg GetRecognitionStatsParams) (GetRecognitionStatsRow, error) {
	row := q.db.QueryRow(ctx, getRecognitionStats, arg.CompanyID, arg.CreatedAt)
	var i GetRecognitionStatsRow
	err := row.Scan(&i.TotalRecognitions, &i.UniqueGivers, &i.UniqueReceivers)
	return i, err
}

const getTopRecognized = `-- name: GetTopRecognized :many
SELECT te.id as employee_id, te.first_name, te.last_name, te.employee_no,
    d.name as department,
    COUNT(*) as recognition_count,
    SUM(r.points) as total_points
FROM recognitions r
JOIN employees te ON te.id = r.to_employee_id
LEFT JOIN departments d ON d.id = te.department_id
WHERE r.company_id = $1 AND r.created_at >= $2
GROUP BY te.id, te.first_name, te.last_name, te.employee_no, d.name
ORDER BY total_points DESC
LIMIT $3
`

type GetTopRecognizedParams struct {
	CompanyID int64     `json:"company_id"`
	CreatedAt time.Time `json:"created_at"`
	Limit     int32     `json:"limit"`
}

type GetTopRecognizedRow struct {
	EmployeeID       int64   `json:"employee_id"`
	FirstName        string  `json:"first_name"`
	LastName         string  `json:"last_name"`
	EmployeeNo       string  `json:"employee_no"`
	Department       *string `json:"department"`
	RecognitionCount int64   `json:"recognition_count"`
	TotalPoints      int64   `json:"total_points"`
}

func (q *Queries) GetTopRecognized(ctx context.Context, arg GetTopRecognizedParams) ([]GetTopRecognizedRow, error) {
	rows, err := q.db.Query(ctx, getTopRecognized, arg.CompanyID, arg.CreatedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopRecognizedRow{}
	for rows.Next() {
		var i GetTopRecognizedRow
		if err := rows.Scan(
			&i.EmployeeID,
			&i.FirstName,
			&i.LastName,
			&i.EmployeeNo,
			&i.Department,
			&i.RecognitionCount,
			&i.TotalPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyRecognitions = `-- name: ListMyRecognitions :many
SELECT r.id, r.company_id, r.from_employee_id, r.to_employee_id, r.category, r.message, r.is_public, r.points, r.created_at,
    fe.first_name as from_first_name, fe.last_name as from_last_name,
    te.first_name as to_first_name, te.last_name as to_last_name
FROM recognitions r
JOIN employees fe ON fe.id = r.from_employee_id
JOIN employees te ON te.id = r.to_employee_id
WHERE r.company_id = $1 AND (r.to_employee_id = $2 OR r.from_employee_id = $2)
ORDER BY r.created_at DESC
LIMIT $3 OFFSET $4
`

type ListMyRecognitionsParams struct {
	CompanyID    int64 `json:"company_id"`
	ToEmployeeID int64 `json:"to_employee_id"`
	Limit        int32 `json:"limit"`
	Offset       int32 `json:"offset"`
}

type ListMyRecognitionsRow struct {
	ID             int64     `json:"id"`
	CompanyID      int64     `json:"company_id"`
	FromEmployeeID int64     `json:"from_employee_id"`
	ToEmployeeID   int64     `json:"to_employee_id"`
	Category       string    `json:"category"`
	Message        string    `json:"message"`
	IsPublic       bool      `json:"is_public"`
	Points         int32     `json:"points"`
	CreatedAt      time.Time `json:"created_at"`
	FromFirstName  string    `json:"from_first_name"`
	FromLastName   string    `json:"from_last_name"`
	ToFirstName    string    `json:"to_first_name"`
	ToLastName     string    `json:"to_last_name"`
}

func (q *Queries) ListMyRecognitions(ctx context.Context, arg ListMyRecognitionsParams) ([]ListMyRecognitionsRow, error) {
	rows, err := q.db.Query(ctx, listMyRecognitions,
		arg.CompanyID,
		arg.ToEmployeeID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyRecognitionsRow{}
	for rows.Next() {
		var i ListMyRecognitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FromEmployeeID,
			&i.ToEmployeeID,
			&i.Category,
			&i.Message,
			&i.IsPublic,
			&i.Points,
			&i.CreatedAt,
			&i.FromFirstName,
			&i.FromLastName,
			&i.ToFirstName,
			&i.ToLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecognitions = `-- name: ListRecognitions :many
SELECT r.id, r.company_id, r.from_employee_id, r.to_employee_id, r.category, r.message, r.is_public, r.points, r.created_at,
    fe.first_name as from_first_name, fe.last_name as from_last_name, fe.employee_no as from_employee_no,
    te.first_name as to_first_name, te.last_name as to_last_name, te.employee_no as to_employee_no,
    td.name as to_department
FROM recognitions r
JOIN employees fe ON fe.id = r.from_employee_id
JOIN employees te ON te.id = r.to_employee_id
LEFT JOIN departments td ON td.id = te.department_id
WHERE r.company_id = $1 AND r.is_public = true
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListRecognitionsParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListRecognitionsRow struct {
	ID             int64     `json:"id"`
	CompanyID      int64     `json:"company_id"`
	FromEmployeeID int64     `json:"from_employee_id"`
	ToEmployeeID   int64     `json:"to_employee_id"`
	Category       string    `json:"category"`
	Message        string    `json:"message"`
	IsPublic       bool      `json:"is_public"`
	Points         int32     `json:"points"`
	CreatedAt      time.Time `json:"created_at"`
	FromFirstName  string    `json:"from_first_name"`
	FromLastName   string    `json:"from_last_name"`
	FromEmployeeNo string    `json:"from_employee_no"`
	ToFirstName    string    `json:"to_first_name"`
	ToLastName     string    `json:"to_last_name"`
	ToEmployeeNo   string    `json:"to_employee_no"`
	ToDepartment   *string   `json:"to_department"`
}

func (q *Queries) ListRecognitions(ctx context.Context, arg ListRecognitionsParams) ([]ListRecognitionsRow, error) {
	rows, err := q.db.Query(ctx, listRecognitions, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecognitionsRow{}
	for rows.Next() {
		var i ListRecognitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FromEmployeeID,
			&i.ToEmployeeID,
			&i.Category,
			&i.Message,
			&i.IsPublic,
			&i.Points,
			&i.CreatedAt,
			&i.FromFirstName,
			&i.FromLastName,
			&i.FromEmployeeNo,
			&i.ToFirstName,
			&i.ToLastName,
			&i.ToEmployeeNo,
			&i.ToDepartment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
