// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: schedule_template.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignScheduleTemplate = `-- name: AssignScheduleTemplate :one
INSERT INTO employee_schedule_assignments (company_id, employee_id, template_id, effective_from, effective_to)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (company_id, employee_id, effective_from) DO UPDATE
SET template_id = EXCLUDED.template_id, effective_to = EXCLUDED.effective_to
RETURNING id, company_id, employee_id, template_id, effective_from, effective_to, created_at
`

type AssignScheduleTemplateParams struct {
	CompanyID     int64       `json:"company_id"`
	EmployeeID    int64       `json:"employee_id"`
	TemplateID    int64       `json:"template_id"`
	EffectiveFrom time.Time   `json:"effective_from"`
	EffectiveTo   pgtype.Date `json:"effective_to"`
}

func (q *Queries) AssignScheduleTemplate(ctx context.Context, arg AssignScheduleTemplateParams) (EmployeeScheduleAssignment, error) {
	row := q.db.QueryRow(ctx, assignScheduleTemplate,
		arg.CompanyID,
		arg.EmployeeID,
		arg.TemplateID,
		arg.EffectiveFrom,
		arg.EffectiveTo,
	)
	var i EmployeeScheduleAssignment
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.TemplateID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const createScheduleTemplate = `-- name: CreateScheduleTemplate :one
INSERT INTO schedule_templates (company_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, company_id, name, description, is_active, created_at, updated_at
`

type CreateScheduleTemplateParams struct {
	CompanyID   int64   `json:"company_id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) CreateScheduleTemplate(ctx context.Context, arg CreateScheduleTemplateParams) (ScheduleTemplate, error) {
	row := q.db.QueryRow(ctx, createScheduleTemplate, arg.CompanyID, arg.Name, arg.Description)
	var i ScheduleTemplate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteScheduleAssignment = `-- name: DeleteScheduleAssignment :exec
DELETE FROM employee_schedule_assignments WHERE id = $1 AND company_id = $2
`

type DeleteScheduleAssignmentParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) DeleteScheduleAssignment(ctx context.Context, arg DeleteScheduleAssignmentParams) error {
	_, err := q.db.Exec(ctx, deleteScheduleAssignment, arg.ID, arg.CompanyID)
	return err
}

const deleteScheduleTemplate = `-- name: DeleteScheduleTemplate :exec
UPDATE schedule_templates SET is_active = false, updated_at = NOW()
WHERE id = $1 AND company_id = $2
`

type DeleteScheduleTemplateParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) DeleteScheduleTemplate(ctx context.Context, arg DeleteScheduleTemplateParams) error {
	_, err := q.db.Exec(ctx, deleteScheduleTemplate, arg.ID, arg.CompanyID)
	return err
}

const deleteScheduleTemplateDays = `-- name: DeleteScheduleTemplateDays :exec
DELETE FROM schedule_template_days WHERE template_id = $1
`

func (q *Queries) DeleteScheduleTemplateDays(ctx context.Context, templateID int64) error {
	_, err := q.db.Exec(ctx, deleteScheduleTemplateDays, templateID)
	return err
}

const getEmployeeCurrentTemplate = `-- name: GetEmployeeCurrentTemplate :one
SELECT esa.id, esa.company_id, esa.employee_id, esa.template_id, esa.effective_from, esa.effective_to, esa.created_at, st.name as template_name
FROM employee_schedule_assignments esa
JOIN schedule_templates st ON st.id = esa.template_id
WHERE esa.company_id = $1 AND esa.employee_id = $2
AND esa.effective_from <= $3
AND (esa.effective_to IS NULL OR esa.effective_to >= $3)
ORDER BY esa.effective_from DESC
LIMIT 1
`

type GetEmployeeCurrentTemplateParams struct {
	CompanyID     int64     `json:"company_id"`
	EmployeeID    int64     `json:"employee_id"`
	EffectiveFrom time.Time `json:"effective_from"`
}

type GetEmployeeCurrentTemplateRow struct {
	ID            int64       `json:"id"`
	CompanyID     int64       `json:"company_id"`
	EmployeeID    int64       `json:"employee_id"`
	TemplateID    int64       `json:"template_id"`
	EffectiveFrom time.Time   `json:"effective_from"`
	EffectiveTo   pgtype.Date `json:"effective_to"`
	CreatedAt     time.Time   `json:"created_at"`
	TemplateName  string      `json:"template_name"`
}

func (q *Queries) GetEmployeeCurrentTemplate(ctx context.Context, arg GetEmployeeCurrentTemplateParams) (GetEmployeeCurrentTemplateRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeCurrentTemplate, arg.CompanyID, arg.EmployeeID, arg.EffectiveFrom)
	var i GetEmployeeCurrentTemplateRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.TemplateID,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.CreatedAt,
		&i.TemplateName,
	)
	return i, err
}

const getScheduleTemplate = `-- name: GetScheduleTemplate :one
SELECT id, company_id, name, description, is_active, created_at, updated_at FROM schedule_templates
WHERE id = $1 AND company_id = $2
`

type GetScheduleTemplateParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetScheduleTemplate(ctx context.Context, arg GetScheduleTemplateParams) (ScheduleTemplate, error) {
	row := q.db.QueryRow(ctx, getScheduleTemplate, arg.ID, arg.CompanyID)
	var i ScheduleTemplate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEmployeeScheduleAssignments = `-- name: ListEmployeeScheduleAssignments :many
SELECT esa.id, esa.company_id, esa.employee_id, esa.template_id, esa.effective_from, esa.effective_to, esa.created_at, st.name as template_name, e.first_name, e.last_name, e.employee_no
FROM employee_schedule_assignments esa
JOIN schedule_templates st ON st.id = esa.template_id
JOIN employees e ON e.id = esa.employee_id
WHERE esa.company_id = $1
ORDER BY esa.effective_from DESC
LIMIT $2 OFFSET $3
`

type ListEmployeeScheduleAssignmentsParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListEmployeeScheduleAssignmentsRow struct {
	ID            int64       `json:"id"`
	CompanyID     int64       `json:"company_id"`
	EmployeeID    int64       `json:"employee_id"`
	TemplateID    int64       `json:"template_id"`
	EffectiveFrom time.Time   `json:"effective_from"`
	EffectiveTo   pgtype.Date `json:"effective_to"`
	CreatedAt     time.Time   `json:"created_at"`
	TemplateName  string      `json:"template_name"`
	FirstName     string      `json:"first_name"`
	LastName      string      `json:"last_name"`
	EmployeeNo    string      `json:"employee_no"`
}

func (q *Queries) ListEmployeeScheduleAssignments(ctx context.Context, arg ListEmployeeScheduleAssignmentsParams) ([]ListEmployeeScheduleAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeScheduleAssignments, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeScheduleAssignmentsRow{}
	for rows.Next() {
		var i ListEmployeeScheduleAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.TemplateID,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.CreatedAt,
			&i.TemplateName,
			&i.FirstName,
			&i.LastName,
			&i.EmployeeNo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleTemplateDays = `-- name: ListScheduleTemplateDays :many
SELECT std.id, std.template_id, std.day_of_week, std.shift_id, std.is_rest_day, s.name as shift_name, s.start_time, s.end_time
FROM schedule_template_days std
LEFT JOIN shifts s ON s.id = std.shift_id
WHERE std.template_id = $1
ORDER BY std.day_of_week
`

type ListScheduleTemplateDaysRow struct {
	ID         int64       `json:"id"`
	TemplateID int64       `json:"template_id"`
	DayOfWeek  int32       `json:"day_of_week"`
	ShiftID    *int64      `json:"shift_id"`
	IsRestDay  bool        `json:"is_rest_day"`
	ShiftName  *string     `json:"shift_name"`
	StartTime  pgtype.Time `json:"start_time"`
	EndTime    pgtype.Time `json:"end_time"`
}

func (q *Queries) ListScheduleTemplateDays(ctx context.Context, templateID int64) ([]ListScheduleTemplateDaysRow, error) {
	rows, err := q.db.Query(ctx, listScheduleTemplateDays, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleTemplateDaysRow{}
	for rows.Next() {
		var i ListScheduleTemplateDaysRow
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.DayOfWeek,
			&i.ShiftID,
			&i.IsRestDay,
			&i.ShiftName,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleTemplates = `-- name: ListScheduleTemplates :many
SELECT id, company_id, name, description, is_active, created_at, updated_at FROM schedule_templates
WHERE company_id = $1 AND is_active = true
ORDER BY name
`

func (q *Queries) ListScheduleTemplates(ctx context.Context, companyID int64) ([]ScheduleTemplate, error) {
	rows, err := q.db.Query(ctx, listScheduleTemplates, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleTemplate{}
	for rows.Next() {
		var i ScheduleTemplate
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateScheduleTemplate = `-- name: UpdateScheduleTemplate :one
UPDATE schedule_templates
SET name = $3, description = $4, updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, description, is_active, created_at, updated_at
`

type UpdateScheduleTemplateParams struct {
	ID          int64   `json:"id"`
	CompanyID   int64   `json:"company_id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateScheduleTemplate(ctx context.Context, arg UpdateScheduleTemplateParams) (ScheduleTemplate, error) {
	row := q.db.QueryRow(ctx, updateScheduleTemplate,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Description,
	)
	var i ScheduleTemplate
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertScheduleTemplateDay = `-- name: UpsertScheduleTemplateDay :one
INSERT INTO schedule_template_days (template_id, day_of_week, shift_id, is_rest_day)
VALUES ($1, $2, $3, $4)
ON CONFLICT (template_id, day_of_week) DO UPDATE
SET shift_id = EXCLUDED.shift_id, is_rest_day = EXCLUDED.is_rest_day
RETURNING id, template_id, day_of_week, shift_id, is_rest_day
`

type UpsertScheduleTemplateDayParams struct {
	TemplateID int64  `json:"template_id"`
	DayOfWeek  int32  `json:"day_of_week"`
	ShiftID    *int64 `json:"shift_id"`
	IsRestDay  bool   `json:"is_rest_day"`
}

func (q *Queries) UpsertScheduleTemplateDay(ctx context.Context, arg UpsertScheduleTemplateDayParams) (ScheduleTemplateDay, error) {
	row := q.db.QueryRow(ctx, upsertScheduleTemplateDay,
		arg.TemplateID,
		arg.DayOfWeek,
		arg.ShiftID,
		arg.IsRestDay,
	)
	var i ScheduleTemplateDay
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.DayOfWeek,
		&i.ShiftID,
		&i.IsRestDay,
	)
	return i, err
}
