// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: selfservice.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmployeeFullInfo = `-- name: GetEmployeeFullInfo :one
SELECT e.id, e.company_id, e.user_id, e.employee_no, e.first_name, e.last_name, e.middle_name, e.suffix, e.display_name, e.email, e.phone, e.birth_date, e.gender, e.civil_status, e.nationality, e.department_id, e.position_id, e.cost_center_id, e.manager_id, e.hire_date, e.regularization_date, e.separation_date, e.employment_type, e.status, e.created_at, e.updated_at, e.contract_end_date,
    d.name as department_name,
    p.title as position_title,
    cc.name as cost_center_name,
    mgr.first_name as manager_first_name,
    mgr.last_name as manager_last_name
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
LEFT JOIN cost_centers cc ON cc.id = e.cost_center_id
LEFT JOIN employees mgr ON mgr.id = e.manager_id
WHERE e.user_id = $1 AND e.company_id = $2
`

type GetEmployeeFullInfoParams struct {
	UserID    *int64 `json:"user_id"`
	CompanyID int64  `json:"company_id"`
}

type GetEmployeeFullInfoRow struct {
	ID                 int64       `json:"id"`
	CompanyID          int64       `json:"company_id"`
	UserID             *int64      `json:"user_id"`
	EmployeeNo         string      `json:"employee_no"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	MiddleName         *string     `json:"middle_name"`
	Suffix             *string     `json:"suffix"`
	DisplayName        *string     `json:"display_name"`
	Email              *string     `json:"email"`
	Phone              *string     `json:"phone"`
	BirthDate          pgtype.Date `json:"birth_date"`
	Gender             *string     `json:"gender"`
	CivilStatus        *string     `json:"civil_status"`
	Nationality        *string     `json:"nationality"`
	DepartmentID       *int64      `json:"department_id"`
	PositionID         *int64      `json:"position_id"`
	CostCenterID       *int64      `json:"cost_center_id"`
	ManagerID          *int64      `json:"manager_id"`
	HireDate           time.Time   `json:"hire_date"`
	RegularizationDate pgtype.Date `json:"regularization_date"`
	SeparationDate     pgtype.Date `json:"separation_date"`
	EmploymentType     string      `json:"employment_type"`
	Status             string      `json:"status"`
	CreatedAt          time.Time   `json:"created_at"`
	UpdatedAt          time.Time   `json:"updated_at"`
	ContractEndDate    pgtype.Date `json:"contract_end_date"`
	DepartmentName     *string     `json:"department_name"`
	PositionTitle      *string     `json:"position_title"`
	CostCenterName     *string     `json:"cost_center_name"`
	ManagerFirstName   *string     `json:"manager_first_name"`
	ManagerLastName    *string     `json:"manager_last_name"`
}

func (q *Queries) GetEmployeeFullInfo(ctx context.Context, arg GetEmployeeFullInfoParams) (GetEmployeeFullInfoRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeFullInfo, arg.UserID, arg.CompanyID)
	var i GetEmployeeFullInfoRow
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.EmployeeNo,
		&i.FirstName,
		&i.LastName,
		&i.MiddleName,
		&i.Suffix,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.BirthDate,
		&i.Gender,
		&i.CivilStatus,
		&i.Nationality,
		&i.DepartmentID,
		&i.PositionID,
		&i.CostCenterID,
		&i.ManagerID,
		&i.HireDate,
		&i.RegularizationDate,
		&i.SeparationDate,
		&i.EmploymentType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ContractEndDate,
		&i.DepartmentName,
		&i.PositionTitle,
		&i.CostCenterName,
		&i.ManagerFirstName,
		&i.ManagerLastName,
	)
	return i, err
}

const getMyCompensation = `-- name: GetMyCompensation :one
SELECT es.basic_salary, es.effective_from,
    ss.name as structure_name
FROM employee_salaries es
LEFT JOIN salary_structures ss ON ss.id = es.structure_id
WHERE es.company_id = $1 AND es.employee_id = $2
  AND es.effective_from <= NOW()
ORDER BY es.effective_from DESC
LIMIT 1
`

type GetMyCompensationParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
}

type GetMyCompensationRow struct {
	BasicSalary   pgtype.Numeric `json:"basic_salary"`
	EffectiveFrom time.Time      `json:"effective_from"`
	StructureName *string        `json:"structure_name"`
}

func (q *Queries) GetMyCompensation(ctx context.Context, arg GetMyCompensationParams) (GetMyCompensationRow, error) {
	row := q.db.QueryRow(ctx, getMyCompensation, arg.CompanyID, arg.EmployeeID)
	var i GetMyCompensationRow
	err := row.Scan(&i.BasicSalary, &i.EffectiveFrom, &i.StructureName)
	return i, err
}

const getMyLatestPayslip = `-- name: GetMyLatestPayslip :one
SELECT pi.id, pi.run_id, pi.employee_id, pi.basic_pay, pi.gross_pay, pi.taxable_income, pi.total_deductions, pi.net_pay, pi.sss_ee, pi.sss_er, pi.sss_ec, pi.philhealth_ee, pi.philhealth_er, pi.pagibig_ee, pi.pagibig_er, pi.withholding_tax, pi.breakdown, pi.work_days, pi.hours_worked, pi.ot_hours, pi.late_deduction, pi.undertime_deduction, pi.holiday_pay, pi.night_diff, pi.created_at, pi.bonus_pay, pi.federal_tax, pi.social_security_ee, pi.social_security_er, pi.medicare_ee, pi.medicare_er, pi.additional_medicare, pi.state_tax, pi.state_disability, pi.futa, pi.sui, pi.pretax_deductions, pc.name as cycle_name, pc.period_start, pc.period_end
FROM payroll_items pi
JOIN payroll_runs pr ON pr.id = pi.run_id
JOIN payroll_cycles pc ON pc.id = pr.cycle_id
WHERE pr.company_id = $1 AND pi.employee_id = $2 AND pr.status = 'completed'
ORDER BY pc.period_end DESC
LIMIT 1
`

type GetMyLatestPayslipParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
}

type GetMyLatestPayslipRow struct {
	ID                 int64           `json:"id"`
	RunID              int64           `json:"run_id"`
	EmployeeID         int64           `json:"employee_id"`
	BasicPay           pgtype.Numeric  `json:"basic_pay"`
	GrossPay           pgtype.Numeric  `json:"gross_pay"`
	TaxableIncome      pgtype.Numeric  `json:"taxable_income"`
	TotalDeductions    pgtype.Numeric  `json:"total_deductions"`
	NetPay             pgtype.Numeric  `json:"net_pay"`
	SssEe              pgtype.Numeric  `json:"sss_ee"`
	SssEr              pgtype.Numeric  `json:"sss_er"`
	SssEc              pgtype.Numeric  `json:"sss_ec"`
	PhilhealthEe       pgtype.Numeric  `json:"philhealth_ee"`
	PhilhealthEr       pgtype.Numeric  `json:"philhealth_er"`
	PagibigEe          pgtype.Numeric  `json:"pagibig_ee"`
	PagibigEr          pgtype.Numeric  `json:"pagibig_er"`
	WithholdingTax     pgtype.Numeric  `json:"withholding_tax"`
	Breakdown          json.RawMessage `json:"breakdown"`
	WorkDays           pgtype.Numeric  `json:"work_days"`
	HoursWorked        pgtype.Numeric  `json:"hours_worked"`
	OtHours            pgtype.Numeric  `json:"ot_hours"`
	LateDeduction      pgtype.Numeric  `json:"late_deduction"`
	UndertimeDeduction pgtype.Numeric  `json:"undertime_deduction"`
	HolidayPay         pgtype.Numeric  `json:"holiday_pay"`
	NightDiff          pgtype.Numeric  `json:"night_diff"`
	CreatedAt          time.Time       `json:"created_at"`
	BonusPay           pgtype.Numeric  `json:"bonus_pay"`
	FederalTax         pgtype.Numeric  `json:"federal_tax"`
	SocialSecurityEe   pgtype.Numeric  `json:"social_security_ee"`
	SocialSecurityEr   pgtype.Numeric  `json:"social_security_er"`
	MedicareEe         pgtype.Numeric  `json:"medicare_ee"`
	MedicareEr         pgtype.Numeric  `json:"medicare_er"`
	AdditionalMedicare pgtype.Numeric  `json:"additional_medicare"`
	StateTax           pgtype.Numeric  `json:"state_tax"`
	StateDisability    pgtype.Numeric  `json:"state_disability"`
	Futa               pgtype.Numeric  `json:"futa"`
	Sui                pgtype.Numeric  `json:"sui"`
	PretaxDeductions   pgtype.Numeric  `json:"pretax_deductions"`
	CycleName          string          `json:"cycle_name"`
	PeriodStart        time.Time       `json:"period_start"`
	PeriodEnd          time.Time       `json:"period_end"`
}

func (q *Queries) GetMyLatestPayslip(ctx context.Context, arg GetMyLatestPayslipParams) (GetMyLatestPayslipRow, error) {
	row := q.db.QueryRow(ctx, getMyLatestPayslip, arg.CompanyID, arg.EmployeeID)
	var i GetMyLatestPayslipRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.EmployeeID,
		&i.BasicPay,
		&i.GrossPay,
		&i.TaxableIncome,
		&i.TotalDeductions,
		&i.NetPay,
		&i.SssEe,
		&i.SssEr,
		&i.SssEc,
		&i.PhilhealthEe,
		&i.PhilhealthEr,
		&i.PagibigEe,
		&i.PagibigEr,
		&i.WithholdingTax,
		&i.Breakdown,
		&i.WorkDays,
		&i.HoursWorked,
		&i.OtHours,
		&i.LateDeduction,
		&i.UndertimeDeduction,
		&i.HolidayPay,
		&i.NightDiff,
		&i.CreatedAt,
		&i.BonusPay,
		&i.FederalTax,
		&i.SocialSecurityEe,
		&i.SocialSecurityEr,
		&i.MedicareEe,
		&i.MedicareEr,
		&i.AdditionalMedicare,
		&i.StateTax,
		&i.StateDisability,
		&i.Futa,
		&i.Sui,
		&i.PretaxDeductions,
		&i.CycleName,
		&i.PeriodStart,
		&i.PeriodEnd,
	)
	return i, err
}

const getMyManager = `-- name: GetMyManager :one
SELECT e.id, e.employee_no, e.first_name, e.last_name, e.email, e.phone,
    d.name as department_name, p.title as position_title
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
WHERE e.id = $1 AND e.company_id = $2
`

type GetMyManagerParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

type GetMyManagerRow struct {
	ID             int64   `json:"id"`
	EmployeeNo     string  `json:"employee_no"`
	FirstName      string  `json:"first_name"`
	LastName       string  `json:"last_name"`
	Email          *string `json:"email"`
	Phone          *string `json:"phone"`
	DepartmentName *string `json:"department_name"`
	PositionTitle  *string `json:"position_title"`
}

func (q *Queries) GetMyManager(ctx context.Context, arg GetMyManagerParams) (GetMyManagerRow, error) {
	row := q.db.QueryRow(ctx, getMyManager, arg.ID, arg.CompanyID)
	var i GetMyManagerRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeNo,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.DepartmentName,
		&i.PositionTitle,
	)
	return i, err
}

const listTeamMembers = `-- name: ListTeamMembers :many
SELECT e.id, e.employee_no, e.first_name, e.last_name, e.email, e.phone,
    e.employment_type, e.hire_date, e.status,
    d.name as department_name, p.title as position_title
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
WHERE e.company_id = $1 AND e.manager_id = $2 AND e.status = 'active'
ORDER BY e.last_name, e.first_name
`

type ListTeamMembersParams struct {
	CompanyID int64  `json:"company_id"`
	ManagerID *int64 `json:"manager_id"`
}

type ListTeamMembersRow struct {
	ID             int64     `json:"id"`
	EmployeeNo     string    `json:"employee_no"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	Email          *string   `json:"email"`
	Phone          *string   `json:"phone"`
	EmploymentType string    `json:"employment_type"`
	HireDate       time.Time `json:"hire_date"`
	Status         string    `json:"status"`
	DepartmentName *string   `json:"department_name"`
	PositionTitle  *string   `json:"position_title"`
}

func (q *Queries) ListTeamMembers(ctx context.Context, arg ListTeamMembersParams) ([]ListTeamMembersRow, error) {
	rows, err := q.db.Query(ctx, listTeamMembers, arg.CompanyID, arg.ManagerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembersRow{}
	for rows.Next() {
		var i ListTeamMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.Phone,
			&i.EmploymentType,
			&i.HireDate,
			&i.Status,
			&i.DepartmentName,
			&i.PositionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
