// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suggestions.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmployeesWithNoSalary = `-- name: CountEmployeesWithNoSalary :one
SELECT COUNT(*) FROM employees e
LEFT JOIN employee_salaries es ON es.employee_id = e.id
  AND es.effective_from <= $2
  AND (es.effective_to IS NULL OR es.effective_to >= $2)
WHERE e.company_id = $1 AND e.status = 'active' AND es.id IS NULL
`

type CountEmployeesWithNoSalaryParams struct {
	CompanyID     int64     `json:"company_id"`
	EffectiveFrom time.Time `json:"effective_from"`
}

func (q *Queries) CountEmployeesWithNoSalary(ctx context.Context, arg CountEmployeesWithNoSalaryParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployeesWithNoSalary, arg.CompanyID, arg.EffectiveFrom)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listEmployeesDueForRegularization = `-- name: ListEmployeesDueForRegularization :many
SELECT e.id, e.employee_no, e.first_name, e.last_name, e.hire_date,
       e.regularization_date,
       COALESCE(d.name, '') as department_name,
       COALESCE(p.title, '') as position_title
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
WHERE e.company_id = $1
  AND e.status = 'active'
  AND e.employment_type = 'probationary'
  AND (e.regularization_date IS NULL OR e.regularization_date <= $2::date + interval '30 days')
ORDER BY e.hire_date
`

type ListEmployeesDueForRegularizationParams struct {
	CompanyID int64     `json:"company_id"`
	Column2   time.Time `json:"column_2"`
}

type ListEmployeesDueForRegularizationRow struct {
	ID                 int64       `json:"id"`
	EmployeeNo         string      `json:"employee_no"`
	FirstName          string      `json:"first_name"`
	LastName           string      `json:"last_name"`
	HireDate           time.Time   `json:"hire_date"`
	RegularizationDate pgtype.Date `json:"regularization_date"`
	DepartmentName     string      `json:"department_name"`
	PositionTitle      string      `json:"position_title"`
}

func (q *Queries) ListEmployeesDueForRegularization(ctx context.Context, arg ListEmployeesDueForRegularizationParams) ([]ListEmployeesDueForRegularizationRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesDueForRegularization, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesDueForRegularizationRow{}
	for rows.Next() {
		var i ListEmployeesDueForRegularizationRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.HireDate,
			&i.RegularizationDate,
			&i.DepartmentName,
			&i.PositionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringContracts = `-- name: ListExpiringContracts :many
SELECT e.id, e.employee_no, e.first_name, e.last_name, e.separation_date,
       COALESCE(d.name, '') as department_name,
       COALESCE(p.title, '') as position_title
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN positions p ON p.id = e.position_id
WHERE e.company_id = $1
  AND e.status = 'active'
  AND e.employment_type = 'contractual'
  AND e.separation_date IS NOT NULL
  AND e.separation_date <= $2::date + interval '60 days'
ORDER BY e.separation_date
`

type ListExpiringContractsParams struct {
	CompanyID int64     `json:"company_id"`
	Column2   time.Time `json:"column_2"`
}

type ListExpiringContractsRow struct {
	ID             int64       `json:"id"`
	EmployeeNo     string      `json:"employee_no"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	SeparationDate pgtype.Date `json:"separation_date"`
	DepartmentName string      `json:"department_name"`
	PositionTitle  string      `json:"position_title"`
}

func (q *Queries) ListExpiringContracts(ctx context.Context, arg ListExpiringContractsParams) ([]ListExpiringContractsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringContracts, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringContractsRow{}
	for rows.Next() {
		var i ListExpiringContractsRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.SeparationDate,
			&i.DepartmentName,
			&i.PositionTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOnboardingTasks = `-- name: ListPendingOnboardingTasks :many
SELECT ot.id, ot.employee_id, ot.title, ot.due_date, ot.workflow_type,
       e.first_name, e.last_name
FROM onboarding_tasks ot
JOIN employees e ON e.id = ot.employee_id
WHERE ot.company_id = $1
  AND ot.status = 'pending'
ORDER BY ot.due_date
LIMIT 20
`

type ListPendingOnboardingTasksRow struct {
	ID           int64       `json:"id"`
	EmployeeID   int64       `json:"employee_id"`
	Title        string      `json:"title"`
	DueDate      pgtype.Date `json:"due_date"`
	WorkflowType string      `json:"workflow_type"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
}

func (q *Queries) ListPendingOnboardingTasks(ctx context.Context, companyID int64) ([]ListPendingOnboardingTasksRow, error) {
	rows, err := q.db.Query(ctx, listPendingOnboardingTasks, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingOnboardingTasksRow{}
	for rows.Next() {
		var i ListPendingOnboardingTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.Title,
			&i.DueDate,
			&i.WorkflowType,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingBirthdays = `-- name: ListUpcomingBirthdays :many
SELECT e.id, e.employee_no, e.first_name, e.last_name, e.birth_date,
       COALESCE(d.name, '') as department_name
FROM employees e
LEFT JOIN departments d ON d.id = e.department_id
WHERE e.company_id = $1
  AND e.status = 'active'
  AND e.birth_date IS NOT NULL
  AND (
    (EXTRACT(MONTH FROM e.birth_date) = EXTRACT(MONTH FROM $2::date)
     AND EXTRACT(DAY FROM e.birth_date) >= EXTRACT(DAY FROM $2::date))
    OR
    (EXTRACT(MONTH FROM e.birth_date) = EXTRACT(MONTH FROM $2::date + interval '30 days')
     AND EXTRACT(DAY FROM e.birth_date) <= EXTRACT(DAY FROM $2::date + interval '30 days'))
  )
ORDER BY EXTRACT(MONTH FROM e.birth_date), EXTRACT(DAY FROM e.birth_date)
`

type ListUpcomingBirthdaysParams struct {
	CompanyID int64     `json:"company_id"`
	Column2   time.Time `json:"column_2"`
}

type ListUpcomingBirthdaysRow struct {
	ID             int64       `json:"id"`
	EmployeeNo     string      `json:"employee_no"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
	BirthDate      pgtype.Date `json:"birth_date"`
	DepartmentName string      `json:"department_name"`
}

func (q *Queries) ListUpcomingBirthdays(ctx context.Context, arg ListUpcomingBirthdaysParams) ([]ListUpcomingBirthdaysRow, error) {
	rows, err := q.db.Query(ctx, listUpcomingBirthdays, arg.CompanyID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUpcomingBirthdaysRow{}
	for rows.Next() {
		var i ListUpcomingBirthdaysRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
			&i.BirthDate,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
