// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tax_filing.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRemittanceRecord = `-- name: CreateRemittanceRecord :one
INSERT INTO remittance_records (
    company_id, filing_id, agency, period_year, period_month,
    employee_count, employer_share, employee_share, total_amount
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, filing_id, agency, period_year, period_month, employee_count, employer_share, employee_share, total_amount, created_at
`

type CreateRemittanceRecordParams struct {
	CompanyID     int64          `json:"company_id"`
	FilingID      *int64         `json:"filing_id"`
	Agency        string         `json:"agency"`
	PeriodYear    int32          `json:"period_year"`
	PeriodMonth   int32          `json:"period_month"`
	EmployeeCount int32          `json:"employee_count"`
	EmployerShare pgtype.Numeric `json:"employer_share"`
	EmployeeShare pgtype.Numeric `json:"employee_share"`
	TotalAmount   pgtype.Numeric `json:"total_amount"`
}

func (q *Queries) CreateRemittanceRecord(ctx context.Context, arg CreateRemittanceRecordParams) (RemittanceRecord, error) {
	row := q.db.QueryRow(ctx, createRemittanceRecord,
		arg.CompanyID,
		arg.FilingID,
		arg.Agency,
		arg.PeriodYear,
		arg.PeriodMonth,
		arg.EmployeeCount,
		arg.EmployerShare,
		arg.EmployeeShare,
		arg.TotalAmount,
	)
	var i RemittanceRecord
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FilingID,
		&i.Agency,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.EmployeeCount,
		&i.EmployerShare,
		&i.EmployeeShare,
		&i.TotalAmount,
		&i.CreatedAt,
	)
	return i, err
}

const createTaxFiling = `-- name: CreateTaxFiling :one
INSERT INTO tax_filings (
    company_id, filing_type, period_type, period_year, period_month,
    period_quarter, due_date, amount, status
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, filing_type, period_type, period_year, period_month, period_quarter, due_date, filing_date, status, amount, penalty_amount, reference_no, proof_path, filed_by, notes, created_at, updated_at
`

type CreateTaxFilingParams struct {
	CompanyID     int64          `json:"company_id"`
	FilingType    string         `json:"filing_type"`
	PeriodType    string         `json:"period_type"`
	PeriodYear    int32          `json:"period_year"`
	PeriodMonth   *int32         `json:"period_month"`
	PeriodQuarter *int32         `json:"period_quarter"`
	DueDate       time.Time      `json:"due_date"`
	Amount        pgtype.Numeric `json:"amount"`
	Status        string         `json:"status"`
}

func (q *Queries) CreateTaxFiling(ctx context.Context, arg CreateTaxFilingParams) (TaxFiling, error) {
	row := q.db.QueryRow(ctx, createTaxFiling,
		arg.CompanyID,
		arg.FilingType,
		arg.PeriodType,
		arg.PeriodYear,
		arg.PeriodMonth,
		arg.PeriodQuarter,
		arg.DueDate,
		arg.Amount,
		arg.Status,
	)
	var i TaxFiling
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FilingType,
		&i.PeriodType,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.PeriodQuarter,
		&i.DueDate,
		&i.FilingDate,
		&i.Status,
		&i.Amount,
		&i.PenaltyAmount,
		&i.ReferenceNo,
		&i.ProofPath,
		&i.FiledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const generateAnnualFilings = `-- name: GenerateAnnualFilings :exec
INSERT INTO tax_filings (company_id, filing_type, period_type, period_year, period_month, due_date, status)
SELECT $1, ft.filing_type, ft.period_type, $2, ft.period_month, ft.due_date, 'pending'
FROM (
    -- BIR 1601-C (Monthly withholding tax)
    SELECT 'bir_1601c' as filing_type, 'monthly' as period_type, m.n as period_month,
           make_date($2::int, m.n, 10) as due_date
    FROM generate_series(1, 12) as m(n)
    UNION ALL
    -- SSS (Monthly contribution)
    SELECT 'sss_r3', 'monthly', m.n,
           make_date($2::int, m.n, CASE WHEN m.n = 12 THEN 31 ELSE 10 END)
    FROM generate_series(1, 12) as m(n)
    UNION ALL
    -- PhilHealth (Monthly)
    SELECT 'philhealth_rf1', 'monthly', m.n,
           make_date($2::int, m.n, 15)
    FROM generate_series(1, 12) as m(n)
    UNION ALL
    -- Pag-IBIG (Monthly)
    SELECT 'pagibig_ml1', 'monthly', m.n,
           make_date($2::int, m.n, 10)
    FROM generate_series(1, 12) as m(n)
    UNION ALL
    -- BIR 2316 (Annual ITR)
    SELECT 'bir_2316', 'annual', NULL,
           make_date($2::int, 1, 31)
) ft
ON CONFLICT DO NOTHING
`

type GenerateAnnualFilingsParams struct {
	CompanyID  int64 `json:"company_id"`
	PeriodYear int32 `json:"period_year"`
}

func (q *Queries) GenerateAnnualFilings(ctx context.Context, arg GenerateAnnualFilingsParams) error {
	_, err := q.db.Exec(ctx, generateAnnualFilings, arg.CompanyID, arg.PeriodYear)
	return err
}

const getFilingSummary = `-- name: GetFilingSummary :one
SELECT
    COUNT(*) as total,
    COUNT(CASE WHEN status = 'filed' THEN 1 END) as filed,
    COUNT(CASE WHEN status IN ('pending', 'generated') AND due_date < CURRENT_DATE THEN 1 END) as overdue,
    COUNT(CASE WHEN status IN ('pending', 'generated') AND due_date >= CURRENT_DATE THEN 1 END) as upcoming,
    COALESCE(SUM(amount), 0) as total_amount,
    COALESCE(SUM(penalty_amount), 0) as total_penalties
FROM tax_filings
WHERE company_id = $1 AND period_year = $2
`

type GetFilingSummaryParams struct {
	CompanyID  int64 `json:"company_id"`
	PeriodYear int32 `json:"period_year"`
}

type GetFilingSummaryRow struct {
	Total          int64       `json:"total"`
	Filed          int64       `json:"filed"`
	Overdue        int64       `json:"overdue"`
	Upcoming       int64       `json:"upcoming"`
	TotalAmount    interface{} `json:"total_amount"`
	TotalPenalties interface{} `json:"total_penalties"`
}

func (q *Queries) GetFilingSummary(ctx context.Context, arg GetFilingSummaryParams) (GetFilingSummaryRow, error) {
	row := q.db.QueryRow(ctx, getFilingSummary, arg.CompanyID, arg.PeriodYear)
	var i GetFilingSummaryRow
	err := row.Scan(
		&i.Total,
		&i.Filed,
		&i.Overdue,
		&i.Upcoming,
		&i.TotalAmount,
		&i.TotalPenalties,
	)
	return i, err
}

const getTaxFiling = `-- name: GetTaxFiling :one
SELECT id, company_id, filing_type, period_type, period_year, period_month, period_quarter, due_date, filing_date, status, amount, penalty_amount, reference_no, proof_path, filed_by, notes, created_at, updated_at FROM tax_filings WHERE id = $1 AND company_id = $2
`

type GetTaxFilingParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetTaxFiling(ctx context.Context, arg GetTaxFilingParams) (TaxFiling, error) {
	row := q.db.QueryRow(ctx, getTaxFiling, arg.ID, arg.CompanyID)
	var i TaxFiling
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FilingType,
		&i.PeriodType,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.PeriodQuarter,
		&i.DueDate,
		&i.FilingDate,
		&i.Status,
		&i.Amount,
		&i.PenaltyAmount,
		&i.ReferenceNo,
		&i.ProofPath,
		&i.FiledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOverdueFilings = `-- name: ListOverdueFilings :many
SELECT id, company_id, filing_type, period_type, period_year, period_month, period_quarter, due_date, filing_date, status, amount, penalty_amount, reference_no, proof_path, filed_by, notes, created_at, updated_at FROM tax_filings
WHERE company_id = $1
  AND status IN ('pending', 'generated')
  AND due_date < CURRENT_DATE
ORDER BY due_date
`

func (q *Queries) ListOverdueFilings(ctx context.Context, companyID int64) ([]TaxFiling, error) {
	rows, err := q.db.Query(ctx, listOverdueFilings, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxFiling{}
	for rows.Next() {
		var i TaxFiling
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FilingType,
			&i.PeriodType,
			&i.PeriodYear,
			&i.PeriodMonth,
			&i.PeriodQuarter,
			&i.DueDate,
			&i.FilingDate,
			&i.Status,
			&i.Amount,
			&i.PenaltyAmount,
			&i.ReferenceNo,
			&i.ProofPath,
			&i.FiledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemittanceRecords = `-- name: ListRemittanceRecords :many
SELECT id, company_id, filing_id, agency, period_year, period_month, employee_count, employer_share, employee_share, total_amount, created_at FROM remittance_records
WHERE company_id = $1 AND period_year = $2
ORDER BY period_month, agency
`

type ListRemittanceRecordsParams struct {
	CompanyID  int64 `json:"company_id"`
	PeriodYear int32 `json:"period_year"`
}

func (q *Queries) ListRemittanceRecords(ctx context.Context, arg ListRemittanceRecordsParams) ([]RemittanceRecord, error) {
	rows, err := q.db.Query(ctx, listRemittanceRecords, arg.CompanyID, arg.PeriodYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RemittanceRecord{}
	for rows.Next() {
		var i RemittanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FilingID,
			&i.Agency,
			&i.PeriodYear,
			&i.PeriodMonth,
			&i.EmployeeCount,
			&i.EmployerShare,
			&i.EmployeeShare,
			&i.TotalAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxFilings = `-- name: ListTaxFilings :many
SELECT id, company_id, filing_type, period_type, period_year, period_month, period_quarter, due_date, filing_date, status, amount, penalty_amount, reference_no, proof_path, filed_by, notes, created_at, updated_at FROM tax_filings
WHERE company_id = $1
  AND ($2 = '' OR status = $2)
  AND ($3 = '' OR filing_type = $3)
  AND period_year = $4
ORDER BY due_date
`

type ListTaxFilingsParams struct {
	CompanyID  int64       `json:"company_id"`
	Status     interface{} `json:"status"`
	FilingType interface{} `json:"filing_type"`
	PeriodYear int32       `json:"period_year"`
}

func (q *Queries) ListTaxFilings(ctx context.Context, arg ListTaxFilingsParams) ([]TaxFiling, error) {
	rows, err := q.db.Query(ctx, listTaxFilings,
		arg.CompanyID,
		arg.Status,
		arg.FilingType,
		arg.PeriodYear,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxFiling{}
	for rows.Next() {
		var i TaxFiling
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FilingType,
			&i.PeriodType,
			&i.PeriodYear,
			&i.PeriodMonth,
			&i.PeriodQuarter,
			&i.DueDate,
			&i.FilingDate,
			&i.Status,
			&i.Amount,
			&i.PenaltyAmount,
			&i.ReferenceNo,
			&i.ProofPath,
			&i.FiledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingFilings = `-- name: ListUpcomingFilings :many
SELECT id, company_id, filing_type, period_type, period_year, period_month, period_quarter, due_date, filing_date, status, amount, penalty_amount, reference_no, proof_path, filed_by, notes, created_at, updated_at FROM tax_filings
WHERE company_id = $1
  AND status IN ('pending', 'generated')
  AND due_date >= CURRENT_DATE
  AND due_date <= CURRENT_DATE + INTERVAL '30 days'
ORDER BY due_date
`

func (q *Queries) ListUpcomingFilings(ctx context.Context, companyID int64) ([]TaxFiling, error) {
	rows, err := q.db.Query(ctx, listUpcomingFilings, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaxFiling{}
	for rows.Next() {
		var i TaxFiling
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.FilingType,
			&i.PeriodType,
			&i.PeriodYear,
			&i.PeriodMonth,
			&i.PeriodQuarter,
			&i.DueDate,
			&i.FilingDate,
			&i.Status,
			&i.Amount,
			&i.PenaltyAmount,
			&i.ReferenceNo,
			&i.ProofPath,
			&i.FiledBy,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOverdueFilings = `-- name: MarkOverdueFilings :exec
UPDATE tax_filings SET
    status = 'overdue',
    updated_at = NOW()
WHERE status IN ('pending', 'generated')
  AND due_date < CURRENT_DATE
`

func (q *Queries) MarkOverdueFilings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, markOverdueFilings)
	return err
}

const updateTaxFilingAmount = `-- name: UpdateTaxFilingAmount :one
UPDATE tax_filings SET
    amount = $3,
    penalty_amount = $4,
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, filing_type, period_type, period_year, period_month, period_quarter, due_date, filing_date, status, amount, penalty_amount, reference_no, proof_path, filed_by, notes, created_at, updated_at
`

type UpdateTaxFilingAmountParams struct {
	ID            int64          `json:"id"`
	CompanyID     int64          `json:"company_id"`
	Amount        pgtype.Numeric `json:"amount"`
	PenaltyAmount pgtype.Numeric `json:"penalty_amount"`
}

func (q *Queries) UpdateTaxFilingAmount(ctx context.Context, arg UpdateTaxFilingAmountParams) (TaxFiling, error) {
	row := q.db.QueryRow(ctx, updateTaxFilingAmount,
		arg.ID,
		arg.CompanyID,
		arg.Amount,
		arg.PenaltyAmount,
	)
	var i TaxFiling
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FilingType,
		&i.PeriodType,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.PeriodQuarter,
		&i.DueDate,
		&i.FilingDate,
		&i.Status,
		&i.Amount,
		&i.PenaltyAmount,
		&i.ReferenceNo,
		&i.ProofPath,
		&i.FiledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaxFilingStatus = `-- name: UpdateTaxFilingStatus :one
UPDATE tax_filings SET
    status = $3,
    filing_date = CASE WHEN $3 IN ('submitted', 'filed') THEN CURRENT_DATE ELSE filing_date END,
    filed_by = $4,
    reference_no = $5,
    notes = $6,
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, filing_type, period_type, period_year, period_month, period_quarter, due_date, filing_date, status, amount, penalty_amount, reference_no, proof_path, filed_by, notes, created_at, updated_at
`

type UpdateTaxFilingStatusParams struct {
	ID          int64   `json:"id"`
	CompanyID   int64   `json:"company_id"`
	Status      string  `json:"status"`
	FiledBy     *int64  `json:"filed_by"`
	ReferenceNo *string `json:"reference_no"`
	Notes       *string `json:"notes"`
}

func (q *Queries) UpdateTaxFilingStatus(ctx context.Context, arg UpdateTaxFilingStatusParams) (TaxFiling, error) {
	row := q.db.QueryRow(ctx, updateTaxFilingStatus,
		arg.ID,
		arg.CompanyID,
		arg.Status,
		arg.FiledBy,
		arg.ReferenceNo,
		arg.Notes,
	)
	var i TaxFiling
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.FilingType,
		&i.PeriodType,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.PeriodQuarter,
		&i.DueDate,
		&i.FilingDate,
		&i.Status,
		&i.Amount,
		&i.PenaltyAmount,
		&i.ReferenceNo,
		&i.ProofPath,
		&i.FiledBy,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
