// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: training.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addTrainingParticipant = `-- name: AddTrainingParticipant :one
INSERT INTO training_participants (training_id, employee_id)
VALUES ($1, $2)
ON CONFLICT (training_id, employee_id) DO NOTHING
RETURNING id, training_id, employee_id, status, score, feedback, completed_at, created_at
`

type AddTrainingParticipantParams struct {
	TrainingID int64 `json:"training_id"`
	EmployeeID int64 `json:"employee_id"`
}

func (q *Queries) AddTrainingParticipant(ctx context.Context, arg AddTrainingParticipantParams) (TrainingParticipant, error) {
	row := q.db.QueryRow(ctx, addTrainingParticipant, arg.TrainingID, arg.EmployeeID)
	var i TrainingParticipant
	err := row.Scan(
		&i.ID,
		&i.TrainingID,
		&i.EmployeeID,
		&i.Status,
		&i.Score,
		&i.Feedback,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createCertification = `-- name: CreateCertification :one
INSERT INTO certifications (
    company_id, employee_id, name, issuing_body,
    credential_id, issue_date, expiry_date
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, company_id, employee_id, name, issuing_body, credential_id, issue_date, expiry_date, status, attachment_path, created_at, updated_at
`

type CreateCertificationParams struct {
	CompanyID    int64       `json:"company_id"`
	EmployeeID   int64       `json:"employee_id"`
	Name         string      `json:"name"`
	IssuingBody  *string     `json:"issuing_body"`
	CredentialID *string     `json:"credential_id"`
	IssueDate    time.Time   `json:"issue_date"`
	ExpiryDate   pgtype.Date `json:"expiry_date"`
}

func (q *Queries) CreateCertification(ctx context.Context, arg CreateCertificationParams) (Certification, error) {
	row := q.db.QueryRow(ctx, createCertification,
		arg.CompanyID,
		arg.EmployeeID,
		arg.Name,
		arg.IssuingBody,
		arg.CredentialID,
		arg.IssueDate,
		arg.ExpiryDate,
	)
	var i Certification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.Name,
		&i.IssuingBody,
		&i.CredentialID,
		&i.IssueDate,
		&i.ExpiryDate,
		&i.Status,
		&i.AttachmentPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTraining = `-- name: CreateTraining :one
INSERT INTO trainings (
    company_id, title, description, trainer, training_type,
    start_date, end_date, max_participants, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, company_id, title, description, trainer, training_type, start_date, end_date, max_participants, status, created_by, created_at, updated_at
`

type CreateTrainingParams struct {
	CompanyID       int64       `json:"company_id"`
	Title           string      `json:"title"`
	Description     *string     `json:"description"`
	Trainer         *string     `json:"trainer"`
	TrainingType    string      `json:"training_type"`
	StartDate       time.Time   `json:"start_date"`
	EndDate         pgtype.Date `json:"end_date"`
	MaxParticipants *int32      `json:"max_participants"`
	CreatedBy       *int64      `json:"created_by"`
}

func (q *Queries) CreateTraining(ctx context.Context, arg CreateTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, createTraining,
		arg.CompanyID,
		arg.Title,
		arg.Description,
		arg.Trainer,
		arg.TrainingType,
		arg.StartDate,
		arg.EndDate,
		arg.MaxParticipants,
		arg.CreatedBy,
	)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Trainer,
		&i.TrainingType,
		&i.StartDate,
		&i.EndDate,
		&i.MaxParticipants,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCertification = `-- name: DeleteCertification :exec
DELETE FROM certifications WHERE id = $1 AND company_id = $2
`

type DeleteCertificationParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) DeleteCertification(ctx context.Context, arg DeleteCertificationParams) error {
	_, err := q.db.Exec(ctx, deleteCertification, arg.ID, arg.CompanyID)
	return err
}

const getTraining = `-- name: GetTraining :one
SELECT id, company_id, title, description, trainer, training_type, start_date, end_date, max_participants, status, created_by, created_at, updated_at FROM trainings WHERE id = $1 AND company_id = $2
`

type GetTrainingParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetTraining(ctx context.Context, arg GetTrainingParams) (Training, error) {
	row := q.db.QueryRow(ctx, getTraining, arg.ID, arg.CompanyID)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Trainer,
		&i.TrainingType,
		&i.StartDate,
		&i.EndDate,
		&i.MaxParticipants,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCertifications = `-- name: ListCertifications :many
SELECT c.id, c.company_id, c.employee_id, c.name, c.issuing_body, c.credential_id, c.issue_date, c.expiry_date, c.status, c.attachment_path, c.created_at, c.updated_at, e.employee_no, e.first_name, e.last_name
FROM certifications c
JOIN employees e ON e.id = c.employee_id
WHERE c.company_id = $1
  AND ($2::bigint IS NULL OR $2 = 0 OR c.employee_id = $2)
ORDER BY c.issue_date DESC
LIMIT $3 OFFSET $4
`

type ListCertificationsParams struct {
	CompanyID int64 `json:"company_id"`
	Column2   int64 `json:"column_2"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListCertificationsRow struct {
	ID             int64       `json:"id"`
	CompanyID      int64       `json:"company_id"`
	EmployeeID     int64       `json:"employee_id"`
	Name           string      `json:"name"`
	IssuingBody    *string     `json:"issuing_body"`
	CredentialID   *string     `json:"credential_id"`
	IssueDate      time.Time   `json:"issue_date"`
	ExpiryDate     pgtype.Date `json:"expiry_date"`
	Status         string      `json:"status"`
	AttachmentPath *string     `json:"attachment_path"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	EmployeeNo     string      `json:"employee_no"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
}

func (q *Queries) ListCertifications(ctx context.Context, arg ListCertificationsParams) ([]ListCertificationsRow, error) {
	rows, err := q.db.Query(ctx, listCertifications,
		arg.CompanyID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCertificationsRow{}
	for rows.Next() {
		var i ListCertificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.Name,
			&i.IssuingBody,
			&i.CredentialID,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.Status,
			&i.AttachmentPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringCertifications = `-- name: ListExpiringCertifications :many
SELECT c.id, c.company_id, c.employee_id, c.name, c.issuing_body, c.credential_id, c.issue_date, c.expiry_date, c.status, c.attachment_path, c.created_at, c.updated_at, e.employee_no, e.first_name, e.last_name
FROM certifications c
JOIN employees e ON e.id = c.employee_id
WHERE c.company_id = $1
  AND c.status = 'active'
  AND c.expiry_date IS NOT NULL
  AND c.expiry_date <= CURRENT_DATE + INTERVAL '90 days'
ORDER BY c.expiry_date
`

type ListExpiringCertificationsRow struct {
	ID             int64       `json:"id"`
	CompanyID      int64       `json:"company_id"`
	EmployeeID     int64       `json:"employee_id"`
	Name           string      `json:"name"`
	IssuingBody    *string     `json:"issuing_body"`
	CredentialID   *string     `json:"credential_id"`
	IssueDate      time.Time   `json:"issue_date"`
	ExpiryDate     pgtype.Date `json:"expiry_date"`
	Status         string      `json:"status"`
	AttachmentPath *string     `json:"attachment_path"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	EmployeeNo     string      `json:"employee_no"`
	FirstName      string      `json:"first_name"`
	LastName       string      `json:"last_name"`
}

func (q *Queries) ListExpiringCertifications(ctx context.Context, companyID int64) ([]ListExpiringCertificationsRow, error) {
	rows, err := q.db.Query(ctx, listExpiringCertifications, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpiringCertificationsRow{}
	for rows.Next() {
		var i ListExpiringCertificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.Name,
			&i.IssuingBody,
			&i.CredentialID,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.Status,
			&i.AttachmentPath,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyCertifications = `-- name: ListMyCertifications :many
SELECT id, company_id, employee_id, name, issuing_body, credential_id, issue_date, expiry_date, status, attachment_path, created_at, updated_at FROM certifications
WHERE employee_id = $1 AND company_id = $2
ORDER BY issue_date DESC
`

type ListMyCertificationsParams struct {
	EmployeeID int64 `json:"employee_id"`
	CompanyID  int64 `json:"company_id"`
}

func (q *Queries) ListMyCertifications(ctx context.Context, arg ListMyCertificationsParams) ([]Certification, error) {
	rows, err := q.db.Query(ctx, listMyCertifications, arg.EmployeeID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Certification{}
	for rows.Next() {
		var i Certification
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.Name,
			&i.IssuingBody,
			&i.CredentialID,
			&i.IssueDate,
			&i.ExpiryDate,
			&i.Status,
			&i.AttachmentPath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyTrainings = `-- name: ListMyTrainings :many
SELECT t.id, t.title, t.trainer, t.training_type, t.start_date, t.end_date,
       t.status as training_status, tp.status as participant_status, tp.score
FROM training_participants tp
JOIN trainings t ON t.id = tp.training_id
WHERE tp.employee_id = $1 AND t.company_id = $2
ORDER BY t.start_date DESC
`

type ListMyTrainingsParams struct {
	EmployeeID int64 `json:"employee_id"`
	CompanyID  int64 `json:"company_id"`
}

type ListMyTrainingsRow struct {
	ID                int64          `json:"id"`
	Title             string         `json:"title"`
	Trainer           *string        `json:"trainer"`
	TrainingType      string         `json:"training_type"`
	StartDate         time.Time      `json:"start_date"`
	EndDate           pgtype.Date    `json:"end_date"`
	TrainingStatus    string         `json:"training_status"`
	ParticipantStatus string         `json:"participant_status"`
	Score             pgtype.Numeric `json:"score"`
}

func (q *Queries) ListMyTrainings(ctx context.Context, arg ListMyTrainingsParams) ([]ListMyTrainingsRow, error) {
	rows, err := q.db.Query(ctx, listMyTrainings, arg.EmployeeID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyTrainingsRow{}
	for rows.Next() {
		var i ListMyTrainingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Trainer,
			&i.TrainingType,
			&i.StartDate,
			&i.EndDate,
			&i.TrainingStatus,
			&i.ParticipantStatus,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingParticipants = `-- name: ListTrainingParticipants :many
SELECT tp.id, tp.training_id, tp.employee_id, tp.status, tp.score, tp.feedback, tp.completed_at, tp.created_at, e.employee_no, e.first_name, e.last_name
FROM training_participants tp
JOIN employees e ON e.id = tp.employee_id
JOIN trainings t ON t.id = tp.training_id
WHERE tp.training_id = $1 AND t.company_id = $2
ORDER BY e.last_name, e.first_name
`

type ListTrainingParticipantsParams struct {
	TrainingID int64 `json:"training_id"`
	CompanyID  int64 `json:"company_id"`
}

type ListTrainingParticipantsRow struct {
	ID          int64              `json:"id"`
	TrainingID  int64              `json:"training_id"`
	EmployeeID  int64              `json:"employee_id"`
	Status      string             `json:"status"`
	Score       pgtype.Numeric     `json:"score"`
	Feedback    *string            `json:"feedback"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	CreatedAt   time.Time          `json:"created_at"`
	EmployeeNo  string             `json:"employee_no"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
}

func (q *Queries) ListTrainingParticipants(ctx context.Context, arg ListTrainingParticipantsParams) ([]ListTrainingParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listTrainingParticipants, arg.TrainingID, arg.CompanyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrainingParticipantsRow{}
	for rows.Next() {
		var i ListTrainingParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TrainingID,
			&i.EmployeeID,
			&i.Status,
			&i.Score,
			&i.Feedback,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.EmployeeNo,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainings = `-- name: ListTrainings :many
SELECT t.id, t.company_id, t.title, t.description, t.trainer, t.training_type, t.start_date, t.end_date, t.max_participants, t.status, t.created_by, t.created_at, t.updated_at, u.email as created_by_email,
       (SELECT COUNT(*) FROM training_participants tp WHERE tp.training_id = t.id) as participant_count
FROM trainings t
LEFT JOIN users u ON u.id = t.created_by
WHERE t.company_id = $1
ORDER BY t.start_date DESC
LIMIT $2 OFFSET $3
`

type ListTrainingsParams struct {
	CompanyID int64 `json:"company_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListTrainingsRow struct {
	ID               int64       `json:"id"`
	CompanyID        int64       `json:"company_id"`
	Title            string      `json:"title"`
	Description      *string     `json:"description"`
	Trainer          *string     `json:"trainer"`
	TrainingType     string      `json:"training_type"`
	StartDate        time.Time   `json:"start_date"`
	EndDate          pgtype.Date `json:"end_date"`
	MaxParticipants  *int32      `json:"max_participants"`
	Status           string      `json:"status"`
	CreatedBy        *int64      `json:"created_by"`
	CreatedAt        time.Time   `json:"created_at"`
	UpdatedAt        time.Time   `json:"updated_at"`
	CreatedByEmail   *string     `json:"created_by_email"`
	ParticipantCount int64       `json:"participant_count"`
}

func (q *Queries) ListTrainings(ctx context.Context, arg ListTrainingsParams) ([]ListTrainingsRow, error) {
	rows, err := q.db.Query(ctx, listTrainings, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrainingsRow{}
	for rows.Next() {
		var i ListTrainingsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Title,
			&i.Description,
			&i.Trainer,
			&i.TrainingType,
			&i.StartDate,
			&i.EndDate,
			&i.MaxParticipants,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedByEmail,
			&i.ParticipantCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateParticipantStatus = `-- name: UpdateParticipantStatus :one
UPDATE training_participants SET
    status = $3,
    score = $4,
    completed_at = CASE WHEN $3 = 'completed' THEN NOW() ELSE completed_at END,
    feedback = $5
WHERE id = $1 AND training_id = $2
RETURNING id, training_id, employee_id, status, score, feedback, completed_at, created_at
`

type UpdateParticipantStatusParams struct {
	ID         int64          `json:"id"`
	TrainingID int64          `json:"training_id"`
	Status     string         `json:"status"`
	Score      pgtype.Numeric `json:"score"`
	Feedback   *string        `json:"feedback"`
}

func (q *Queries) UpdateParticipantStatus(ctx context.Context, arg UpdateParticipantStatusParams) (TrainingParticipant, error) {
	row := q.db.QueryRow(ctx, updateParticipantStatus,
		arg.ID,
		arg.TrainingID,
		arg.Status,
		arg.Score,
		arg.Feedback,
	)
	var i TrainingParticipant
	err := row.Scan(
		&i.ID,
		&i.TrainingID,
		&i.EmployeeID,
		&i.Status,
		&i.Score,
		&i.Feedback,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateTrainingStatus = `-- name: UpdateTrainingStatus :one
UPDATE trainings SET status = $3, updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, title, description, trainer, training_type, start_date, end_date, max_participants, status, created_by, created_at, updated_at
`

type UpdateTrainingStatusParams struct {
	ID        int64  `json:"id"`
	CompanyID int64  `json:"company_id"`
	Status    string `json:"status"`
}

func (q *Queries) UpdateTrainingStatus(ctx context.Context, arg UpdateTrainingStatusParams) (Training, error) {
	row := q.db.QueryRow(ctx, updateTrainingStatus, arg.ID, arg.CompanyID, arg.Status)
	var i Training
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Title,
		&i.Description,
		&i.Trainer,
		&i.TrainingType,
		&i.StartDate,
		&i.EndDate,
		&i.MaxParticipants,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
