// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_companies.sql

package store

import (
	"context"
)

const getUserCompanies = `-- name: GetUserCompanies :many
SELECT c.id, c.name, c.country, c.timezone, c.currency, c.logo_url
FROM user_companies uc
JOIN companies c ON c.id = uc.company_id
WHERE uc.user_id = $1
ORDER BY c.name
`

type GetUserCompaniesRow struct {
	ID       int64   `json:"id"`
	Name     string  `json:"name"`
	Country  string  `json:"country"`
	Timezone string  `json:"timezone"`
	Currency string  `json:"currency"`
	LogoUrl  *string `json:"logo_url"`
}

func (q *Queries) GetUserCompanies(ctx context.Context, userID int64) ([]GetUserCompaniesRow, error) {
	rows, err := q.db.Query(ctx, getUserCompanies, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserCompaniesRow{}
	for rows.Next() {
		var i GetUserCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Country,
			&i.Timezone,
			&i.Currency,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCompanyMembership = `-- name: GetUserCompanyMembership :one
SELECT user_id, company_id, role, joined_at
FROM user_companies
WHERE user_id = $1 AND company_id = $2
`

type GetUserCompanyMembershipParams struct {
	UserID    int64 `json:"user_id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) GetUserCompanyMembership(ctx context.Context, arg GetUserCompanyMembershipParams) (UserCompany, error) {
	row := q.db.QueryRow(ctx, getUserCompanyMembership, arg.UserID, arg.CompanyID)
	var i UserCompany
	err := row.Scan(
		&i.UserID,
		&i.CompanyID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const insertUserCompany = `-- name: InsertUserCompany :exec
INSERT INTO user_companies (user_id, company_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, company_id) DO NOTHING
`

type InsertUserCompanyParams struct {
	UserID    int64  `json:"user_id"`
	CompanyID int64  `json:"company_id"`
	Role      string `json:"role"`
}

func (q *Queries) InsertUserCompany(ctx context.Context, arg InsertUserCompanyParams) error {
	_, err := q.db.Exec(ctx, insertUserCompany, arg.UserID, arg.CompanyID, arg.Role)
	return err
}

const updateUserActiveCompany = `-- name: UpdateUserActiveCompany :exec
UPDATE users SET company_id = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateUserActiveCompanyParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) UpdateUserActiveCompany(ctx context.Context, arg UpdateUserActiveCompanyParams) error {
	_, err := q.db.Exec(ctx, updateUserActiveCompany, arg.ID, arg.CompanyID)
	return err
}
