// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: virtual_office.sql

package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignSeat = `-- name: AssignSeat :one
INSERT INTO virtual_office_seats (company_id, employee_id, floor, zone, seat_x, seat_y)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, company_id, employee_id, floor, zone, seat_x, seat_y, avatar_type, avatar_color, custom_status, custom_emoji, manual_status, meeting_room_zone, created_at, updated_at
`

type AssignSeatParams struct {
	CompanyID  int64  `json:"company_id"`
	EmployeeID int64  `json:"employee_id"`
	Floor      int32  `json:"floor"`
	Zone       string `json:"zone"`
	SeatX      int32  `json:"seat_x"`
	SeatY      int32  `json:"seat_y"`
}

func (q *Queries) AssignSeat(ctx context.Context, arg AssignSeatParams) (VirtualOfficeSeat, error) {
	row := q.db.QueryRow(ctx, assignSeat,
		arg.CompanyID,
		arg.EmployeeID,
		arg.Floor,
		arg.Zone,
		arg.SeatX,
		arg.SeatY,
	)
	var i VirtualOfficeSeat
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.Floor,
		&i.Zone,
		&i.SeatX,
		&i.SeatY,
		&i.AvatarType,
		&i.AvatarColor,
		&i.CustomStatus,
		&i.CustomEmoji,
		&i.ManualStatus,
		&i.MeetingRoomZone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeatByEmployee = `-- name: GetSeatByEmployee :one
SELECT id, company_id, employee_id, floor, zone, seat_x, seat_y, avatar_type, avatar_color, custom_status, custom_emoji, manual_status, meeting_room_zone, created_at, updated_at FROM virtual_office_seats WHERE company_id = $1 AND employee_id = $2
`

type GetSeatByEmployeeParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
}

func (q *Queries) GetSeatByEmployee(ctx context.Context, arg GetSeatByEmployeeParams) (VirtualOfficeSeat, error) {
	row := q.db.QueryRow(ctx, getSeatByEmployee, arg.CompanyID, arg.EmployeeID)
	var i VirtualOfficeSeat
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EmployeeID,
		&i.Floor,
		&i.Zone,
		&i.SeatX,
		&i.SeatY,
		&i.AvatarType,
		&i.AvatarColor,
		&i.CustomStatus,
		&i.CustomEmoji,
		&i.ManualStatus,
		&i.MeetingRoomZone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSnapshotSeats = `-- name: GetSnapshotSeats :many
WITH today_leaves AS (
    SELECT DISTINCT ON (lr.employee_id)
           lr.employee_id, lt.name AS leave_type
    FROM leave_requests lr
    JOIN leave_types lt ON lt.id = lr.leave_type_id
    WHERE lr.company_id = $1
      AND lr.status = 'approved'
      AND CURRENT_DATE BETWEEN lr.start_date AND lr.end_date
    ORDER BY lr.employee_id, lr.created_at DESC
),
today_attendance AS (
    SELECT DISTINCT ON (employee_id)
           employee_id,
           clock_in_at,
           clock_out_at,
           late_minutes
    FROM attendance_logs
    WHERE company_id = $1
      AND clock_in_at >= CURRENT_DATE
      AND clock_in_at < CURRENT_DATE + INTERVAL '1 day'
    ORDER BY employee_id, clock_in_at DESC
)
SELECT
    s.id AS seat_id,
    s.employee_id,
    e.first_name || ' ' || e.last_name AS name,
    COALESCE(p.title, '') AS position,
    COALESCE(d.name, '') AS department,
    s.floor,
    s.zone,
    s.seat_x,
    s.seat_y,
    s.avatar_type,
    s.avatar_color,
    s.custom_status,
    s.custom_emoji,
    s.manual_status,
    s.meeting_room_zone,
    tl.leave_type,
    ta.clock_in_at,
    ta.clock_out_at,
    COALESCE(ta.late_minutes, 0) AS late_minutes
FROM virtual_office_seats s
JOIN employees e ON e.id = s.employee_id AND e.company_id = s.company_id
LEFT JOIN positions p ON p.id = e.position_id
LEFT JOIN departments d ON d.id = e.department_id
LEFT JOIN today_leaves tl ON tl.employee_id = s.employee_id
LEFT JOIN today_attendance ta ON ta.employee_id = s.employee_id
WHERE s.company_id = $1
  AND e.status IN ('active', 'probationary')
ORDER BY s.floor, s.zone, s.seat_y, s.seat_x
`

type GetSnapshotSeatsRow struct {
	SeatID          int64              `json:"seat_id"`
	EmployeeID      int64              `json:"employee_id"`
	Name            interface{}        `json:"name"`
	Position        string             `json:"position"`
	Department      string             `json:"department"`
	Floor           int32              `json:"floor"`
	Zone            string             `json:"zone"`
	SeatX           int32              `json:"seat_x"`
	SeatY           int32              `json:"seat_y"`
	AvatarType      string             `json:"avatar_type"`
	AvatarColor     string             `json:"avatar_color"`
	CustomStatus    *string            `json:"custom_status"`
	CustomEmoji     *string            `json:"custom_emoji"`
	ManualStatus    *string            `json:"manual_status"`
	MeetingRoomZone *string            `json:"meeting_room_zone"`
	LeaveType       *string            `json:"leave_type"`
	ClockInAt       pgtype.Timestamptz `json:"clock_in_at"`
	ClockOutAt      pgtype.Timestamptz `json:"clock_out_at"`
	LateMinutes     int32              `json:"late_minutes"`
}

func (q *Queries) GetSnapshotSeats(ctx context.Context, companyID int64) ([]GetSnapshotSeatsRow, error) {
	rows, err := q.db.Query(ctx, getSnapshotSeats, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSnapshotSeatsRow{}
	for rows.Next() {
		var i GetSnapshotSeatsRow
		if err := rows.Scan(
			&i.SeatID,
			&i.EmployeeID,
			&i.Name,
			&i.Position,
			&i.Department,
			&i.Floor,
			&i.Zone,
			&i.SeatX,
			&i.SeatY,
			&i.AvatarType,
			&i.AvatarColor,
			&i.CustomStatus,
			&i.CustomEmoji,
			&i.ManualStatus,
			&i.MeetingRoomZone,
			&i.LeaveType,
			&i.ClockInAt,
			&i.ClockOutAt,
			&i.LateMinutes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVirtualOfficeConfig = `-- name: GetVirtualOfficeConfig :one
SELECT company_id, template, created_at, updated_at FROM virtual_office_config WHERE company_id = $1
`

func (q *Queries) GetVirtualOfficeConfig(ctx context.Context, companyID int64) (VirtualOfficeConfig, error) {
	row := q.db.QueryRow(ctx, getVirtualOfficeConfig, companyID)
	var i VirtualOfficeConfig
	err := row.Scan(
		&i.CompanyID,
		&i.Template,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOccupiedPositions = `-- name: ListOccupiedPositions :many
SELECT floor, seat_x, seat_y FROM virtual_office_seats WHERE company_id = $1
`

type ListOccupiedPositionsRow struct {
	Floor int32 `json:"floor"`
	SeatX int32 `json:"seat_x"`
	SeatY int32 `json:"seat_y"`
}

func (q *Queries) ListOccupiedPositions(ctx context.Context, companyID int64) ([]ListOccupiedPositionsRow, error) {
	rows, err := q.db.Query(ctx, listOccupiedPositions, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOccupiedPositionsRow{}
	for rows.Next() {
		var i ListOccupiedPositionsRow
		if err := rows.Scan(&i.Floor, &i.SeatX, &i.SeatY); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSeats = `-- name: ListSeats :many
SELECT s.id, s.company_id, s.employee_id, s.floor, s.zone, s.seat_x, s.seat_y, s.avatar_type, s.avatar_color, s.custom_status, s.custom_emoji, s.manual_status, s.meeting_room_zone, s.created_at, s.updated_at, e.first_name, e.last_name,
       COALESCE(d.name, '') AS department_name
FROM virtual_office_seats s
JOIN employees e ON e.id = s.employee_id
LEFT JOIN departments d ON d.id = e.department_id
WHERE s.company_id = $1
ORDER BY s.floor, s.zone, s.seat_y, s.seat_x
`

type ListSeatsRow struct {
	ID              int64     `json:"id"`
	CompanyID       int64     `json:"company_id"`
	EmployeeID      int64     `json:"employee_id"`
	Floor           int32     `json:"floor"`
	Zone            string    `json:"zone"`
	SeatX           int32     `json:"seat_x"`
	SeatY           int32     `json:"seat_y"`
	AvatarType      string    `json:"avatar_type"`
	AvatarColor     string    `json:"avatar_color"`
	CustomStatus    *string   `json:"custom_status"`
	CustomEmoji     *string   `json:"custom_emoji"`
	ManualStatus    *string   `json:"manual_status"`
	MeetingRoomZone *string   `json:"meeting_room_zone"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
	FirstName       string    `json:"first_name"`
	LastName        string    `json:"last_name"`
	DepartmentName  string    `json:"department_name"`
}

func (q *Queries) ListSeats(ctx context.Context, companyID int64) ([]ListSeatsRow, error) {
	rows, err := q.db.Query(ctx, listSeats, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSeatsRow{}
	for rows.Next() {
		var i ListSeatsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EmployeeID,
			&i.Floor,
			&i.Zone,
			&i.SeatX,
			&i.SeatY,
			&i.AvatarType,
			&i.AvatarColor,
			&i.CustomStatus,
			&i.CustomEmoji,
			&i.ManualStatus,
			&i.MeetingRoomZone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnassignedActiveEmployees = `-- name: ListUnassignedActiveEmployees :many
SELECT e.id, e.first_name, e.last_name, e.department_id
FROM employees e
WHERE e.company_id = $1
  AND e.status IN ('active', 'probationary')
  AND NOT EXISTS (
    SELECT 1 FROM virtual_office_seats s
    WHERE s.company_id = e.company_id AND s.employee_id = e.id
  )
ORDER BY e.department_id, e.last_name, e.first_name
`

type ListUnassignedActiveEmployeesRow struct {
	ID           int64  `json:"id"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
	DepartmentID *int64 `json:"department_id"`
}

func (q *Queries) ListUnassignedActiveEmployees(ctx context.Context, companyID int64) ([]ListUnassignedActiveEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listUnassignedActiveEmployees, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnassignedActiveEmployeesRow{}
	for rows.Next() {
		var i ListUnassignedActiveEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DepartmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSeat = `-- name: RemoveSeat :exec
DELETE FROM virtual_office_seats WHERE company_id = $1 AND employee_id = $2
`

type RemoveSeatParams struct {
	CompanyID  int64 `json:"company_id"`
	EmployeeID int64 `json:"employee_id"`
}

func (q *Queries) RemoveSeat(ctx context.Context, arg RemoveSeatParams) error {
	_, err := q.db.Exec(ctx, removeSeat, arg.CompanyID, arg.EmployeeID)
	return err
}

const updateSeatAvatar = `-- name: UpdateSeatAvatar :exec
UPDATE virtual_office_seats SET
    avatar_type = $3,
    avatar_color = $4,
    updated_at = NOW()
WHERE company_id = $1 AND employee_id = $2
`

type UpdateSeatAvatarParams struct {
	CompanyID   int64  `json:"company_id"`
	EmployeeID  int64  `json:"employee_id"`
	AvatarType  string `json:"avatar_type"`
	AvatarColor string `json:"avatar_color"`
}

func (q *Queries) UpdateSeatAvatar(ctx context.Context, arg UpdateSeatAvatarParams) error {
	_, err := q.db.Exec(ctx, updateSeatAvatar,
		arg.CompanyID,
		arg.EmployeeID,
		arg.AvatarType,
		arg.AvatarColor,
	)
	return err
}

const updateSeatStatus = `-- name: UpdateSeatStatus :exec
UPDATE virtual_office_seats SET
    custom_status = $3,
    custom_emoji = $4,
    manual_status = $5,
    meeting_room_zone = $6,
    updated_at = NOW()
WHERE company_id = $1 AND employee_id = $2
`

type UpdateSeatStatusParams struct {
	CompanyID       int64   `json:"company_id"`
	EmployeeID      int64   `json:"employee_id"`
	CustomStatus    *string `json:"custom_status"`
	CustomEmoji     *string `json:"custom_emoji"`
	ManualStatus    *string `json:"manual_status"`
	MeetingRoomZone *string `json:"meeting_room_zone"`
}

func (q *Queries) UpdateSeatStatus(ctx context.Context, arg UpdateSeatStatusParams) error {
	_, err := q.db.Exec(ctx, updateSeatStatus,
		arg.CompanyID,
		arg.EmployeeID,
		arg.CustomStatus,
		arg.CustomEmoji,
		arg.ManualStatus,
		arg.MeetingRoomZone,
	)
	return err
}

const upsertVirtualOfficeConfig = `-- name: UpsertVirtualOfficeConfig :one
INSERT INTO virtual_office_config (company_id, template)
VALUES ($1, $2)
ON CONFLICT (company_id)
DO UPDATE SET template = $2, updated_at = NOW()
RETURNING company_id, template, created_at, updated_at
`

type UpsertVirtualOfficeConfigParams struct {
	CompanyID int64  `json:"company_id"`
	Template  string `json:"template"`
}

func (q *Queries) UpsertVirtualOfficeConfig(ctx context.Context, arg UpsertVirtualOfficeConfigParams) (VirtualOfficeConfig, error) {
	row := q.db.QueryRow(ctx, upsertVirtualOfficeConfig, arg.CompanyID, arg.Template)
	var i VirtualOfficeConfig
	err := row.Scan(
		&i.CompanyID,
		&i.Template,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
