// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_agent.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDecisionsByOutcome = `-- name: CountDecisionsByOutcome :many
SELECT decision, COUNT(*) as count
FROM workflow_decisions
WHERE company_id = $1
  AND created_at > NOW() - INTERVAL '30 days'
GROUP BY decision
`

type CountDecisionsByOutcomeRow struct {
	Decision string `json:"decision"`
	Count    int64  `json:"count"`
}

func (q *Queries) CountDecisionsByOutcome(ctx context.Context, companyID int64) ([]CountDecisionsByOutcomeRow, error) {
	rows, err := q.db.Query(ctx, countDecisionsByOutcome, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDecisionsByOutcomeRow{}
	for rows.Next() {
		var i CountDecisionsByOutcomeRow
		if err := rows.Scan(&i.Decision, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWorkflowDecisions = `-- name: CountWorkflowDecisions :one
SELECT COUNT(*) FROM workflow_decisions
WHERE company_id = $1
  AND ($2::varchar = '' OR entity_type = $2)
  AND ($3::bigint IS NULL OR $3 = 0 OR entity_id = $3)
  AND ($4::boolean IS NULL OR $4 = false OR overridden_at IS NOT NULL)
`

type CountWorkflowDecisionsParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Column3   int64  `json:"column_3"`
	Column4   bool   `json:"column_4"`
}

func (q *Queries) CountWorkflowDecisions(ctx context.Context, arg CountWorkflowDecisionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkflowDecisions,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createWorkflowTrigger = `-- name: CreateWorkflowTrigger :one
INSERT INTO workflow_triggers (company_id, name, description, trigger_type, entity_type, trigger_config, action_type, action_config, priority, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, name, description, trigger_type, entity_type, trigger_config, action_type, action_config, priority, is_active, created_by, created_at, updated_at
`

type CreateWorkflowTriggerParams struct {
	CompanyID     int64           `json:"company_id"`
	Name          string          `json:"name"`
	Description   *string         `json:"description"`
	TriggerType   string          `json:"trigger_type"`
	EntityType    string          `json:"entity_type"`
	TriggerConfig json.RawMessage `json:"trigger_config"`
	ActionType    string          `json:"action_type"`
	ActionConfig  json.RawMessage `json:"action_config"`
	Priority      int32           `json:"priority"`
	CreatedBy     *int64          `json:"created_by"`
}

func (q *Queries) CreateWorkflowTrigger(ctx context.Context, arg CreateWorkflowTriggerParams) (WorkflowTrigger, error) {
	row := q.db.QueryRow(ctx, createWorkflowTrigger,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.EntityType,
		arg.TriggerConfig,
		arg.ActionType,
		arg.ActionConfig,
		arg.Priority,
		arg.CreatedBy,
	)
	var i WorkflowTrigger
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.EntityType,
		&i.TriggerConfig,
		&i.ActionType,
		&i.ActionConfig,
		&i.Priority,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateWorkflowTrigger = `-- name: DeactivateWorkflowTrigger :exec
UPDATE workflow_triggers SET is_active = false, updated_at = NOW()
WHERE id = $1 AND company_id = $2
`

type DeactivateWorkflowTriggerParams struct {
	ID        int64 `json:"id"`
	CompanyID int64 `json:"company_id"`
}

func (q *Queries) DeactivateWorkflowTrigger(ctx context.Context, arg DeactivateWorkflowTriggerParams) error {
	_, err := q.db.Exec(ctx, deactivateWorkflowTrigger, arg.ID, arg.CompanyID)
	return err
}

const getAgentDecisionStats = `-- name: GetAgentDecisionStats :one
SELECT
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE executed = true) as auto_executed,
    COUNT(*) FILTER (WHERE decision LIKE 'recommend_%') as recommended,
    COUNT(*) FILTER (WHERE decision = 'escalate') as escalated,
    COUNT(*) FILTER (WHERE overridden_at IS NOT NULL) as overridden,
    COALESCE(AVG(confidence::numeric), 0) as avg_confidence
FROM workflow_decisions
WHERE company_id = $1
  AND created_at > NOW() - INTERVAL '30 days'
`

type GetAgentDecisionStatsRow struct {
	Total         int64       `json:"total"`
	AutoExecuted  int64       `json:"auto_executed"`
	Recommended   int64       `json:"recommended"`
	Escalated     int64       `json:"escalated"`
	Overridden    int64       `json:"overridden"`
	AvgConfidence interface{} `json:"avg_confidence"`
}

func (q *Queries) GetAgentDecisionStats(ctx context.Context, companyID int64) (GetAgentDecisionStatsRow, error) {
	row := q.db.QueryRow(ctx, getAgentDecisionStats, companyID)
	var i GetAgentDecisionStatsRow
	err := row.Scan(
		&i.Total,
		&i.AutoExecuted,
		&i.Recommended,
		&i.Escalated,
		&i.Overridden,
		&i.AvgConfidence,
	)
	return i, err
}

const getDecisionAccuracyRate = `-- name: GetDecisionAccuracyRate :many
SELECT
    CASE
        WHEN confidence::numeric >= 0.90 THEN 'high'
        WHEN confidence::numeric >= 0.70 THEN 'medium'
        ELSE 'low'
    END as confidence_tier,
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE overridden_at IS NOT NULL) as overridden
FROM workflow_decisions
WHERE company_id = $1
  AND created_at > NOW() - INTERVAL '30 days'
GROUP BY confidence_tier
`

type GetDecisionAccuracyRateRow struct {
	ConfidenceTier string `json:"confidence_tier"`
	Total          int64  `json:"total"`
	Overridden     int64  `json:"overridden"`
}

func (q *Queries) GetDecisionAccuracyRate(ctx context.Context, companyID int64) ([]GetDecisionAccuracyRateRow, error) {
	rows, err := q.db.Query(ctx, getDecisionAccuracyRate, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDecisionAccuracyRateRow{}
	for rows.Next() {
		var i GetDecisionAccuracyRateRow
		if err := rows.Scan(&i.ConfidenceTier, &i.Total, &i.Overridden); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDecisionForEntity = `-- name: GetDecisionForEntity :one
SELECT id, company_id, trigger_id, entity_type, entity_id, decision, confidence, reasoning, context_snapshot, ai_agent_slug, tokens_used, executed, executed_at, execution_result, overridden_by, override_action, override_reason, overridden_at, created_at FROM workflow_decisions
WHERE entity_type = $1 AND entity_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetDecisionForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) GetDecisionForEntity(ctx context.Context, arg GetDecisionForEntityParams) (WorkflowDecision, error) {
	row := q.db.QueryRow(ctx, getDecisionForEntity, arg.EntityType, arg.EntityID)
	var i WorkflowDecision
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TriggerID,
		&i.EntityType,
		&i.EntityID,
		&i.Decision,
		&i.Confidence,
		&i.Reasoning,
		&i.ContextSnapshot,
		&i.AiAgentSlug,
		&i.TokensUsed,
		&i.Executed,
		&i.ExecutedAt,
		&i.ExecutionResult,
		&i.OverriddenBy,
		&i.OverrideAction,
		&i.OverrideReason,
		&i.OverriddenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getDecisionVolumeByDay = `-- name: GetDecisionVolumeByDay :many
SELECT
    DATE(created_at) as day,
    COUNT(*) as total,
    COUNT(*) FILTER (WHERE executed = true) as auto_executed,
    COUNT(*) FILTER (WHERE decision LIKE 'recommend_%') as recommended,
    COUNT(*) FILTER (WHERE decision = 'escalate') as escalated
FROM workflow_decisions
WHERE company_id = $1
  AND created_at > NOW() - INTERVAL '30 days'
GROUP BY DATE(created_at)
ORDER BY day DESC
`

type GetDecisionVolumeByDayRow struct {
	Day          time.Time `json:"day"`
	Total        int64     `json:"total"`
	AutoExecuted int64     `json:"auto_executed"`
	Recommended  int64     `json:"recommended"`
	Escalated    int64     `json:"escalated"`
}

func (q *Queries) GetDecisionVolumeByDay(ctx context.Context, companyID int64) ([]GetDecisionVolumeByDayRow, error) {
	rows, err := q.db.Query(ctx, getDecisionVolumeByDay, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDecisionVolumeByDayRow{}
	for rows.Next() {
		var i GetDecisionVolumeByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.Total,
			&i.AutoExecuted,
			&i.Recommended,
			&i.Escalated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentApprovalPatterns = `-- name: GetRecentApprovalPatterns :many
SELECT decision, confidence,
       CASE WHEN overridden_at IS NOT NULL THEN true ELSE false END as was_overridden,
       override_action
FROM workflow_decisions
WHERE company_id = $1 AND entity_type = $2
ORDER BY created_at DESC
LIMIT 50
`

type GetRecentApprovalPatternsParams struct {
	CompanyID  int64  `json:"company_id"`
	EntityType string `json:"entity_type"`
}

type GetRecentApprovalPatternsRow struct {
	Decision       string         `json:"decision"`
	Confidence     pgtype.Numeric `json:"confidence"`
	WasOverridden  bool           `json:"was_overridden"`
	OverrideAction *string        `json:"override_action"`
}

func (q *Queries) GetRecentApprovalPatterns(ctx context.Context, arg GetRecentApprovalPatternsParams) ([]GetRecentApprovalPatternsRow, error) {
	rows, err := q.db.Query(ctx, getRecentApprovalPatterns, arg.CompanyID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentApprovalPatternsRow{}
	for rows.Next() {
		var i GetRecentApprovalPatternsRow
		if err := rows.Scan(
			&i.Decision,
			&i.Confidence,
			&i.WasOverridden,
			&i.OverrideAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowDecision = `-- name: GetWorkflowDecision :one
SELECT id, company_id, trigger_id, entity_type, entity_id, decision, confidence, reasoning, context_snapshot, ai_agent_slug, tokens_used, executed, executed_at, execution_result, overridden_by, override_action, override_reason, overridden_at, created_at FROM workflow_decisions WHERE id = $1
`

func (q *Queries) GetWorkflowDecision(ctx context.Context, id int64) (WorkflowDecision, error) {
	row := q.db.QueryRow(ctx, getWorkflowDecision, id)
	var i WorkflowDecision
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TriggerID,
		&i.EntityType,
		&i.EntityID,
		&i.Decision,
		&i.Confidence,
		&i.Reasoning,
		&i.ContextSnapshot,
		&i.AiAgentSlug,
		&i.TokensUsed,
		&i.Executed,
		&i.ExecutedAt,
		&i.ExecutionResult,
		&i.OverriddenBy,
		&i.OverrideAction,
		&i.OverrideReason,
		&i.OverriddenAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasDecisionForEntity = `-- name: HasDecisionForEntity :one
SELECT EXISTS(
    SELECT 1 FROM workflow_decisions
    WHERE entity_type = $1 AND entity_id = $2
) AS has_decision
`

type HasDecisionForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) HasDecisionForEntity(ctx context.Context, arg HasDecisionForEntityParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasDecisionForEntity, arg.EntityType, arg.EntityID)
	var has_decision bool
	err := row.Scan(&has_decision)
	return has_decision, err
}

const insertWorkflowDecision = `-- name: InsertWorkflowDecision :one
INSERT INTO workflow_decisions (
    company_id, trigger_id, entity_type, entity_id,
    decision, confidence, reasoning, context_snapshot,
    ai_agent_slug, tokens_used
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, company_id, trigger_id, entity_type, entity_id, decision, confidence, reasoning, context_snapshot, ai_agent_slug, tokens_used, executed, executed_at, execution_result, overridden_by, override_action, override_reason, overridden_at, created_at
`

type InsertWorkflowDecisionParams struct {
	CompanyID       int64          `json:"company_id"`
	TriggerID       *int64         `json:"trigger_id"`
	EntityType      string         `json:"entity_type"`
	EntityID        int64          `json:"entity_id"`
	Decision        string         `json:"decision"`
	Confidence      pgtype.Numeric `json:"confidence"`
	Reasoning       *string        `json:"reasoning"`
	ContextSnapshot []byte         `json:"context_snapshot"`
	AiAgentSlug     *string        `json:"ai_agent_slug"`
	TokensUsed      int32          `json:"tokens_used"`
}

func (q *Queries) InsertWorkflowDecision(ctx context.Context, arg InsertWorkflowDecisionParams) (WorkflowDecision, error) {
	row := q.db.QueryRow(ctx, insertWorkflowDecision,
		arg.CompanyID,
		arg.TriggerID,
		arg.EntityType,
		arg.EntityID,
		arg.Decision,
		arg.Confidence,
		arg.Reasoning,
		arg.ContextSnapshot,
		arg.AiAgentSlug,
		arg.TokensUsed,
	)
	var i WorkflowDecision
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.TriggerID,
		&i.EntityType,
		&i.EntityID,
		&i.Decision,
		&i.Confidence,
		&i.Reasoning,
		&i.ContextSnapshot,
		&i.AiAgentSlug,
		&i.TokensUsed,
		&i.Executed,
		&i.ExecutedAt,
		&i.ExecutionResult,
		&i.OverriddenBy,
		&i.OverrideAction,
		&i.OverrideReason,
		&i.OverriddenAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveTriggersForEvent = `-- name: ListActiveTriggersForEvent :many
SELECT id, company_id, name, description, trigger_type, entity_type, trigger_config, action_type, action_config, priority, is_active, created_by, created_at, updated_at FROM workflow_triggers
WHERE company_id = $1
  AND is_active = true
  AND trigger_type = $2
  AND (entity_type = $3 OR entity_type = '*')
ORDER BY priority ASC
`

type ListActiveTriggersForEventParams struct {
	CompanyID   int64  `json:"company_id"`
	TriggerType string `json:"trigger_type"`
	EntityType  string `json:"entity_type"`
}

func (q *Queries) ListActiveTriggersForEvent(ctx context.Context, arg ListActiveTriggersForEventParams) ([]WorkflowTrigger, error) {
	rows, err := q.db.Query(ctx, listActiveTriggersForEvent, arg.CompanyID, arg.TriggerType, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowTrigger{}
	for rows.Next() {
		var i WorkflowTrigger
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.TriggerType,
			&i.EntityType,
			&i.TriggerConfig,
			&i.ActionType,
			&i.ActionConfig,
			&i.Priority,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowDecisions = `-- name: ListWorkflowDecisions :many
SELECT wd.id, wd.company_id, wd.trigger_id, wd.entity_type, wd.entity_id, wd.decision, wd.confidence, wd.reasoning, wd.context_snapshot, wd.ai_agent_slug, wd.tokens_used, wd.executed, wd.executed_at, wd.execution_result, wd.overridden_by, wd.override_action, wd.override_reason, wd.overridden_at, wd.created_at, wt.name as trigger_name
FROM workflow_decisions wd
LEFT JOIN workflow_triggers wt ON wt.id = wd.trigger_id
WHERE wd.company_id = $1
  AND ($2::varchar = '' OR wd.entity_type = $2)
  AND ($3::bigint IS NULL OR $3 = 0 OR wd.entity_id = $3)
  AND ($4::boolean IS NULL OR $4 = false OR wd.overridden_at IS NOT NULL)
ORDER BY wd.created_at DESC
LIMIT $5 OFFSET $6
`

type ListWorkflowDecisionsParams struct {
	CompanyID int64  `json:"company_id"`
	Column2   string `json:"column_2"`
	Column3   int64  `json:"column_3"`
	Column4   bool   `json:"column_4"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

type ListWorkflowDecisionsRow struct {
	ID              int64              `json:"id"`
	CompanyID       int64              `json:"company_id"`
	TriggerID       *int64             `json:"trigger_id"`
	EntityType      string             `json:"entity_type"`
	EntityID        int64              `json:"entity_id"`
	Decision        string             `json:"decision"`
	Confidence      pgtype.Numeric     `json:"confidence"`
	Reasoning       *string            `json:"reasoning"`
	ContextSnapshot []byte             `json:"context_snapshot"`
	AiAgentSlug     *string            `json:"ai_agent_slug"`
	TokensUsed      int32              `json:"tokens_used"`
	Executed        bool               `json:"executed"`
	ExecutedAt      pgtype.Timestamptz `json:"executed_at"`
	ExecutionResult []byte             `json:"execution_result"`
	OverriddenBy    *int64             `json:"overridden_by"`
	OverrideAction  *string            `json:"override_action"`
	OverrideReason  *string            `json:"override_reason"`
	OverriddenAt    pgtype.Timestamptz `json:"overridden_at"`
	CreatedAt       time.Time          `json:"created_at"`
	TriggerName     *string            `json:"trigger_name"`
}

func (q *Queries) ListWorkflowDecisions(ctx context.Context, arg ListWorkflowDecisionsParams) ([]ListWorkflowDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listWorkflowDecisions,
		arg.CompanyID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkflowDecisionsRow{}
	for rows.Next() {
		var i ListWorkflowDecisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.TriggerID,
			&i.EntityType,
			&i.EntityID,
			&i.Decision,
			&i.Confidence,
			&i.Reasoning,
			&i.ContextSnapshot,
			&i.AiAgentSlug,
			&i.TokensUsed,
			&i.Executed,
			&i.ExecutedAt,
			&i.ExecutionResult,
			&i.OverriddenBy,
			&i.OverrideAction,
			&i.OverrideReason,
			&i.OverriddenAt,
			&i.CreatedAt,
			&i.TriggerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkflowTriggers = `-- name: ListWorkflowTriggers :many
SELECT id, company_id, name, description, trigger_type, entity_type, trigger_config, action_type, action_config, priority, is_active, created_by, created_at, updated_at FROM workflow_triggers
WHERE company_id = $1
ORDER BY priority ASC, created_at DESC
`

func (q *Queries) ListWorkflowTriggers(ctx context.Context, companyID int64) ([]WorkflowTrigger, error) {
	rows, err := q.db.Query(ctx, listWorkflowTriggers, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowTrigger{}
	for rows.Next() {
		var i WorkflowTrigger
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.TriggerType,
			&i.EntityType,
			&i.TriggerConfig,
			&i.ActionType,
			&i.ActionConfig,
			&i.Priority,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDecisionExecuted = `-- name: MarkDecisionExecuted :exec
UPDATE workflow_decisions SET
    executed = true,
    executed_at = NOW(),
    execution_result = $2
WHERE id = $1
`

type MarkDecisionExecutedParams struct {
	ID              int64  `json:"id"`
	ExecutionResult []byte `json:"execution_result"`
}

func (q *Queries) MarkDecisionExecuted(ctx context.Context, arg MarkDecisionExecutedParams) error {
	_, err := q.db.Exec(ctx, markDecisionExecuted, arg.ID, arg.ExecutionResult)
	return err
}

const recordDecisionOverride = `-- name: RecordDecisionOverride :exec
UPDATE workflow_decisions SET
    overridden_by = $2,
    override_action = $3,
    override_reason = $4,
    overridden_at = NOW()
WHERE id = $1 AND overridden_at IS NULL
`

type RecordDecisionOverrideParams struct {
	ID             int64   `json:"id"`
	OverriddenBy   *int64  `json:"overridden_by"`
	OverrideAction *string `json:"override_action"`
	OverrideReason *string `json:"override_reason"`
}

func (q *Queries) RecordDecisionOverride(ctx context.Context, arg RecordDecisionOverrideParams) error {
	_, err := q.db.Exec(ctx, recordDecisionOverride,
		arg.ID,
		arg.OverriddenBy,
		arg.OverrideAction,
		arg.OverrideReason,
	)
	return err
}

const updateWorkflowTrigger = `-- name: UpdateWorkflowTrigger :one
UPDATE workflow_triggers SET
    name = $3,
    description = $4,
    trigger_type = $5,
    entity_type = $6,
    trigger_config = $7,
    action_type = $8,
    action_config = $9,
    priority = $10,
    is_active = $11,
    updated_at = NOW()
WHERE id = $1 AND company_id = $2
RETURNING id, company_id, name, description, trigger_type, entity_type, trigger_config, action_type, action_config, priority, is_active, created_by, created_at, updated_at
`

type UpdateWorkflowTriggerParams struct {
	ID            int64           `json:"id"`
	CompanyID     int64           `json:"company_id"`
	Name          string          `json:"name"`
	Description   *string         `json:"description"`
	TriggerType   string          `json:"trigger_type"`
	EntityType    string          `json:"entity_type"`
	TriggerConfig json.RawMessage `json:"trigger_config"`
	ActionType    string          `json:"action_type"`
	ActionConfig  json.RawMessage `json:"action_config"`
	Priority      int32           `json:"priority"`
	IsActive      bool            `json:"is_active"`
}

func (q *Queries) UpdateWorkflowTrigger(ctx context.Context, arg UpdateWorkflowTriggerParams) (WorkflowTrigger, error) {
	row := q.db.QueryRow(ctx, updateWorkflowTrigger,
		arg.ID,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.TriggerType,
		arg.EntityType,
		arg.TriggerConfig,
		arg.ActionType,
		arg.ActionConfig,
		arg.Priority,
		arg.IsActive,
	)
	var i WorkflowTrigger
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.TriggerType,
		&i.EntityType,
		&i.TriggerConfig,
		&i.ActionType,
		&i.ActionConfig,
		&i.Priority,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
